### ISSUE TITLE
mythconverg_restore.pl change_hostname is not processing videos

### ISSUE THREAD

**Issue by jfabernathy** [MythTV/mythtv#1001]
* **Platform**:Linux den-pc 6.8.0-51-generic x86_64 x86_64 x86_64 GNU/Linux

* **MythTV version**:v35 master

* **Package version**:ppa:mythbuntu/35

* **Component**:web app

### What steps will reproduce the bug?

I installed a fresh Linux Mint 22 (ubuntu 24.04) build on a Intel Nuc 11 get Core i7. I installed v35 from the ppa and installed mariadb, then mythtv. I used Web App to do a minimal configuration just so the backend would run then I restored mythconverg from a backup of my production backend. I also copied all the files over from the storage group.

Using the Web app I setup everything correctly. Leaving the Storage Group Videos directory pointing to my default videos directory under /mythtv/Videos but no videos existed in that directory. On my production backend there is an additional directory included pointing to a different drive for all my videos.

However, that was not setup on the new system.  So I'd expect Web App to show nothing on the dashboard for Videos.  It showed, however, all the videos from my old backend.  mythfrontend shows those also but you can't play them and a scan for changes errors out referring to the old system name not found.

I'm thinking I need to setup a new videos directory in Storage group which may or may not clear up the database?

**Comment by jfabernathy** [comment]
So I added a new directory to the Storage Group -Videos and now mythfrontend  Media library -> Watch Videos and hit M -> Scan for Changes find all the videos in the newly added directory, but it still errors out saying Failed to Scan SG Video Host: Kubuntu-closet, which is the name of my old production backend.

**Comment by jfabernathy** [comment]
journalctl output related to mythutil --scanvideo
```
ec 21 08:40:41 den-pc mythbackend[1617]: mythbackend[1617]: E VideoScanner dirscan.cpp:245 (ScanVideoDirectory) MythVideo::ScanVideoDirectory failed to scan /share/Movies/dvd
Dec 21 08:40:41 den-pc mythbackend[1617]: mythbackend[1617]: W VideoScanner videoscan.cpp:292 (verifyFiles) SG(kubuntu-closet) not available. Not removing file :Tulsa King/Tulsa King - s1e1 - Go Wes>
Dec 21 08:40:41 den-pc mythbackend[1617]: mythbackend[1617]: W VideoScanner videoscan.cpp:292 (verifyFiles) SG(kubuntu-closet) not available. Not removing file :Tulsa King/Tulsa King - s1e2 - Center>
Dec 21 08:40:41 den-pc mythbackend[1617]: mythbackend[1617]: W VideoScanner videoscan.cpp:292 (verifyFiles) SG(kubuntu-closet) not available. Not removing file :Tulsa King/Tulsa King - s1e3 - Capric>
Dec 21 08:40:41 den-pc mythbackend[1617]: mythbackend[1617]: W VideoScanner videoscan.cpp:292 (verifyFiles) SG(kubuntu-closet) not available. Not removing file :Tulsa King/Tulsa King - s1e4 - Visita>
Dec 21 08:40:41 den-pc mythbackend[1617]: mythbackend[1617]: W VideoScanner videoscan.cpp:292 (verifyFiles) SG(kubuntu-closet) not available. Not removing file :Tulsa King/Tulsa King - s1e6 - Stable>
Dec 21 08:40:41 den-pc mythbackend[1617]: mythbackend[1617]: W VideoScanner videoscan.cpp:292 (verifyFiles) SG(kubuntu-closet) not available. Not removing file :Tulsa King/Tulsa King - s1e7 - Warr A>
Dec 21 08:40:41 den-pc mythbackend[1617]: mythbackend[1617]: W VideoScanner videoscan.cpp:292 (verifyFiles) SG(kubuntu-closet) not available. Not removing file :Tulsa King/Tulsa King - s1e8 - Adobe >
Dec 21 08:40:41 den-pc mythbackend[1617]: mythbackend[1617]: W VideoScanner videoscan.cpp:292 (verifyFiles) SG(kubuntu-closet) not available. Not removing file :Tulsa King/Tulsa King - s1e9 - Happy >
Dec 21 08:40:41 den-pc mythbackend[1617]: mythbackend[1617]: I MythSocketThread(9) mainserver.cpp:7895 (connectionClosed) Monitor sock(5ff1d5c72e60) 'den-pc' disconnected
~

```

**Comment by bennettpeter** [comment]
It loks like you had a slave backend called kubuntu-closet and it cannot access that slave backend to check if videos are still there. It will not delete them from the database because kubuntu-closet may be down but the files may still exist.

Is that correct, that you had a slave backend?

**Comment by jfabernathy** [comment]
kubuntu-closet was the name of the Master backend that I took the backup of mythconverg from to restore to the new backend.  I then renamed the new backend to den-pc.  So my production backend, kubuntu-closet, should be mirrored in den-pc now and moving forward.  Except I did not move the Videos Storage group directories over to den-pc. 

So I guess the problem to me is that while the database contained the names of all the storage group -> videos that were on the kubuntu-closet backend, once the web app finished setting up the den-pc's storage group directories I'd expect the new mythconverg to be update with no videos listed in the web app. I sort expected them to be there until a mythutil --scanvideos was run.  But that failed as show above. 

At present I've done enough work on the den-pc backend that I no longer have this issue. not sure what fixed it, but it might just be a corner case affecting restoring & renaming databases to new hardware. Hopefully that's not done very often. I expect one more time for me as I've tested the process enough to know what to do when I rebuild my production backend for real, hopefully in a few weeks.

**Comment by bennettpeter** [comment]
The correct way would have been to run this to change the host name after restoring. Did you do that?

/usr/share/mythtv/mythconverg_restore.pl --change_hostname \ 
  --old_hostname="kubuntu-closet" --new_hostname="den-pc"

**Comment by jfabernathy** [comment]
Correct; I first had to unzip the backup and edit the sql file to remove the first line.  You may have seen that discussion on the mailing list.  The I restored the database with the drop and create options. I then did the rename exactly like you showed above. I then use the web app to change all the setup stuff to match the new backend with different capture cards, etc.  All that worked except that the videos showed what was in the database and not in the Videos storage directories on the new backend.

**Comment by jfabernathy** [comment]
If you think it's worth pursuing, I can set aside a day this week to recreate and new den-pc backend on a fresh install and see what happens paying more attention to the video area.  When I get to that part I can free it until we've discussed any test to run.

**Comment by bennettpeter** [comment]
It seems that the host column in videometadata was not updated and still had the old host name
run SELECT * FROM videometadata; and look at the host column.

If you fell like checking it again, it would be helpful. I have changed host name in the past and never noticed a problem with videos, so it may be a new bug.

**Comment by jfabernathy** [comment]
SELECT * FROM videometadata; returns nothing in mythconverg.

**Comment by jfabernathy** [comment]
FYI Monday will be the day I start over with the fresh rebuild. I'll be using Debian 12, mariadb, and v35-master. I build the .deb packages locally.

**Comment by jfabernathy** [comment]
So I completed the fresh install of LMDE6 (debian 12) and installed mythtv master v35 built this morning and overall things went well. I logged everything in a notebook so I can refer back if needed. but I took timeshift snapshots before I started the configuration via localhost:6544 so I can quickly restore and repeat if needed, but don't think I'll need to.

All my mythtv files are on a secondary drive so that just got rsync'ed  with the production backend before I started.

I installed mariadb before mythtv and on first run of the web app the database was setup right.  I setup the language screen and General / Host IP screen; then restarted the backend and it stayed running as expected.

I took the latest backup of mythconverg and unzipped it, deleted the 1st line, and did the restore  dropping the database and creating the database. That went well.

On the rename I got some errors/warnings but the results were I had a working database. console below:
```
$ /usr/share/mythtv/[mythconverg_restore.pl](http://mythconverg_restore.pl/) --change_hostname --old_hostname="kubuntu-closet" --new_hostname="den-pc"
DBD::mysql::st execute failed: Duplicate entry 'OpenGL High Quality-den-pc' for key 'PRIMARY' at /usr/share/mythtv/[mythconverg_restore.pl](http://mythconverg_restore.pl/) line 1395.
Unable to update hostname in table: displayprofilegroups
Duplicate entry 'OpenGL High Quality-den-pc' for key 'PRIMARY'
DBD::mysql::st execute failed: Duplicate entry 'Reload Theme-den-pc' for key 'PRIMARY' at /usr/share/mythtv/[mythconverg_restore.pl](http://mythconverg_restore.pl/) line 1395.
Unable to update hostname in table: jumppoints
Duplicate entry 'Reload Theme-den-pc' for key 'PRIMARY'
DBD::mysql::st execute failed: Duplicate entry 'Global-UP-den-pc' for key 'PRIMARY' at /usr/share/mythtv/[mythconverg_restore.pl](http://mythconverg_restore.pl/) line 1395.
Unable to update hostname in table: keybindings
Duplicate entry 'Global-UP-den-pc' for key 'PRIMARY'
```
At this point I install xmltv and ran the web app to change the Primary Hostname to my den-pc IP address and check the box for this is a primary backend, which changed the read only name of the backend from kubuntu-closet to den-pc. 

I then deleted all the capture cards because they showed as DVB cards from my old backend and I put in HDHR tuners. I then went through and changed all the stuff needed, particularly the Storage Group directories. On the Videos directory I pointed it to the video directory on secondary drive that was empty.

With that done the web app still showed stuff in my Videos tab. However once I ran `mythutil --scanvideos` and checked the log, it showed that the video names from the production backend no longer existed on my new backend.  

Now web app shows no videos in that tab.

So it seems fixed.  It could be that last time there was some issue during hostname renaming or the fact that I tried to rescan the videos via the menu option in the mythfrontend.  But the process I did above shows no issues.  Could have been related to the fact that web app now updates the depreciated variables for hostname IP??

**Comment by bennettpeter** [comment]
This is a bug in the host rename process

The videometadata table stores the host name in a column called "host" instead of "hostname". mythconverg_restore.pl goes through all tablesd renaming the contents of hostname, thus it does not rename in the videometadata table.

To be consistent, we should rename the host column of videometadata. That will require a schema change plus possibly many code changes. Alternatively we could just change mythconverg_restore.pl to process the host column in videometadata.

**Comment by jfabernathy** [comment]
I still have nothing in videometadata. Not sure if I should do anything?? Hopefully this is resolved before I have to rebuild the production backend for real is a few weeks.
```
MariaDB [mythconverg]> select * from videometadata;
Empty set (0.001 sec)

MariaDB [mythconverg]> 
```

**Comment by bennettpeter** [comment]
If there is data in videometadata you can update it manually or delete it and rescan. If you delete and rescan videos you will lose the last played position and watched indicator.

**Comment by jfabernathy** [comment]
I copied a set of videos from my production backend to the Video Storage directory on my new backend and then ran` mythutil --scanvideos`
I checked the Web App and they showed up as expected. I also looked in mysql:
```
MariaDB [mythconverg]> select title,season,episode,host from videometadata;
+---------------------+--------+---------+--------+
| title               | season | episode | host   |
+---------------------+--------+---------+--------+
| The Big Bang Theory |      1 |       1 | den-pc |
| The Big Bang Theory |      1 |       2 | den-pc |
| The Big Bang Theory |      1 |       3 | den-pc |
| The Big Bang Theory |      1 |       4 | den-pc |
| The Big Bang Theory |      1 |       5 | den-pc |
| The Big Bang Theory |      1 |       6 | den-pc |
| The Big Bang Theory |      1 |       7 | den-pc |
| The Big Bang Theory |      1 |       8 | den-pc |
| The Big Bang Theory |      1 |       9 | den-pc |
| The Big Bang Theory |      1 |      10 | den-pc |
| The Big Bang Theory |      1 |      11 | den-pc |
| The Big Bang Theory |      1 |      12 | den-pc |
| The Big Bang Theory |      1 |      13 | den-pc |
```
So one possible solution for me when I do the production backend upgrade is to not bring over the videos until after everything is setup then just copy them over and run `mythutil --scanvideos` at that point.  More or less what I did today on a reduced quantity basis.

**Comment by bennettpeter** [comment]
I tested "mythconverg_restore.pl --change_hostname" and it deos correctly change the hostname of the videos. You  must have been running this before running the change_hostname. So there is no bug here.

**Comment by jfabernathy** [comment]
One last question. Based on what you reported, I would be Okay to copy All of the Storage Group files over to the new backend including the Videos, restoring the database, and renaming the backend to the new Hostname? Correct?
