### ISSUE TITLE
Mythfrontend crashes when displaying programme guide and video exits

### ISSUE THREAD

**Issue by mark-kendall** [MythTV/mythtv#202]
- only applies when setting 'Continue playback when embedded' is enabled
- does not apply to Programme Finder, Upcoming Recordings or Edit Recording Schedule UIs as these do not obey the setting (i.e. they pause playback)
- does not apply to live TV as (in theory at least) playback should not stop
- should be a relatively straightforward fix

**Comment by Jpilk** [comment]
I have been able to provoke frontend crashes by scrolling rapidly upwards shortly after going to the programme guide, perhaps only shortly after starting the frontend.   Mainly seen in el7.  Maybe a failing lock somewhere.  No problems noticed after a frontend restart.

**Comment by mark-kendall** [comment]
> I have been able to provoke frontend crashes by scrolling rapidly upwards shortly after going to the programme guide,

John - this is almost certainly a different issue. Can you open a new issue with all of the relevant details. Thanks.

**Comment by mark-kendall** [comment]
'should be a relatively straightforward fix' - I definitely spoke too soon. This is a real mess.

With the code as written, the player has no knowledge of the guidegrid object that it is embedding in - it is simply told that it needs to embed. If the player stops before the guidegrid exits - all hell breaks lose. The code is so convoluted here, I just don't know where to start.

**Comment by mark-kendall** [comment]
Fixed in master and fixes/31
