### ISSUE TITLE
Regression in V4L2 M2M Prime decoding

### ISSUE THREAD

**Issue by mark-kendall** [MythTV/mythtv#209]
a1e378ad431c74c029fb4aba0bc34194838672e1 updated the V4L2 M2M decoder for the latest patch set.

No issues noted with RPI4 but @warpme reports a regression in decoder performance on s905 based boards.

My only suspect is the use of V4L2_MEMORY_DMABUF instead of V4L2_MEMORY_MMAP

**Comment by mark-kendall** [comment]
Test patch: https://gist.github.com/mark-kendall/bb9923ade6a41d3e7d901b8d8dc8b0e8

**Comment by warpme** [comment]
Mark - unfortunately test patch not helps. issue is still present.

**Comment by warpme** [comment]
Summarise my experience with current master (as of b3d42cff2):

1. with a1e378a I have 
 > a\ issue of randomly skipping frames on s905 when v4l2 m2m decode is used;
 > b\ s912/sm1 playabck hangs.
2. reverting a1e378a fixes a\ and b\
3. applying https://gist.github.com/mark-kendall/bb9923ade6a41d3e7d901b8d8dc8b0e8 fixes b\ but not a\

**Comment by mark-kendall** [comment]
@warpme  I decided the easiest approach was to just to revert to the original implementation. The updated patches offered some theoretical improvements/fixes but I couldn't see any actual improvements and I simply don't have the time to dig into the regressions.

Closing this to focus on the request API.
