### ISSUE TITLE
Android: Regression in video playback in master

### ISSUE THREAD

**Issue by mark-kendall** [MythTV/mythtv#211]
As reported by @bennettpeter 

Non-working version is b14bb16df5
Previous working version is c98d3996a8

I can't see any obvious reason for the issue and the android logs give no clues.

There was a significant video playback refactor around e70fbf7044037a1c1cfe06726915fe2eb2fec19b

but there were also some significant clang-tidy cleanups from @linuxdude42  across the code starting around ccf15e76b0e462f62418d50561948e5c64433fbb

@bennettpeter  can you try and git bisect which commit breaks the build? I would suggest 4328cf92ce7e95c47027201129e9aec528a06a02 as a starting point (pre my video playback refactor and post @linuxdude42 's changes)

**Comment by linuxdude42** [comment]
Version 2e11e33b7a (where the schema changed) is good.

**Comment by linuxdude42** [comment]
Version 663d142a73 is where the problem occurs.

**Comment by bennettpeter** [comment]
It looks like David has done the bisect. Thank you David!

**Comment by linuxdude42** [comment]
You're welcome. I was worried that it might have been one of my cleanups.

**Comment by mark-kendall** [comment]
Right - still no closer to actually understanding the issue.

@bennettpeter  I realised that the difference between the 2 logs you provided previously is that the original (with the MythVidTex errors) was presumably using software (or decode only) decoding - whereas the second was using full mediacodec. Could you for the time being stick to software decoding in testing - as noted below there is some logging that may better pinpoint the issue.

I've been pushing updates/fixes/tweaks for a few days, including some extra logging.

Can someone test latest master (with software decoding) and post some logs if it is still not working (preferably with -v playback logging). Thanks.

**Comment by bennettpeter** [comment]
I built latest master today for shield
mythfrontend-20200919-arm64-v32-Pre-1054-gbd3fe45807.apk
I selected playback profile OpenGL Slim. That uses standard decode and opengl render
Playback does not start, but displays "Failed to Initialize Video Output".
The complete log is in the paste below, with verbose playback set. See time 12:27:55 for start of playback
https://pastebin.com/cM2C3Ld1

**Comment by mark-kendall** [comment]
Peter - strange error. Can you try with the latest update. Thanks.

**Comment by bennettpeter** [comment]
built mythfrontend-20200919-arm64-v32-Pre-1059-ga352d83b77.apk
It is working now on shield. I tried OpenGL Slim and Mediacodec Normal.
I will put the latest build on bintray.com for those who are using master but don't build themselves.
Thanks

**Comment by mark-kendall** [comment]
Fixed in 32259ab49c57a5b. @bennettpeter thanks for testing and confirming.
