### ISSUE TITLE
Correct relevance test for programgenres in progdetails.cpp

### ISSUE THREAD

**Issue by garybuhrmaster** [MythTV/mythtv#212]
Correct relevance test for programgenres in progdetails.cpp

Original trac ticket:   https://code.mythtv.org/trac/ticket/13019

The relevance column is used for sequencing but it is not a number, but a character.  Testing for > 0 results in not returning the entire list of genres when the set is large (which can be generated by (at least) the schedules direct grabbers for some programs).

(pull request will be posted shortly)

**Comment by garybuhrmaster** [comment]
Suggested labels: bug:general component:mythtv:general (maybe component:mythtv:playback?) patch:bug-fix version:master

**Comment by bennettpeter** [comment]
I see values 0-9 and A-D in the relevance column in programgenres.
