### ISSUE TITLE
Wayland: MythTV fails to inhibit idle ie screensaver on sway

### ISSUE THREAD

**Issue by bhepple** [MythTV/mythtv#216]
This is on sway, the popular wayland compositor.

kodi and mpv both emit an idle-inhibit signal when playing and stop the screensaver cutting in. 

* **Platform**:
Linux nina 5.7.9-100.fc31.x86_64 #1 SMP Fri Jul 17 17:18:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

* **MythTV version**:
mythtv-frontend-31.0-9.20200829gitab0c38a476.fc31.x86_64

* **Package version**:

* **Component**:
mythfrontend

### What steps will reproduce the bug?
While running under sway, have a idle timer running like so:

```
swayidle -w timeout 10 swaymsg 'output * dpms off' resume swaymsg 'output * dpms on'
```

Then start a mythtv playback and wait for the screen to blank. 

### What is the expected behaviour?

mythtv should inhibit the idle timer - kodi and mpv do it correctly.

### What do you see instead?

The screen blanks until the mouse is moved or a key is pressed

**Comment by mark-kendall** [comment]
@bhepple  This appears to be working correctly in master (but does need a custom build). Any problems, please open a new ticket. Thanks for reporting.
