### ISSUE TITLE
Android: Enable libfftw support (for visualisations)

### ISSUE THREAD

**Issue by mark-kendall** [MythTV/mythtv#217]
@mspieth added libfftw to the Android build  but it is not currently enabled.

**Comment by mspieth** [comment]
It's built and the headers and libs are present. 
Is it disabled in myth configure by default? 
or maybe configure cant find it.

**Comment by mark-kendall** [comment]
It should be enabled by default if configure finds it. I had a quick play (using @bennettpeter 's latest master build) yesterday and the visualisers that depend on it were not available.

**Comment by mspieth** [comment]
Definitely myth configure. android lib is combined threads and f so dont need all the 3 libs in the probe.
Havent figured it out yet.

**Comment by mspieth** [comment]
When the commit comes through, run ```makelibs.sh``` again or for a faster turnaround ```makelibs fftw``` and then rebuild myth. 
Have not tried plugins yet but should work.

**Comment by mspieth** [comment]
Missed the other part to copy the fftw libs to the target image
https://github.com/MythTV/packaging/commit/711afc3ad689722b3bd897122591a9f865eb0d80
