### ISSUE TITLE
Wayland: Link to Wayland and include Qt private platform headers

### ISSUE THREAD

**Issue by mark-kendall** [MythTV/mythtv#218]
Qt does not directly expose either the wl_compositor or wl_surface objects to clients. We need these if we are going to call Wayland api's for additional functionality.

Proposal:-

- add a 'wayland-extras' option to configure (for the time being at least not enabled by default)
- if enabled require Wayland and check for existence of Qt private headers (QPlatformNativeInterface)
- update libmythui.pro to include Qt private headers

Refs #210 and #216

**Comment by garybuhrmaster** [comment]
Re: default to not enabled.  It is not my call, but I admit that for purposes of certain packaging automation that I prefer that configure default to enabled for useful features with the option to disable on the configure command line and a test in configure that disables the functionality if the required headers are not available with a line in the configure results summary reporting the results.  Similar to how the recent vulkan option/tests were added to configure.  And, at least with the current project CI buildbot configuration, it is likely to get better build coverage as configure does not (currently) use enable overrides (except for symbol-visibility).  I suspect that the annoying part will be determining what the various distros name the package with the private headers to add them to the appropriate ansible stanza(s) and test those.

**Comment by mark-kendall** [comment]
> Re: default to not enabled. It is not my call, but I admit that for purposes of certain packaging automation that I prefer that configure default to enabled for useful features with the option to disable on the configure command line and a test in configure that disables the functionality if the required headers are not available with a line in the configure results summary reporting the results.

The longer term intention is to enable by default. Just being cautious in the short term.

**Comment by mark-kendall** [comment]
This is complete with the exception of handling Qt private header detection in configure - which I can't figure out yet - so leaving the default behavior to not enabled.
