### ISSUE TITLE
FireStick 4K Firmare version 6.2.7.3 UK 1080i

### ISSUE THREAD

**Issue by jksj461** [MythTV/mythtv#236]
Version 6.2.7.3 of Fire OS claims to have fixed the mediacodec issues when playing back UK DVB 1080i recordings see [https://github.com/amzn/exoplayer-amazon-port/issues/94#issuecomment-675488742](url).
Mythfrontend however hangs on attempting playback using mediacodec.
Software playback is unaffected.
Log attached.
[Debug.txt](https://github.com/MythTV/mythtv/files/5288759/Debug.txt)

**Comment by mark-kendall** [comment]
Could you attach the same log without filtering for mfe? android typically is quite verbose about what it thinks is happening

**Comment by jksj461** [comment]
Unfiltered log 
[Debug2.txt](https://github.com/MythTV/mythtv/files/5288802/Debug2.txt)

**Comment by jksj461** [comment]
Sorry closed in error - 'The Close with comment' button is easily misinterpreted

**Comment by bennettpeter** [comment]
Firestick 4K has not been able to play mpeg2 using mediacodec. Hence the recommendation to use software decoding for mpeg2.
https://www.mythtv.org/wiki/Android#Amazon_Fire_TV_Stick_4K
This was due to problems with the ffmpeg interface to mediacodec. This may have changed, I have not looked at it in a while.

**Comment by jksj461** [comment]
This works in current master v32-Pre-2005-g4ce4d36b2b so closing.

**Comment by bennettpeter** [comment]
I confirm it is fixed, but you have to select "Mediacodec" and not "Mediacodec (decode-only)". This should not be a problem as "Mediacodec" is superior.
