### ISSUE TITLE
Use values from database instead of calculating from filename

### ISSUE THREAD

**Issue by Vollstrecker** [MythTV/mythtv#246]
Hi,

I'm on debian with atm version 31.0+fixes20200906.gitb282809197-dmo0~bpo10+1

After trying to clean up everything undone in the past years, I saw that the series with the german Name "Es war einmal... das Leben" didn't show screenshots, just the cover. After checking ttvdb.py does download them, and verifying be renaming that the picture itself is OK, I searched deeper. On a last try I renamed the Folder of the series, it was named "Es war einmal das Leben", so in the folder name three dots where missing. At least in terra theme this wasn't visible, as the dots where removed from the scanned filename anyways. The right data was saved in the db after ttvdb run, so in my Eyes it's just wrong to calculate that from the directory and filenames instead of using the already saved data. Or the saving of the unused data is wrong.

**Comment by bennettpeter** [comment]
Please can you clarify: Are you referring to videos in the Video storage group that you have placed there and that have been scanned by the scan videos command or mythutil --scanvideos? 

There are different processes involved in shows you have recorded vs videos you have placed in the Videos directory and I want to be sure I am looking at the correct thing.

**Comment by Vollstrecker** [comment]
I had the problems in the storagegroups. I don't have any selfrecorded titles.

**Comment by bennettpeter** [comment]
I don't understand what you feel is wrong. I set my language to Deutsch and named a file "Es war einmal... das Leben.mpg" in my videos. I am using tmdb3 for lookup in Artwork und Datenquellen . It gets the poster and description but there is no preview screen, as you mentioned. Looking at the website of www.themoviedb.org, I do not see preview images for any movies, only for TV series. DO you have examples of other movies where you did see a picture? I don't think it is the three dots that is the problem, I think the web site maybe does not have a preview image.

**Comment by Vollstrecker** [comment]
This is a [series](https://www.thetvdb.com/series/once-upon-a-time-life). The problem are not the dots, the problem was that I didn't have them in the folder-name and I wasn't able to see this in the frontend.

Maybe to clarify:
- My folder: No dots.
- Right Series Name: With dots.
- Seriesname in the database: With dots
- Series (or folder) shown in the frontend: No dots.
- Downloaded Screenshots filename: With dots.

Maybe it's expected to show the real foldername, but for choosing the right screenshots to display inside this folder, the seriesnames should be used, as they are used for saving them.

**Comment by Vollstrecker** [comment]
For example:
```
Adding :  : Es War Einmal Das Leben/S1E01 - Ein Kleines Wunderwerk, Oder Die Zelle.avi : 7bdbe13e942056f9
Running Grabber: /usr/share/mythtv/metadata/Movie/tmdb3.py -l de -a DE -M Es War Einmal Das Leben
Running Grabber: /usr/share/mythtv/metadata/Television/ttvdb.py -l de -a DE -D 79158 1 1
Result Found, Season 1 Episode 1
Returning Metadata Results: Es war einmal... Das Leben 1 1
Metadata Image Download: http://thetvdb.com/banners/episodes/79158/316491.jpg -> myth://Screenshots@htpc/Es war einmal... Das Leben Season 1x1_screenshot.jpg
```
Results in just the Cover is shown on this episode.

**Comment by bennettpeter** [comment]
The system will not change the folder name displayed to match the series name. When I tried this, I did get a screen shot for the episode, with any folder name including the one without dots.I tried your folder name and I also tried a folder name of Children. It works with ttvdb and also tmdb3.

```
2021-06-05 16:54:28.426313 I  Adding :  : Es War Einmal Das Leben/S1E01 - Ein Kleines Wunderwerk, Oder Die Zelle.ts : 3bb1158ce8220216
2021-06-05 16:54:28.427025 I  Video Scan Complete: a(1) m(0) d(0)
2021-06-05 16:54:28.508052 I  Monitor sock(555b5a04da20) 'rocinante' disconnected
2021-06-05 16:54:28.605469 I  Running Grabber: /home/peter/proj/build/focal-amd64/mythtv/master/usr/share/mythtv/metadata/Television/ttvdb.py -l en -a US -N Es War Einmal Das Leben Ein Kleines Wunderwerk, Oder Die Zelle
2021-06-05 16:54:28.805691 I  Running Grabber: /home/peter/proj/build/focal-amd64/mythtv/master/usr/share/mythtv/metadata/Television/ttvdb.py -l en -a US -M Es War Einmal Das Leben
2021-06-05 16:54:28.956431 I  Result Found, Season 1 Episode 1
2021-06-05 16:54:29.106631 I  Running Grabber: /home/peter/proj/build/focal-amd64/mythtv/master/usr/share/mythtv/metadata/Movie/tmdb3.py -l en -a US -M Es War Einmal Das Leben
2021-06-05 16:54:30.016448 I  Running Grabber: /home/peter/proj/build/focal-amd64/mythtv/master/usr/share/mythtv/metadata/Television/ttvdb.py -l en -a US -D 79158 1 1
2021-06-05 16:54:30.260149 I  Result Found, Season 1 Episode 1
2021-06-05 16:54:30.260199 I  Returning Metadata Results: Once Upon a Time... Life 1 1
2021-06-05 16:54:30.262549 I  Metadata Image Download: http://thetvdb.com/banners/episodes/79158/316491.jpg -> myth://Screenshots@rocinante/Once Upon a Time... Life Season 1x1_screenshot.jpg
2021-06-05 16:54:49.550219 I  MainServer: MainServer::ANN Playback

```

**Comment by Vollstrecker** [comment]
Yep, download works, but as you can see, the Folder without dots get's screenshots with dots. And (at least here) this results in the screenshots just not showing up in the frontend. Every single episode is shown with the season cover image (which also is saved with dots). In the moment I'm adding the dots to the foldername and rescan, all screenshots show up without being downloaded again, so it seems that the series name is used for naming the downloaded files, and is inserted in the database, but for showing them, the foldername plus season, episode and so on is used.

Funfact: If I use "Es War Einmal Das Leben/Staffel 1/01 - Die...mkv" it works with and without the dots. I just don't want to add an extra season folder if there is only one.

And tmdb is no alternative, I won't say 100%, but at least all series I checked are lacking a german translation.
