### ISSUE TITLE
Current master (as of gf2db1dc) connected to 4k display gives black screen

### ISSUE THREAD

**Issue by warpme** [MythTV/mythtv#268]
I just discovered that current master (as of gf2db1dc) connected to 4k display gives black screen. 
I have tested on s912 and baytrail. 
As GL based screensaver works ok on those platforms - i think issue in in myth code. 
Log from baytrail FE: https://pastebin.com/MLAPRSqY

**Comment by mark-kendall** [comment]
@warpme  can you bisect the issue at all? it seems to get confused between 4k and 1920P output at some point - not sure why that would happen.

**Comment by warpme** [comment]
Mark,
Before bisecting....
I done some tests and: if I set GuiVidModeResolution to 3840x2160 all works ok.
So for me issue is rather related to how GuiVidModeResolution is initialised + how we deal with case when user changes display i.e. from HD to UHD...

**Comment by mark-kendall** [comment]
so to be clear - you are connected to a 4K display, the display is normally running at 4K (i.e. the desktop is 4K) but you have set the GUI resolution to 1920? is that right?

**Comment by warpme** [comment]
scenario was following: fe works ok connected to HD display. Power off, replacing HD display to 4k display for this fe, booting gives 4k desktop but when full screen myth starts - screen becomes black. Turning off FE, change GuiVidModeResolution setting to 3840x2160 for this frontend, booting frontend gives correctly working myth with 4k resolution.

**Comment by warpme** [comment]
Mark,
I tested updated code and i still have original issue. Just fyi: workaround i found is setting GuiVidModeResolution in DB to "0x0" - I can freely switch between HD and 4k displays. Of course log says: `Display: Failed to change mode to 0x0@0.000Hz` but beside this all seems to work OK.

**Comment by mark-kendall** [comment]
@warpme  any chance you can git bisect as mentioned before. I can't reproduce.

**Comment by warpme** [comment]
Mark, before bisecting: my monitor server 4k max @30. in all problematic cases i see myth tries to set 4k@60.
here is out from z8500 box:

```
2020-11-15 20:50:49.257100 I Display: Found screen \'HDMI-1\'
2020-11-15 20:50:49.257128 I Display: Using screen \'HDMI-1\' (Make: Samsung Electric Company Model: U32J59x-)
2020-11-15 20:50:49.257155 I Display: Qt screen pixel ratio: 1.00
2020-11-15 20:50:49.257185 I Display: Geometry: 3840x2160+0+0 Size(Qt): 697mmx392mm
2020-11-15 20:50:49.290400 N Display: Desktop video mode: 3840x2160 30.000Hz
2020-11-15 20:50:49.290412 N Display: Display has custom colourspace
2020-11-15 20:50:50.318867 I Display: Waiting for resolution change
2020-11-15 20:50:50.844747 W Display: Timed out wating for screen change
2020-11-15 20:50:50.852849 I Display: Switched to 1920x1080@60.000Hz
```
xorg on this box says:
```
[ 43.151] (II) modeset(0): Printing probed modes for output HDMI-1
[ 43.151] (II) modeset(0): Modeline "3840x2160"x30.0 297.00 3840 4016 4104 4400 2160 2168 2178 2250 +hsync +vsync (67.5 kHz e)
[ 43.151] (II) modeset(0): Modeline "3840x2160"x25.0 297.00 3840 4896 4984 5280 2160 2168 2178 2250 +hsync +vsync (56.2 kHz e)
[ 43.151] (II) modeset(0): Modeline "3840x2160"x24.0 297.00 3840 5116 5204 5500 2160 2168 2178 2250 +hsync +vsync (54.0 kHz e)
[ 43.151] (II) modeset(0): Modeline "3840x2160"x30.0 296.70 3840 4016 4104 4400 2160 2168 2178 2250 +hsync +vsync (67.4 kHz e)
[ 43.151] (II) modeset(0): Modeline "3840x2160"x24.0 296.70 3840 5116 5204 5500 2160 2168 2178 2250 +hsync +vsync (53.9 kHz e)
[ 43.151] (II) modeset(0): Modeline "2560x1440"x60.0 241.50 2560 2608 2640 2720 1440 1443 1448 1481 +hsync -vsync (88.8 kHz e)
[ 43.151] (II) modeset(0): Modeline "1920x1080"x60.0 148.50 1920 2008 2052 2200 1080 1084 1089 1125 +hsync +vsync (67.5 kHz e)
[ 43.151] (II) modeset(0): Modeline "1920x1080"x50.0 148.50 1920 2448 2492 2640 1080 1084 1089 1125 +hsync +vsync (56.2 kHz e)
[ 43.151] (II) modeset(0): Modeline "1920x1080"x59.9 148.35 1920 2008 2052 2200 1080 1084 1089 1125 +hsync +vsync (67.4 kHz e)
[ 43.151] (II) modeset(0): Modeline "1920x1080"x30.0 74.25 1920 2008 2052 2200 1080 1084 1089 1125 +hsync +vsync (33.8 kHz e)
[ 43.151] (II) modeset(0): Modeline "1920x1080"x24.0 74.25 1920 2558 2602 2750 1080 1084 1089 1125 +hsync +vsync (27.0 kHz e)
[ 43.151] (II) modeset(0): Modeline "1920x1080"x30.0 74.18 1920 2008 2052 2200 1080 1084 1089 1125 +hsync +vsync (33.7 kHz e)
[ 43.151] (II) modeset(0): Modeline "1920x1080"x24.0 74.18 1920 2558 2602 2750 1080 1084 1089 1125 +hsync +vsync (27.0 kHz e)
```

 this i think explains why screen is black on my display

**Comment by mark-kendall** [comment]
@warpme I don't see any reference to trying to set the mode to 4k@60?

**Comment by warpme** [comment]
ah my bad. was looking wrong log. let me reconnect device and look again...

**Comment by mark-kendall** [comment]
@warpme if you are rerunning with latest master, could you attach a new log? Thanks

**Comment by warpme** [comment]
Mark, sure. I'm a bit lost with this issue. Now it looks like mode change issued by myth is not changing mode of display. 
Myth log says 
`I Display: Switched to 1920x1080@60.000Hz `
but monitor OSD says 3840x2160@30.
Also randr says:
```
DP-1 disconnected primary (normal left inverted right x axis y axis)
HDMI-1 connected 3840x2160+0+0 (normal left inverted right x axis y axis) 697mm x 392mm
   3840x2160     30.00*   25.00    24.00    29.97    23.98
   2560x1440     59.95
   1920x1080     60.00    50.00    59.94    30.00    24.00    29.97    23.98
   1680x1050     59.88
   1600x900      60.00
   1280x1024     75.02    60.02 
```
Running vnc also shows screen is 3840x2160. 
GL screen saver works so xorg/GL stack is working on 4k mode
I need to understand what is going on here...
(generally mode changes are working i.e. when i'm starting 24fps movies....)

**Comment by warpme** [comment]
After adding solution for refresh rate changing in eglfs drm planes:
Qt5:
https://github.com/warpme/minimyth2/blob/master/script/qt/qt5/files/qt-everywhere-src-5.15.3-eglfskmsgbmscreen-add-dynamic-refresh-switching.patch
https://github.com/warpme/minimyth2/blob/master/script/qt/qt5/files/qt-everywhere-src-5.15.3-eglfskmsintegration-add-dynamic-refresh-switching.patch
and mythtv:
https://github.com/warpme/minimyth2/blob/master/script/myth-master/mythtv/files/0198-libmythui-mythdrmdevice-add-refresh-change-capability.patch

i'm not able to reproduce issue so closing ticket.
