### ISSUE TITLE
Remove excessive prompting when shutting down

### ISSUE THREAD

**Issue by majurgens** [MythTV/mythtv#270]
Submitting as a new feature since this is not really a bug.

As of about v31 a new prompt appeared in the frontend shutdown sequence asking the user to ok or cancel the process.
This is somewhat excessive and unnecessary. Prompts like this should be reserved to when they may prevent an accident or when the consequence is high. Neither of these conditions are met for the new prompting.

Accident: Due to the combination of keystrokes required to reach this prompt in the first place, it is highly likely that the user intends to shutdown/exit and that they would always select OK anyway.
Consequence: What is the consequence of shutting down the frontend? Not much. It can easily be restarted. There is still one case the prompt should appear and that is when the shutdown of the frontend would also impact the backend.

I have created a pull request to show how I see the code working. I have changed the exit prompt to only appear in a single case - where the backend and frontend are on the same system

https://github.com/MythTV/mythtv/pull/269

**Comment by mark-kendall** [comment]
No need for a pull request and a ticket.
