### ISSUE TITLE
DVB APIv5 log spam from unsupported SNR calls

### ISSUE THREAD

**Issue by stuarta** [MythTV/mythtv#288]
* **Platform**:

Linux

* **MythTV version**:

Master, post e12c9e030e9d33beb9fb5c0cafbbf62663e7dde2

* **Package version**:
n/a 

* **Component**:

dvb apiv5
### What steps will reproduce the bug?

Run backend on card / driver combination that doesn't support SNR calls via the DVB v5 API

### How often does it reproduce? Is there a required condition?

Constantly. Flooding logs

### What is the expected behaviour?

No log spam

### What do you see instead?

Repeating every 5ms

E [20998/22906] SignalMonitor recorders/dvbchannel.cpp:1333 (GetSNR) - DVBChan[1](/dev/dvb/adapter1/frontend0): Getting Frontend signal/noise ratio failed. 
     eno: Unknown error 524 (524)

### Additional information

Looking at the code ripped out in 0d1b1668560ea7e98fa29bc5fa6f506edd12c16c
errno 524 is ENOTSUPP

**Comment by kmdewaal** [comment]
Hi Stuart, it should be fixed now. If it still does not work for you then please create a log with "-v channel" as this will give now lots of info about the tuner.

**Comment by stuarta** [comment]
Fixed, thanks!
