### ISSUE TITLE
Programme guide now lost category colours

### ISSUE THREAD

**Issue by bib1963** [MythTV/mythtv#291]
* **Platform**:

* **MythTV version**:
git head 20201212 

commit 85e2689da6d72bd85758a471cf94709d92933e45 (patch)
tree 76b923f938c065fb830835ea639b0488bf7a85f1
parent aca7df4b97284bcebfe478c9cd1bf28ac2da9b8d (diff)

* **Package version**:

* **Component**:

### Additional information

If you view the programme guide, all the category colours are now missing. They were there with git head from 20201128.

I assume this is problem with the diff MythRenderOpenGL: Greatly simplify drawing rounded rects.

**Comment by Jpilk** [comment]
See also http://lists.mythtv.org/pipermail/mythtv-users/2020-December/405811.html

**Comment by Jpilk** [comment]
Yes, that fixed the headline, issue and the cutlist cursor is back.  Great.  It looks a bit untidy at each end of the range, though;  has it ever been/would it be easy to make it masked ?
