### ISSUE TITLE
Previously recorded screen spins on loading

### ISSUE THREAD

**Issue by bib1963** [MythTV/mythtv#296]
Linux ns2 5.3.18-lp152.57-default #1 SMP Fri Dec 4 07:27:58 UTC 2020 (7be5551) x86_64 x86_64 x86_64 GNU/Linux

* **Platform**:

* **MythTV version**:
master head 20201231
* **Package version**:

* **Component**:
mythfrontend
### What steps will reproduce the bug?

In the frontend, go to the previously recorded screen.
It just spins on "Loading...".
Only way to kill it is to issue a kill command.

**Comment by stuarta** [comment]
Cannot reproduce this issue with current master. If the issue still persists you will need to gather more information
