### ISSUE TITLE
Decode error or zooming the playback of left upper corner of video 

### ISSUE THREAD

**Issue by jarnos** [MythTV/mythtv#300]
* **Platform**:

Xubuntu 20.04.1 LTS, Linux 5.4.0-59-generic (64bit)

* **MythTV version**:

MythTV Version : v31.0+fixes.202101061415.e8d34eacf7~ubuntu20.04.1
MythTV Branch : fixes/31
Network Protocol : 91
Library API : 31.20200101-1
QT Version : 5.12.8
Options compiled in:
 linux profile use_hidesyms using_alsa using_oss using_pulse using_pulseoutput using_backend using_bindings_perl using_bindings_python using_bindings_php using_dvb using_firewire using_frontend using_hdhomerun using_vbox using_ceton using_hdpvr using_ivtv using_joystick_menu using_libcec using_libcrypto using_gnutls using_libdns_sd using_libfftw3 using_libxml2 using_lirc using_mheg using_opengl using_egl using_qtwebkit using_qtscript using_qtdbus using_taglib using_v4l2 using_x11 using_libbluray_external using_xrandr using_profiletype using_systemd_notify using_systemd_journal using_bindings_perl using_bindings_python using_bindings_php using_freetype2 using_mythtranscode using_opengl using_egl using_vaapi using_nvdec using_vdpau using_ffmpeg_threads using_mheg using_libass using_libxml2 using_libmp3lame

* **Package version**:

2:31.0+fixes.202101061415.e8d34eacf7~ubuntu20.04.1

* **Component**:

mythfrontend

### What steps will reproduce the bug?

Start playback of a recording from certain YLE HD channel. Sometimes it can not play anything and just tells me to wait. Sometimes it shows only left upper part of the video zoomed, and sometimes it gives decode error.

### How often does it reproduce? Is there a required condition?

Sometimes and only with HD recordings

### What is the expected behaviour?

Play video properly

### What do you see instead?

Zoomed video or no playback at all.

### Additional information

I have reported this in the old bug tracker before:
https://code.mythtv.org/trac/ticket/13557#comment:22

**Comment by jarnos** [comment]
I played live TV today by mythfronted (containing package) version 2:31.0+fixes.202102041836.7763a3363d~ubuntu20.04.1
and it played fine for a while but maybe after program switch (still playing the same YLE HD channel) it zoomed the image and freezed so I had to terminate the application by signal. Kodi starts faster and plays the channel without such an issue, but mythfrontend can play video smoother with some VAAPI playback settings.

**Comment by kmdewaal** [comment]
This topic is continued in issue #351.

**Comment by kmdewaal** [comment]
Problem is fixed in #351.
