### ISSUE TITLE
Location of wayland-client.h not always under /usr/include

### ISSUE THREAD

**Issue by bib1963** [MythTV/mythtv#305]
* **Platform**:
opensuse 15.2

* **MythTV version**:
* master head 20210123

* **Package version**:

* **Component**:

### What steps will reproduce the bug?

Normal build fails as wayland-client.h is under /usr/include/wayland, rather than just /usr/include

g++ -c -pipe -D_FILE_OFFSET_BITS=64 -DPIC -std=c++17 -faligned-new -fomit-frame-pointer -fPIC -DQT_DISABLE_DEPRECATED_BEFORE=0x050900 -msse -pthread -g -Wall -Wextra -Wpointer-arith -fvisibility-inlines-hidden -Wdouble-promotion -Wduplicated-cond -Wlogical-op -Wmissing-declarations -Wnull-dereference -Woverloaded-virtual -Wshadow -funit-at-a-time -Wzero-as-null-pointer-constant -Wsuggest-override -I/usr/include/libdrm -fvisibility=hidden -std=gnu++1z -D_REENTRANT -fPIC -DMMX -D_GNU_SOURCE -DUSING_X11 -DUSING_DRM -DUSING_QTPRIVATEHEADERS -DUSING_WAYLANDEXTRAS -DUSING_DBUS -DUSING_OPENGL -DUSING_EGL -DUSING_QTWEBKIT -DMUI_API -DQT_NO_DEBUG -DQT_WEBKITWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_SQL_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt5 -isystem /usr/include/libxml2 -isystem /usr/include/X11 -Iopengl -Iplatforms -Iplatforms/drm -Idevices -Ivulkan -I../libmythbase -I../.. -I.. -isystem /usr/include/qt5/QtWebKitWidgets -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtWebKit -isystem /usr/include/qt5/QtGui/5.12.7 -isystem /usr/include/qt5/QtGui/5.12.7/QtGui -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtXml -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore/5.12.7 -isystem /usr/include/qt5/QtCore/5.12.7/QtCore -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtCore -Imoc -I/usr/lib64/qt5/mkspecs/linux-g++ -o obj/mythscreensaverwayland.o platforms/mythscreensaverwayland.cpp
In file included from platforms/mythscreensaverwayland.cpp:5:0:
./platforms/waylandprotocols/idle_inhibit_unstable_v1.h:8:10: fatal error: wayland-client.h: No such file or directory
 #include "wayland-client.h"

**Comment by stuarta** [comment]
Can you share the output from `pkg-config --cflags wayland-client` and `pkg-config --libs wayland-client`

**Comment by bib1963** [comment]
On Tuesday, 2 February 2021 09:14:46 GMT Stuart Auchterlonie wrote:
> Can you share the output from `pkg-config --cflags wayland-client` and `pkg-config --libs wayland-client`
> 
> 

Here you go!

user@ns2 ~$ pkg-config --cflags wayland-client
-I/usr/include/wayland
user@ns2 ~$ pkg-config --libs wayland-client
-lwayland-client




B

**Comment by stuarta** [comment]
This issue has been resolved
