### ISSUE TITLE
Segfault on exit of mythtv-setup

### ISSUE THREAD

**Issue by kmdewaal** [MythTV/mythtv#312]
* **Platform**:
Linux PC with Ubuntu:
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.4.0-1ubuntu1~18.04.1' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1) 

* **MythTV version**:
2021-02-03 15:30:58.895 C  mythtv-setup version: master [v32-Pre-2208-gbce11f8532] www.mythtv.org

* **Package version**:
Master built from source.

* **Component**:
mythtv-setup

### What steps will reproduce the bug?
Start mythtv-setup.
Exit by pressing escape.
Look at the log.
This then shows the following at exit:
2021-02-03 15:31:01.780 I  Current MythTV Schema Version (DBSchemaVer): 1367
2021-02-03 15:31:05.697 C  'UDP': MThread epilog was never run! (UDP)
2021-02-03 15:31:05.697 C  'UDP': MThread destructor called while thread still running! (UDP)
2021-02-03 15:31:05.705 I  InputHandler: Stopping
2021-02-03 15:31:05.705 W  MythPainter: 132 images not yet de-allocated.
2021-02-03 15:31:06.041 I  Display: Deleting
2021-02-03 15:31:06.049 I  PowerDBus: Closing interfaces
2021-02-03 15:31:06.051 C  'SSDP': MThread epilog was never run! (SSDP)
2021-02-03 15:31:06.051 C  'SSDP': MThread destructor called while thread still running! (SSDP)
Handling Segmentation fault
Segmentation fault (core dumped)

### How often does it reproduce? Is there a required condition?
100% reproducible.

### What is the expected behaviour?
No segfault.

### Additional information
This issue has been discussed in the users mailing list.

Have done a "git bisect" and the problem is caused by the following commit:

 Commit: a9d53f3230a12d03182ee7df5e85cbcefc40abea
      https://github.com/MythTV/mythtv/commit/a9d53f3230a12d03182ee7df5e85cbcefc40abea
  Author: David Hampton <mythtv@love2code.net>
  Date:   2021-01-25 (Mon, 25 Jan 2021)

  Changed paths:
    M mythplugins/mythmusic/mythmusic/playlistcontainer.cpp
    M mythtv/libs/libmyth/audio/audiooutputalsa.cpp
    M mythtv/libs/libmyth/audio/audiooutputbase.cpp
    M mythtv/libs/libmyth/audio/audiooutputca.cpp
    M mythtv/libs/libmyth/audio/audiooutputoss.cpp
    M mythtv/libs/libmyth/audio/volumebase.cpp
    M mythtv/libs/libmythbase/mthread.cpp
    M mythtv/libs/libmythbase/mthread.h
    M mythtv/libs/libmythbase/mthreadpool.cpp
    M mythtv/libs/libmythbase/mthreadpool.h
    M mythtv/libs/libmythbase/mythdate.cpp
    M mythtv/libs/libmythbase/mythdate.h
    M mythtv/libs/libmythbase/mythdownloadmanager.cpp
    M mythtv/libs/libmythbase/mythsystemunix.cpp
    M mythtv/libs/libmythmetadata/imagescanner.cpp
    M mythtv/libs/libmythprotoserver/mythsocketmanager.cpp
    M mythtv/libs/libmythprotoserver/requesthandler/deletethread.cpp
    M mythtv/libs/libmythtv/HLS/httplivestreambuffer.cpp
    M mythtv/libs/libmythtv/cardutil.cpp
    M mythtv/libs/libmythtv/cardutil.h
    M mythtv/libs/libmythtv/channelscan/channelscan_sm.cpp
    M mythtv/libs/libmythtv/channelscan/externrecscanner.cpp
    M mythtv/libs/libmythtv/channelscan/iptvchannelfetcher.cpp
    M mythtv/libs/libmythtv/channelscan/vboxchannelfetcher.cpp
    M mythtv/libs/libmythtv/io/mythfilebuffer.cpp
    M mythtv/libs/libmythtv/io/mythmediabuffer.cpp
    M mythtv/libs/libmythtv/mythplayer.cpp
    M mythtv/libs/libmythtv/previewgenerator.cpp
    M mythtv/libs/libmythtv/recorders/DeviceReadBuffer.cpp
    M mythtv/libs/libmythtv/recorders/cetonstreamhandler.cpp
    M mythtv/libs/libmythtv/recorders/dvbchannel.h
    M mythtv/libs/libmythtv/recorders/dvbsignalmonitor.cpp
    M mythtv/libs/libmythtv/recorders/signalmonitor.cpp
    M mythtv/libs/libmythtv/recorders/signalmonitor.h
    M mythtv/libs/libmythtv/recorders/v4lrecorder.h
    M mythtv/libs/libmythtv/tv_rec.cpp
    M mythtv/libs/libmythtv/tv_rec.h
    M mythtv/libs/libmythui/mythmainwindowprivate.h
    M mythtv/libs/libmythui/mythuianimation.cpp
    M mythtv/libs/libmythui/mythuianimation.h
    M mythtv/libs/libmythupnp/taskqueue.cpp
    M mythtv/programs/mythbackend/mainserver.cpp
    M mythtv/programs/mythbackend/scheduler.cpp
    M mythtv/programs/mythfrontend/galleryslide.cpp
    M mythtv/programs/mythfrontend/galleryslide.h
    M mythtv/programs/mythfrontend/galleryslideview.cpp
    M mythtv/programs/mythfrontend/galleryslideview.h
    M mythtv/programs/mythfrontend/gallerytransitions.cpp
    M mythtv/programs/mythfrontend/gallerytransitions.h

  Log Message:
  -----------
  Convert myth threads to std::chrono. (2)

This commit focuses on converting MThread, and propagating those
changes throughout the rest of the code without changing too many
other interfaces. There are some temporary conversions to/from
int/std::chrono::millisecond that should be removed with later
commits.

My guess is that the C++ programming constructs that have been introduced by this commit, and possible also by other code-improvement commits,  give different results for different compiler versions.

**Comment by linuxdude42** [comment]
I still haven't found a way to trigger the crash on my test system. Can you try this patch and see if it solves the problem for you?

```
diff --git a/mythtv/libs/libmythbase/mthread.cpp b/mythtv/libs/libmythbase/mthread.cpp
index dedfb2bf4f..1e81391783 100644
--- a/mythtv/libs/libmythbase/mthread.cpp
+++ b/mythtv/libs/libmythbase/mthread.cpp
@@ -305,7 +305,15 @@ void MThread::quit(void)
 bool MThread::wait(std::chrono::milliseconds time)
 {
     if (m_thread->isRunning())
-        return m_thread->wait(time.count());
+    {
+        if (time == std::chrono::milliseconds::max())
+            return m_thread->wait(ULONG_MAX); // Magic number in recent Qt5.
+        if (time >= 0ms)
+            return m_thread->wait(time.count());
+        LOG(VB_GENERAL, LOG_CRIT,
+            QString("'%1': MThread::wait called for %1 ms!").arg(time.count()));
+        return m_thread->wait(1);
+    }
     return true;
 }
 ```

**Comment by kmdewaal** [comment]
Yes this does fix the problem.
Additional debug shows that the MThread::wait is only called with the LONG_MAX aka std::chrono::milliseconds::max() not with any other value.
