### ISSUE TITLE
Logging timestamps changed to milliseconds

### ISSUE THREAD

**Issue by kmdewaal** [MythTV/mythtv#316]
* **Platform**: Fedora 33

* **MythTV version**: master

* **Package version**: build from source

* **Component**: mythbackend / logging

### What steps will reproduce the bug?

Logging timestamps have been changed from microseconds to milliseconds in commit cdebc71831771ba61d14eeaf7b11c9de4d6a542b.

I do prefer microseconds because it gives me more information about the time interval between the events. This is especially useful when dealing with realtime events such as packet processing etc.
Timestamps in microseconds do also uniquely identify events because there are never two events in one microsecond but there can be several in one milliseconds.
There is no motivation given for this change.
Note that the Linux command "dmesg" also gives timestamps in microseconds.
For me this is a regression; the logging timestamps should be changed back to microsecond resolution.

**Comment by stuarta** [comment]
Microseconds restored in commit 1ae034bd8ab9ffd8c64eea03a4501e897a246b93
