### ISSUE TITLE
Commit 422c4ce109b breaks shape fills

### ISSUE THREAD

**Issue by jpoet** [MythTV/mythtv#319]
@mark-kendall 

* **Platform**: Linux 5.10.15-100.fc32.x86_64 #1 SMP Wed Feb 10 17:52:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

* **MythTV version**: v32-Pre-2365-gb6e2003f64

* **Package version**:

* **Component**: OpenGL

### How often does it reproduce? Is there a required condition?
Run mythfrontend with the Steppes theme. Go to Manage Recordings -> Schedule Recordings -> Manual Schedule. At the bottom the 'name' of the page will be shown "Manual Recording Schedule" and that will be 'connected' to the date and time. The connection to the date and time should NOT be solid black but should be transparent.
In addition, the form on that page will be asking for "Title (Optional): " and there will be an input box. That input box should NOT be filled with the same color as the line color of the box. 

### What is the expected behaviour?

The specified fill color should be used instead of the line color

### What do you see instead?

The line color is used for the fill color.

### Additional information

What is should look like:
![OpenGL-good](https://user-images.githubusercontent.com/508768/108799904-d7010800-754e-11eb-83c4-4214512aff2c.png)
What is looks like with commit 422c4ce109b:
![OpenGL-Commit-422c4ce109b](https://user-images.githubusercontent.com/508768/108799917-df594300-754e-11eb-9515-7bccde75c643.png)

**Comment by mark-kendall** [comment]
@jpoet This looks to be fixed. If you are happy there are no other issues or new regressions, please close.

**Comment by jpoet** [comment]
Yes, it looks good now. Thank your for the quick response @mark-kendall
