### ISSUE TITLE
tvmaze bugs

### ISSUE THREAD

**Issue by bennettpeter** [MythTV/mythtv#320]
Here are some minor issues reported by users for the new tvmaze scripts:

in tvmaze/utils.py

/usr/lib/python3/dist-packages/MythTV/tvmaze/utils.py:45: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if html is not None and html is not "":

in tvmaze.py

bug line 504:
    
```
        if not os.path.exists(cachedir):
-            os.makedirs(cachepath)
+            os.makedirs(cachedir)
        if sys.version_info[0] == 2:

```

**Comment by rcrdnalor** [comment]
Closed by commit 116a715
