### ISSUE TITLE
ProgramInfo string map can lose data

### ISSUE THREAD

**Issue by linuxdude42** [MythTV/mythtv#337]
The contents of a programinfo object can be retrieved as a map of string values. This appears to be used a number of places throughout the code, by the themes, and probably by all the bindings.

The problem is that nine numeric values are not returned as strings, but as a single utf16 character. This limits the maximum possible numeric value to 65536, or 16 bits if it is a bitfield. These fields are:

* commfree
* recordedid
* chanid
* recpriority
* recpriority2
* programflags
* audioproperties
* videoproperties
* subtitleType

There are more than 16 program flags defined in the source, and on my development system the chanid numbers exceed 65536. Given space is now allocated for 10,000 channels per tuner and tuner numbers aren't reused (unless all tuners are deleted) its likely that users may be seeing this too.

In order not to break existing users, I plan to add nine more fields to the map that end in "...str" and have a textual representation of the number, in addition to the existing values containing a single utf16 character. For example, a program with the  FL_IGNOREPROGSTART and FL_COMMFLAG flags set will have a "programflags" value of QChar(0x1) since it can't represent the higher value bit, but it will also have a correct "programflagsstr" value of "65537" to represent both bits.

**Comment by jpoet** [comment]
On Mon, Mar 15, 2021 at 9:29 AM David Hampton ***@***.***>
wrote:

> The contents of a programinfo object can be retrieved as a map of string
> values. This appears to be used a number of places throughout the code, by
> the themes, and probably by all the bindings.
>
> The problem is that nine numeric values are not returned as strings, but
> as a single utf16 character. This limits the maximum possible numeric value
> to 65536, or 16 bits if it is a bitfield. These fields are:
>
>    - commfree
>    - recordedid
>    - chanid
>    - recpriority
>    - recpriority2
>    - programflags
>    - audioproperties
>    - videoproperties
>    - subtitleType
>
> There are more than 16 program flags defined in the source, and on my
> development system the chanid numbers exceed 65536. Given space is now
> allocated for 10,000 channels per tuner and tuner numbers aren't reused
> (unless all tuners are deleted) its likely that users may be seeing this
> too.
>
> In order not to break existing users, I plan to add nine more fields to
> the map that end in "...str" and have a textual representation of the
> number, in addition to the existing values containing a single utf16
> character. For example, a program with the FL_IGNOREPROGSTART and
> FL_COMMFLAG flags set will have a "programflags" value of QChar(0x1) since
> it can't represent the higher value bit, but it will also have a correct
> "programflagsstr" value of "65537" to represent both bits.
>
Thank you David for looking at this. I just started working on some
ServicesAPI code which uses this data. My first thought was that the
properties data was not particularly useful to an external program. How is
it supposed to know what bits mean what? I like your idea of adding a
string, but think it might be better for it to have something like
"FL_IGNOREPROGSTART|FL_COMMFLAG" in it instead of a numeric code?  Maybe
not that verbose, but you get the idea.

Thoughts?

John

**Comment by linuxdude42** [comment]
I can do that, or I can add both. I don't have a preference. I'm only chasing down this rabbit hole because qt6 and gcc11 threw a bunch of complaints about ambiguous conversions from int to QChar.

I think just leave the common prefix off the names: IGNOREPROGSTART|COMMFLAG

**Comment by jpoet** [comment]
That works for me. Thank you.

**Comment by bennettpeter** [comment]
Is this used by the service api? The service api has worked fine for me - all of these items are returned as integers, for example
`<ChanId>10001</ChanId>`
`<RecordedId>13</RecordedId>`
`<ProgramFlags>4624</ProgramFlags>`
I agree that having the programflags like this requires knowing internal details, but it has worked for me. I believe the only value I am checking in programflags is 0x00000200 for "watched".
Will anything change in the service API as a result of your work here?

**Comment by linuxdude42** [comment]
There shouldn't be any effect on the services api. It extracts its data directly from the ProgramInfo object, not via an InfoMap object that was populated by calling ProgramInfo::ToMap.
