### ISSUE TITLE
Automatically split a program into pieces.

### ISSUE THREAD

**Issue by mathog** [MythTV/mythtv#340]
**Is your feature request related to a problem? Please describe.**
My wife insists on recording shows in pieces.  That way she can "throw out a piece at a time".   In order to do this she stops whatever we are watching, starts watching another show, waits for a commercial, stops and then restarts the recording.  

Is there any sane reason to do this?  Not as far as I can tell, but I simply cannot convince her to record the whole hour (or whatever) and live with that.

**Describe the solution you'd like**

Add an option to the recording rules with two parameters: N = the number of fragments and O = overlap in seconds.
So if N = 2 and O = 5 and the show runs from 18:00 to 19:00 - delta, the first recording would run from 18:00-18:30 and
the second from 18:29:55-19:00 - delta.  To achieve the overlap MythTV would briefly "tee" the stream, so that for O seconds it was writing to two files, and then at the end of the overlap period it would drop the original stream and carry on with the new one. It would be acceptable to set an upper limit on O determined by the available hardware.

It would be nice if the show times reflected the actual fragments.  When she uses her method the times shown are for the entire show.  (MythTV 30+fixes on Ubuntu 18.04 LTS)

The default would be N=1 and O=0, as it is now.

That way she could have her show fragments and I could watch a movie without these interruptions.

**Describe alternatives you've considered**
Psychiatry?

**Comment by gigem** [comment]
This is not going to happen.  If you really want it, add your own, custom job to split the recording into pieces after completion.

**Comment by billmeek** [comment]
@mathog, why not use bookmarks? Set the bookmark, switch programs
and when returning to another show, it will start exactly where the bookmark
was set. Rinse and repeat.

A bit harder, but use the editor. Cut to beginning after watching n minutes.
For additional passes on the same program, move the cut point to the end
of the previous one. [Harder 'cause there are more key presses.]

**Comment by mathog** [comment]
How exactly would one add such a "custom job",  particularly so that it would show up as a recording option?

Presumably when the job ends there is some mechanism to call a bash script with the path to the .ts file and possibly some
other information, like the start and stop times for the program.  Where is that documented?  How would one add the option of running this job as a recording option?

That script would need to do:


1.  Make the N fragments.  The endpoints need not be exactly on Full_Time/N boundaries.  This could be done with dd for instance, and it would be OK in this case if all fragments used whatever existing png there is.  In future it might generate a new one for each fragment.

2.  Removes the original recording.   That could be done with /bin/rm, but most likely that would leave the original database entry, now pointing to nothing.

3.  Makes all of these fragments visible so that they show up like any other prerecorded programs.  That is, they would need to be entered into the database as if they were normal recordings.

I know how to do the chop/rename operations in bash.  No idea what sort of SQL would be needed to change the database view though.

**Comment by gigem** [comment]
See https://www.mythtv.org/wiki/User_Jobs regarding how to create your own jobs.  You won't be able to make the parts be their own TV recordings as I'm pretty sure there's no programmatic way to do that.  You'll likely have to export them as videos and watch them that way.
