### ISSUE TITLE
Pause playback of LiveTV, hit play again 20 minutes later: the right-arrow key now skips all the way ahead to the present instead of normal 30 seconds

### ISSUE THREAD

**Issue by alexlance** [MythTV/mythtv#352]
* **Platform**:
Debian Buster: Linux mint 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

* **MythTV version**:
30 (but also experienced same thing on 28)

* **Package version**:
mythtv/stable,stable,now 30.0+fixes20210328.git7d297b1fb8-dmo0+deb10u1 

* **Component**:
livetv

### What steps will reproduce the bug?

1. Watch some livetv
2. Hit pause using the spacebar and let the play buffer grow...
3. Some time later (eg 10 minutes / half an hour) hit spacebar again to resume watching.
4. Hit the right-arrow to skip forward 30 seconds...
    - If you hit right-arrow immediately after hitting unpause, then you are skipped to the present of the tv (often to the end of the movie or sports thing :grimacing:)
    - if you very slowly/carefully tap the right-arrow a couple of times, then you can gradually work your way forward by 30 second increments... but:
    - if you tap too quickly, blammo you lose, and it skips to the present again 

### How often does it reproduce? Is there a required condition?

Everytime I pause it for a little while.

### What is the expected behaviour?

Just that I can skip through at 30 seconds intervals like normal, without getting rushed back into the present livetv viewing.

### What do you see instead?

I'm almost wondering if I have an old setting in my database that I've accidentally carried through with me. Just ask if you want a database dump of a table or something. If it's worth anything I've got 8gb ram / 25gb swap / 2gb video card, it does sort of feel like I'm hitting a ram boundary maybe.

There are a couple of Trac tickets that I found that got auto-closed without a resolution: 
https://code.mythtv.org/trac/ticket/12681
https://code.mythtv.org/trac/ticket/12755

**Comment by kmdewaal** [comment]
Reproducible in today's master. No need to wait for 20 minutes, just pause for one minute and then unpause/right arrow jumps to live instead of skipping 30 seconds. This problem only occurs with live TV; when playing a recording, including playing a recording in-progress, skip forward is correct.

**Comment by kmdewaal** [comment]
Fixed in master and in v31.
