### ISSUE TITLE
Complex Karaoke-style Subttiles fail.

### ISSUE THREAD

**Issue by kt--** [MythTV/mythtv#355]
* **Platform**: Ubuntu 20.04 + all updates  /  Linux redacted 5.8.0-50-generic #56-Ubuntu SMP Mon Apr 12 17:18:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

* **MythTV version**: branch fixes/31
* **Package version**: git clone

* **Component**: front-end subtitles

### What steps will reproduce the bug?

Find a video that has Sub Station Alpha (SSA / ASS) subtitles.  To cause the issue, you need _complex_ subtitles with at least "bouncing ball", or "flying stars" style animation to them.  Play the video with the subtitles turned on.  Note that "coloured progress bar" karaoke subtitles render OK.

### How often does it reproduce? Is there a required condition?
At a guess, when there is sufficient items on the screen, > 40.  It will always effect the same subtitles every time.

### What is the expected behaviour?
Subtitles render correctly with the SSA karaoke effects.  At least compared to VLC.
Instead you get the error message (in the log):

> SubtitleReader: >40 AVSubtitles queued - clearing.

### What do you see instead?
The subtitles will not render correctly, depending on the situation you get some of them.  One of the most common bad behaviours is that you get maybe the first few words on-screen, a big space-gap, then some end words.  Usually also some textual "subtitle noise" as some bit render, and others are denied.

### Additional information
I have already found and patched the issue, just going through the formal process to get the changes in.

**Comment by kmdewaal** [comment]
Please add the patch to this ticket; a "git diff" against the latest fixes/31 is OK.
Please also make a recording available that, when played back, shows the problem.

**Comment by kt--** [comment]
### git diff origin/fixes/31 origin/fix_ssa_subs_karaoke_broken

```
diff --git a/mythtv/libs/libmythtv/subtitlereader.cpp b/mythtv/libs/libmythtv/subtitlereader.cpp
index a8ff9382b4..33b1285c0f 100644
--- a/mythtv/libs/libmythtv/subtitlereader.cpp
+++ b/mythtv/libs/libmythtv/subtitlereader.cpp
@@ -1,6 +1,10 @@
 #include "mythlogging.h"
 #include "subtitlereader.h"
 
+// If the count of subtitle buffers is greater than this, force a clear
+static const int MAX_BUFFERS_BEFORE_CLEAR = 175;  // 125 too low for karaoke
+
+
 SubtitleReader::~SubtitleReader()
 {
     ClearAVSubtitles();
@@ -54,10 +58,12 @@ bool SubtitleReader::AddAVSubtitle(AVSubtitle &subtitle,
     m_avSubtitles.m_buffers.push_back(subtitle);
     // in case forced subtitles aren't displayed, avoid leaking by
     // manually clearing the subtitles
-    if (m_avSubtitles.m_buffers.size() > 40)
+    if ( m_avSubtitles.m_buffers.size() > MAX_BUFFERS_BEFORE_CLEAR )
     {
-        LOG(VB_GENERAL, LOG_ERR,
-            "SubtitleReader: >40 AVSubtitles queued - clearing.");
+        LOG( VB_GENERAL, LOG_ERR, 
+             QString( "SubtitleReader: >%1 AVSubtitles queued - clearing." )
+                 .arg( MAX_BUFFERS_BEFORE_CLEAR )
+           );
         clearsubs = true;
     }
     m_avSubtitles.m_lock.unlock();

```
