### ISSUE TITLE
Unneccessary channels scanned for US broadcast

### ISSUE THREAD

**Issue by ulmus-scott** [MythTV/mythtv#365]
Following the spectrum repack in the US, which completed July 13, 2020 (exceptions ceased broadcasting on the higher channels before October 7), ATSC channels 37 and above are no longer used for TV broadcasts.  MythTV currently scans up to channel 51.

* **Platform**:
Xubuntu 21.04
Linux htpc-HP 5.11.0-18-generic #19-Ubuntu SMP Fri May 7 14:22:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* **MythTV version**:
MythTV Version : v31.0+fixes.202105291450.df29c72b4d~ubuntu21.04.1
MythTV Branch : fixes/31
* **Package version**:
mythbuntu ppa
* **Component**:
mythbackend(-setup?)

### What steps will reproduce the bug?
In mythbackend-setup:
With General -> Locale Settings -> Channel frequency table -> us-bcast
A video source (antenna) using the default frequency table

In Input connections -> (an ATSC tuner) with antenna -> scan for channels -> full scan -> Scan

### How often does it reproduce? Is there a required condition?
Always
### What is the expected behaviour?
Channel scan ends at channel 36.
### What do you see instead?
Scan continues until channel 51.

**Comment by stuarta** [comment]
@kmdewaal the test case needs updating too, as all the builds failed because of this change

**Comment by kmdewaal** [comment]
I will revert the last commit as I am not familiar with test cases.

**Comment by ulmus-scott** [comment]
Tested on MythTV Version : v32.0~master.202107051824.4d21b95e4f~ubuntu20.04.1 via the mythbuntu ppa: the behavior is as expected.
