### ISSUE TITLE
datetime.duck() conversion breaks timezone

### ISSUE THREAD

**Issue by pmhahn** [MythTV/mythtv#384]
* **Platform**: Debian 11 "Bullseye" amd64

* **MythTV version**: 31.0+fixes.20210506.b2ed400037

* **Package version**: self compiled from git b2ed400037

* **Component**: bindings/python

### What steps will reproduce the bug?

After upgrading from Debian-10 "Buster" (Python 3.7) to Debian-11 "Bullseye" (Python 3.9) [transcode-h264.py](https://www.mythtv.org/wiki/Transcode_Mpeg2_to_H264) fails with

> File "./transcode-h264.py", line 172, in runjob
>   rec = Recorded((chanid, utcstarttime), db=db);
> File "/usr/lib/python3.9/dist-packages/MythTV/dataheap.py", line 342, in __init__
>   DBDataWrite.__init__(self, data, db)
> File "/usr/lib/python3.9/dist-packages/MythTV/database.py", line 318, in __init__
>   DBData.__init__(self, data, db)
> File "/usr/lib/python3.9/dist-packages/MythTV/database.py", line 180, in __init__
>   self._pull()
> File "/usr/lib/python3.9/dist-packages/MythTV/database.py", line 388, in _pull
>   DBData._pull(self)
> File "/usr/lib/python3.9/dist-packages/MythTV/database.py", line 204, in _pull
>   raise MythError('DBData() could not read from database')
> MythTV.exceptions.MythError: DBData() could not read from database

This is caused by the following code
```python
    db = MythDB()
    if jobid:
        job = Job(jobid, db=db)
        chanid = job.chanid
        starttime = job.starttime
    rec = Recorded((chanid, starttime), db=db)
```

`job.starttime` is of type `datetime.datetime` and represents the start time in **UTC**, e.g. `pydatetime(2021, 8, 22, 7, 28)`.

This gets converted by `MythTV.utils.dt.datetime.duck()` into a time-stamp with the time-zone replaced by **CEST** (*central european summer time*, currently UTC+2):
> datetime(2021, 8, 22, 7, 28, tzinfo=<MythTV.utility.dt.posixtzinfo object at 0x7fb99748f820>)

When converted back into a string this normalites the time back to **UTC**, which subtracts 2 hours. The searche then is performed with the wrong time and does not find the entry in the `recorded` table:
> '2021-08-22 07:28:00+02:00'

### How often does it reproduce? Is there a required condition?
Every time.

### What is the expected behaviour?
Data returned from the database should be usable as input without any further required steps.

### What do you see instead?
As the timestamp no longer matches, no recording is found and the above shown traceback is printed, which is also misleading; instead it should print something like
> no record found

### Additional information
```python
from datetime import datetime as pydatetime
from MythTV.utility.dt import datetime
starttime = pydatetime(2021, 8, 22, 7, 28)
str(starttime)
# '2021-08-22 07:28:00'
st = datetime.duck(starttime)
str(st)
# '2021-08-22 07:28:00+02:00'
str(dt.astimezone(datetime.timezone.utc))
# '2021-08-22 05:28:00+00:00'
```

```sh
zdump CET UTC
# CET  Mon Aug 23 17:30:42 2021 CEST
# UTC  Mon Aug 23 15:30:42 2021 UTC
```

For now I have fixed that by converting the `datetime` returned from `job.starttime` to a time stamp with timezone `UTC` to prevent `MythTV.utility.dt.datetime.duck()` from using my local time zone:
```python
starttime = job.starttime.replace(tzinfo=datetime.UTCTZ())
```

* https://code.mythtv.org/trac/ticket/13299
* https://code.mythtv.org/trac/ticket/13622 24db137ee6435ae0f1ecc51c580ef1b3d5936402

**Comment by rcrdnalor** [comment]
Please post the version of `python3-mysqldb` or simply open a python terminal and paste
>>> import MySQLdb
>>> MySQLdb.version_info

**Comment by pmhahn** [comment]
> Please post the version of `python3-mysqldb` or simply open a python terminal and paste

Debian 11 "Bullseye" has [python3-mysqlbd](https://packages.debian.org/bullseye/python3-mysqldb) version `1.4.4-2`.

**Comment by pmhahn** [comment]
> job.starttime is of type MythTV.datetime and is timezone aware
No, not for me:

```
$ python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from MythTV import MythDB, Job
>>> db = MythDB()
>>> job = Job(16168)
>>> job.starttime
datetime.datetime(2021, 8, 30, 13, 58)
>>> type(job.starttime)
<class 'datetime.datetime'>
```

That time is in UTC, as the real start time is 16:00 CEST (minus 2 minutes early start)

```
pdb3
…
> /usr/lib/python3/dist-packages/MythTV/database.py(203)_pull()
(Pdb) p res
((16168, 55622, datetime.datetime(2021, 8, 30, 13, 58), datetime.datetime(2021, 8, 30, 15, 0), 2, 0, 0, 4, datetime.datetime(2021, 8, 30, 17, 13, 24), 'barrel', b'', '67% erledigt @ 84.4104 fps.', datetime.datetime(2021, 8, 30, 15, 0)),)
...
-> if (val.type in ('datetime','timestamp')) \
(Pdb) p val.type
'datetime /* mariadb-5.3 */'
(Pdb) p val
{'type': 'datetime /* mariadb-5.3 */', 'null': 'NO', 'key': '', 'default': '0000-00-00 00:00:00', 'extra': ''}
```

Looks like [mythtv/bindings/python/MythTV/database.py#L186](https://github.com/MythTV/mythtv/blob/master/mythtv/bindings/python/MythTV/database.py#L186) does not like my version of MariaDB, as MySQL is not available from Debian.

**Comment by rcrdnalor** [comment]
I suggest to fix your installation:

```
$ mysql -u mythtv -p<your password here> mythconverg

Server version: 10.5.11-MariaDB-1 Debian 11

MariaDB [mythconverg]> select * from jobqueue;
+----+--------+---------------------+---------------------+------+------+-------+--------+---------------------+----------+------+---------+---------------------+
| id | chanid | starttime           | inserttime          | type | cmds | flags | status | statustime          | hostname | args | comment | schedruntime        |
+----+--------+---------------------+---------------------+------+------+-------+--------+---------------------+----------+------+---------+---------------------+
|  8 |  10171 | 2021-08-27 10:10:00 | 2021-08-30 19:13:43 |  256 |    0 |     0 |      1 | 2021-08-30 21:13:43 |          |      |         | 2021-08-30 19:13:43 |
+----+--------+---------------------+---------------------+------+------+-------+--------+---------------------+----------+------+---------+---------------------+
1 row in set (0.001 sec)

MariaDB [mythconverg]> exit;
Bye
```
and
```
$ python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from MythTV import MythDB, Job
>>> db = MythDB()
>>> job = Job(8)
>>> job.starttime
datetime(2021, 8, 27, 12, 10, tzinfo=<MythTV.utility.dt.posixtzinfo object at 0x7f0545602130>)
>>> type(job.starttime)
<class 'MythTV.utility.dt.datetime'>
>>> 
```

Using the same installation and versions as stated previously.

**Comment by pmhahn** [comment]
> I suggest to fix your installation:

Probably everyone updating his system from MySQL to MariaDB will be affected:

[MariaDB 10 1.2](https://mariadb.com/kb/en/datetime/#internal-format) changed its internal format for `datetime`: Everybody updating from an older version of *MySQL 5.6* to that version will be affected as starting with `MariaDB 10 5.1` it will append the ` /* mariadb-5.3 */` comment, which [MythTV/database,py]( mythtv/bindings/python/MythTV/database.py#L186) does not handle.

I see the follwoing options:
1. Either update all your tables to use the new format using `ALTER TABLE <table_name> MODIFY <column_name> DATETIME;` manually
2. Do a SQL `dump` and `restore`.
3. Change [MythTV/database,py]( mythtv/bindings/python/MythTV/database.py#L186) to also handle *types with comments*.

**Comment by pmhahn** [comment]
```sh
docker network create some-network
docker run --net some-network --name some-mariadb -e MARIADB_ROOT_PASSWORD=my-secret-pw -d mariadb
docker run -it --network some-network --rm mariadb mysql -hsome-mariadb -uroot -pmy-secret-pw
```

```sql
SET GLOBAL mysql56_temporal_format=OFF;
SHOW VARIABLES LIKE 'mysql56_temporal_format';
CREATE SCHEMA mythtv;
\r mythtv
DESCRIBE t1;
```

```
+-------------------------+-------+
| Variable_name           | Value |
+-------------------------+-------+
| mysql56_temporal_format | OFF   |
+-------------------------+-------+

+-------+----------------------------+------+-----+---------+-------+
| Field | Type                       | Null | Key | Default | Extra |
+-------+----------------------------+------+-----+---------+-------+
| d     | datetime /* mariadb-5.3 */ | YES  |     | NULL    |       |
+-------+----------------------------+------+-----+---------+-------+
1 row in set (0.004 sec)
```

* https://mariadb.com/docs/reference/mdb/system-variables/mysql56_temporal_format/
* https://mariadb.com/kb/en/library/server-system-variables/#mysql56_temporal_format

**Comment by rcrdnalor** [comment]
Thank you again for providing this information.

Below a recipe to reproduce this bug on a fresh installation of mariadb >= 10.5.1 and MythTV:

I switched the global key `mysql56_temporal_format` off as root user:
```
MariaDB [(none)]> SET GLOBAL mysql56_temporal_format = OFF;
```
created an additional table `datetimetest`:
```
MariaDB [mythconverg]> describe datetimetest;

+-------+----------------------------+------+-----+---------------------+----------------+
| Field | Type                       | Null | Key | Default             | Extra          |
+-------+----------------------------+------+-----+---------------------+----------------+
| dtid  | int(10) unsigned           | NO   | PRI | NULL                | auto_increment |
| dt0   | datetime /* mariadb-5.3 */ | NO   |     | 0000-00-00 00:00:00 |                |
+-------+----------------------------+------+-----+---------------------+----------------+
2 rows in set (0.001 sec)
```
turned the global key `mysql56_temporal_format` on again and 
could reproduce the error by running this python script:
```
#!/usr/bin/env python3

""" read/write test to table 'datetimetest' """

from MythTV import MythDB, DBDataWrite, MythError, datetime

class DateTimeTest(DBDataWrite):
    """Additional calls to test MythTV's python bindings."""
    _table = 'datetimetest'
    _key   = ['dtid']

db = MythDB()

now = datetime.now()

newdtentry = DateTimeTest(db=db).create({'dt0': now})
newdtentry.update()

i = 1
while(True):
    try:
        thisdtentry = DateTimeTest(i, db=db)
        print(thisdtentry.dt0, type(thisdtentry.dt0))
        i += 1
    except MythError:
        break
```
which results like this:
```
2021-09-01 20:56:51 <class 'datetime.datetime'>
```

I applied the attached patch and got the following result:
```
2021-09-02 19:57:25+02:00 <class 'MythTV.utility.dt.datetime'>
```

The data supplied to the class `_TableFields.__init__(self, result)`:
input : 'result':
```
(('dtid', 'int(10) unsigned', 'NO', 'PRI', None, 'auto_increment'),
 ('dt0', 'datetime /* mariadb-5.3 */', 'NO', '', '0000-00-00 00:00:00', ''))
```
and the resulting output ('data'):
```
[('dtid', {'type': 'int(10) unsigned', 'null': 'NO', 'key': 'PRI', 'default': None, 'extra': 'auto_increment'}),
 ('dt0', {'type': 'datetime', 'null': 'NO', 'key': '', 'default': '0000-00-00 00:00:00', 'extra': ''})]
```

Could you please check this patch?

BTW, changing the database for the key `DATETIME` only might not fix all errors:
Probably necessary to look for `DATE`, `TIME` and `TIMESTAMP` literals as well.

Patch:
[datetime_mariadb_comment_patch.zip](https://github.com/MythTV/mythtv/files/7100994/datetime_mariadb_comment_patch.zip)

**Comment by pmhahn** [comment]
Attaching `.zip` files makes reviewing your patch much harder as I need to download and unpack it first.

```diff
diff --git a/mythtv/bindings/python/MythTV/database.py b/mythtv/bindings/python/MythTV/database.py
index e8b8bf5d52..17e9bb8817 100644
--- a/mythtv/bindings/python/MythTV/database.py
+++ b/mythtv/bindings/python/MythTV/database.py
@@ -1119,10 +1119,12 @@ class DBCache( MythSchema ):
             def __repr__(self): return py23_repr(str(self))
             def __iter__(self): return self.iterkeys()
             def __init__(self, result):
+                # remove comments in items like "datetime /* mariadb-5.3 */"
                 data = [(row[0],
                          OrdDict(zip( \
-                                ('type','null','key','default','extra'),
-                                row[1:])) \
+                            ('type','null','key','default','extra'),
+                            [x.split('/*', 1)[0].rstrip() \
+                                if x is not None else None for x in row[1:]])) \
                          )for row in result]
                 OrdDict.__init__(self, data)
             def __getitem__(self,key):
```

- Add a reference to this issue `#384` in the comment to make it easier for future generations to research on the why
- Please limit the comment stripping to column 1; otherwise if we ever get an default with `/*` bad things will happen.

**Comment by rcrdnalor** [comment]
Version 2 of the patch now limits stripping to item 'type':
````
diff --git a/mythtv/bindings/python/MythTV/database.py b/mythtv/bindings/python/MythTV/database.py
index e8b8bf5d52..d35a77ad47 100644
--- a/mythtv/bindings/python/MythTV/database.py
+++ b/mythtv/bindings/python/MythTV/database.py
@@ -1119,10 +1119,11 @@ class DBCache( MythSchema ):
             def __repr__(self): return py23_repr(str(self))
             def __iter__(self): return self.iterkeys()
             def __init__(self, result):
+                # remove comments in 'type' like "datetime /* mariadb-5.3 */"
                 data = [(row[0],
                          OrdDict(zip( \
-                                ('type','null','key','default','extra'),
-                                row[1:])) \
+                            ('type','null','key','default','extra'),
+                            (row[1].split('/*', 1)[0].rstrip(), ) + row[2:])) \
                          )for row in result]
                 OrdDict.__init__(self, data)
             def __getitem__(self,key):
````
A reference to this issue will be inside the commit message, as usual.

Patch v2:
/home/local-admin/MythTV/master/patches/datetime_mariadb_comment_patch_v2.zip
