### ISSUE TITLE
Support external (system) soundtouch libraries

### ISSUE THREAD

**Issue by garybuhrmaster** [MythTV/mythtv#387]
Support external (system) soundtouch libraries

The MythTV soundtouch library is somewhat dated, and does not include some more recent capabilities.  From reviewing the past commits that were in MythTV for soundtouch, and reviewing the soundtouch commits, it appears that all relevant fixes (and more) eventually made it upstream in regular releases, and have been available in most OS's for quite some time.

Rather than pull in a newer soundtouch library into the external directory, the project should support the system packaged soundtouch library when it is reasonably recent (which is true for any recent OS).

A pull request will be forthcoming doing so.

While I do not regularly use time stretch, limiting testing using the system soundtouch library seems to work properly with the expected tempo/pitch adjustments.

Note that should the pull request be accepted I will (likely slowly) work to update the ansible playbooks to pull in the system soundtouch for build purposes.

**Comment by linuxdude42** [comment]
What's the minimum version necessary to function properly? The oldest version I see on any of my builders is 1.8 on SuSe 15. If that's sufficient for MythTV, we should remove the extern/libmythsoundtouch directory and always require the system library.

**Comment by garybuhrmaster** [comment]
1.8.0 is the first version that officially supported multi-channel.  The configure script tests for that version (there are lots of improvements with later versions of soundtouch too) but I left the extern library support alone because of the android packaging, and I would expect that one would have to change to downloading/building the android soundtouch libraries (which I had not investigated).  So, I figured, don't break what you are not prepared to fix.

**Comment by mspieth** [comment]
On 29/09/2021 5:26 am, David Hampton wrote:
>
> What's the minimum version necessary to function properly? The oldest 
> version I see on any of my builders is 1.8 on SuSe 15. If that's 
> sufficient for MythTV, we should remove the extern/libmythsoundtouch 
> directory and always require the system library.
>
First we would need to add the upstream build to android and windows lib 
builders. Otherwise these would be broken.

I also thought there were some arm optimizations but looks like not. I 
obviously never got around to it.

Other than the above I have no objections.

2.3.1 is the latest release.

Also have to cater for libsoundtouch0 (<2) and libsoundtouch1 
(>=2)selection in configure.

I think 1.8 seems ok to use.

Mark




-- 
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by garybuhrmaster** [comment]
> Also have to cater for libsoundtouch0 (<2) and libsoundtouch1 (>=2)selection in configure. I think 1.8 seems ok to use. Mark

The configure script patch uses pkg-config (as does many of the other library version checks in configure), and falls back to the project's extern/ version, so installing the correct requirements is really an ansible (or manual admin) installation issue.

Realistically, I expected that it would take time to get the projects buildbot workers updated with the appropriate library (and who wants to see all red on the waterfall and be the blameee for all of the build failure messages?  Not I!), so I considered fallback to the project extern/ version was probably good as a first step.

**Comment by linuxdude42** [comment]
> First we would need to add the upstream build to android and windows lib builders. Otherwise these would be broken.

I forgot about android/win32. I will look into those as I have setups to build both. I did check all the various linux flavors, FreeBSD, and OSX. 

> Realistically, I expected that it would take time to get the projects buildbot workers updated with the appropriate library (and who wants to see all red on the waterfall and be the blameee for all of the build failure messages? Not I!),

I updated  all my build workers today with the soundtouch-dev (and equivalent) packages. :grin:

**Comment by garybuhrmaster** [comment]
> I updated all my build workers today with the soundtouch-dev (and equivalent) packages.

I updated the buildbot workers I administrator months ago when I was considering the patch in the first place (and my packaging repo spec file for MythTV also started to include the BR in early July, "just in case").  It tends to take me longer to write the justification documentation for submitting the project feature issue than writing/testing the patch itself (or at least it feels that way, since I tend to defer documentation as long as possible).

**Comment by jhoyt4** [comment]
> Note that should the pull request be accepted I will (likely slowly) work to update the ansible playbooks to pull in the system soundtouch for build purposes.

The ansible script for macports will require the "soundtouch" port which is currently at v2.0.0

**Comment by linuxdude42** [comment]
I have updated the android packaging to build libsoundtouch. (Both internal and external versions sound choppy on my Nvidia Shield box, but that's a different issue.)

**Comment by jhoyt4** [comment]
I've just verified that this works great on both ARM and Intel based macports builds.  I also kicked out a PR to update the macports ansible playbook.
