### ISSUE TITLE
Australian OTA HDTV - Channel 7 "Could not open decoder"

### ISSUE THREAD

**Issue by itneau1** [MythTV/mythtv#389]
* **Platform**: x86_64 / Ubuntu 20.04

* **MythTV version**:  31

* **Package version**: 2:31.0+fixes.202108081239.5da2523154~ubuntu20.04.1

* **Component**:tv playback/hdhomerun DVB-T/T2

### How often does it reproduce? Is there a required condition?
everyday I switch to channel 7 HDTV broadcast

### What is the expected behaviour?
these HDTV channels should work

### What do you see instead?

"Could not open decoder"

**Comment by kmdewaal** [comment]
I understand that you can make a recording of Channel 7 but that you cannot play back this recording.
Can you please post a (part of) such a recording on a file sharing website (e.g. pastebin or google)?

**Comment by itneau1** [comment]
I thing I cannot start recording because the error message says "failed to open decoder"

Sep 11 17:02:54 media mythfrontend.real: mythfrontend[1565]: I AudioOutputBase audio/audiooutputalsa.cpp:565 (WriteAudio) WriteAudio: Preparing 1536 bytes (384 frames)
Sep 11 17:02:54 media mythfrontend.real: mythfrontend[1565]: I AudioOutputBase audio/audiooutputalsa.cpp:565 (WriteAudio) WriteAudio: Preparing 1536 bytes (384 frames)
Sep 11 17:02:54 media mythfrontend.real: mythfrontend[1565]: I CoreContext decoders/avformatdecoder.cpp:916 (InitByteContext) AFD: Buffer size: 32768 Streamed 1 Seekable 1 Available 0
Sep 11 17:02:54 media mythfrontend.real: mythfrontend[1565]: W CoreContext decoders/avformatdecoder.cpp:302 (myth_av_log) [mpegts @ 00007fbb9f7fdba0] Could not detect TS packet size, defaulting to non-FEC/DVHS
Sep 11 17:02:54 media mythfrontend.real: mythfrontend[1565]: E CoreContext decoders/avformatdecoder.cpp:302 (myth_av_log) mpegts_read_header: read_packet() failed
Sep 11 17:02:54 media mythfrontend.real: mythfrontend[1565]: I CoreContext decoders/avformatdecoder.cpp:1045 (OpenFile) AFD: Failed to open input ('Operation not permitted')
Sep 11 17:02:54 media mythfrontend.real: mythfrontend[1565]: I AudioOutputBase audio/audiooutputalsa.cpp:565 (WriteAudio) WriteAudio: Preparing 1536 bytes (384 frames)
Sep 11 17:02:54 media mythfrontend.real: mythfrontend[1565]: I AudioOutputBase audio/audiooutputalsa.cpp:565 (WriteAudio) WriteAudio: Preparing 1536 bytes (384 frames)
Sep 11 17:02:54 media mythfrontend.real: mythfrontend[1565]: I AudioOutputBase audio/audiooutputalsa.cpp:565 (WriteAudio) WriteAudio: Preparing 1536 bytes (384 frames)
Sep 11 17:02:54 media mythfrontend.real: mythfrontend[1565]: I AudioOutputBase audio/audiooutputalsa.cpp:565 (WriteAudio) WriteAudio: Preparing 1536 bytes (384 frames)
Sep 11 17:02:54 media mythfrontend.real: mythfrontend[1565]: I CoreContext decoders/avformatdecoder.cpp:916 (InitByteContext) AFD: Buffer size: 32768 Streamed 1 Seekable 1 Available 128592
Sep 11 17:02:54 media mythfrontend.real: mythfrontend[1565]: E CoreContext decoders/avformatdecoder.cpp:302 (myth_av_log) mpegts_read_header: read_packet() failed
Sep 11 17:02:54 media mythfrontend.real: mythfrontend[1565]: I CoreContext decoders/avformatdecoder.cpp:1045 (OpenFile) AFD: Failed to open input ('Operation not permitted')
Sep 11 17:02:54 media mythfrontend.real: mythfrontend[1565]: E CoreContext decoders/avformatdecoder.cpp:1063 (OpenFile) AFD: Attempting to use original FFmpeg MPEG-TS demuxer.
Sep 11 17:02:54 media mythfrontend.real: mythfrontend[1565]: E CoreContext decoders/avformatdecoder.cpp:1076 (OpenFile) AFD: Fatal error opening input. Aborting
Sep 11 17:02:54 media mythfrontend.real: mythfrontend[1565]: E CoreContext mythplayer.cpp:891 (OpenFile) Couldn't open decoder for: /tv/live/1070_20210911070249.ts
Sep 11 17:02:54 media mythfrontend.real: mythfrontend[1565]: E CoreContext mythplayer.cpp:5459 (SetErrored) Player(j): Error Opening Jump Program File
Sep 11 17:02:54 media mythfrontend.real: mythfrontend[1565]: E CoreContext mythplayer.cpp:2669 (JumpToProgram) Player(j): JumpToProgram failed.
Sep 11 17:02:54 media mythfrontend.real: mythfrontend[1565]: E CoreContext mythplayer.cpp:2912 (EventLoop) Player(j): Unknown recorder error, exiting decoder
Sep 11 17:02:54 media mythfrontend.real: mythfrontend[1565]: I Decoder mythplayer.cpp:97 (run) Player(j): Decoder thread exiting.

**Comment by itneau1** [comment]
I will try to upload the .ts file to pastebin and share

**Comment by kmdewaal** [comment]
The error message shows that you are using Live TV which is recording and playback combined. This should work of course but for debugging the first thing is to know whether it is a recording problem or a playback problem. The log messages of mythfrontend suggest that the recording is bad or that it could not be read.
So please try first to make a recording.

**Comment by itneau1** [comment]
Hi I have uploaded two recording files  see below with description.

- 10070_20210920121322.ts which resulted in "Could Open Decoder" error and kicked me back to main menu
Link to file above is https://drive.google.com/file/d/1IeqZlEO7JeuL5eHSVIQr-HAfrewSYwv-/view?usp=sharing

- 10074_20210920121352.ts which did start recording but the video playback was in slow motion on TV. There is some more  
Link to file above https://drive.google.com/file/d/1Xeye0_hLjlj2rw0Gxg8ldgWBPCeGWdeb/view?usp=sharing
logging output for file "352" I thought might help.
Sep 20 22:13:58 media mythfrontend.real: mythfrontend[90905]: I CoreContext mythplayer.cpp:3104 (ProcessCallbacks) Player(u): Executing VAAPI context creation
Sep 20 22:13:58 media mythfrontend.real: mythfrontend[90905]: I CoreContext opengl/mythopenglinterop.cpp:158 (GetInteropType) OpenGLInterop: Rendering supported for frame type 'VAAPI' with VAAPI DRM
Sep 20 22:13:58 media mythfrontend.real: mythfrontend[90905]: I CoreContext opengl/mythvaapiinterop.cpp:116 (InitaliseDisplay) VAAPIInterop: Created VAAPI 1.10 display for VAAPI DRM (Intel iHD driver for Intel(R) Gen Graphics - 21.1.1 ())
Sep 20 22:13:58 media mythfrontend.real: mythfrontend[90905]: I CoreContext mythvideoout.cpp:400 (SetDeinterlacing) VideoOutput: SetDeinterlacing (Doublerate 1): Single Medium|CPU|GLSL Double Medium|CPU|GLSL

**Comment by kmdewaal** [comment]
The first file, the 10070, can be downloaded. The second file, the 10074, is set to "view only" and cannot be downloaded.
I have tested the 10070 with mythtv-master and it does play OK on a PC with NVIDIA/vdpau graphics and it plays also OK on my laptop with Intel graphics.
I think this means that your recordings are OK but that you do have a playback configuration problem.
I do suggest the following:
- create a complete log of the mythfrontend output and post that here
- experiment with playback profile settings (Setup / Video / Playback) setting Current Video Playback Profile and posibly also the other settings
- one level deeper, in Playback Settings, you can try enabling "Use FFmpeg's Original MPEG-TS demuxer"

**Comment by itneau1** [comment]
Following up on your request for details. Below is a complete log of change channel. Its long sorry and I have greped out SSDP and referencecounter.

I have played with all the playback profiles and each one is the same. I also tried enabling MPEG-TS demuxer. This setting results in a number of channels going blank. I even played with MPEG-TS and playback profiles with no success.

the mytvdebug log is too large to past into this window so I have uploaded to gdrive see link below

https://drive.google.com/file/d/175ps84d-mQOpKCfNbeLVyMfMKlWgvWbL/view?usp=sharing

Best
John

**Comment by itneau1** [comment]
Hi just a brief note on top of above material shared. I did some testing with older versions of mythtv 0.27-0.29 and each version was able to play all channels including the ones with present issues such as channel 7 HDTV.  Video playback is not great as intel graphics drivers are not good in ubuntu 18 but it all works. I am also able to use hdhomerun DVR application from my windows laptop to play all channels.

**Comment by kmdewaal** [comment]
You can also try the latest master and see if that works for you.
The log looks quite OK except for what I think is a channel change at the end of the log.
Could it be that this is only a Live TV issue and that recording and later playback does work?

FYI, there are known issues with Live TV, such as that a channel change does sometimes fail with the "Error Opening Jump Program File" message. This is however something that is not limited to a single channel.

**Comment by itneau1** [comment]
Hi 

You are correct, I only experience the issue when changing channel to Channel 74 or Channel 70 which are both HDTV broadcasts of Channel 7. Every other channel(24 channels) work regardless if they are SDTV or HDTV. 

I am using the Ubuntu packages and have never compiled mythtv from source. Is there a guide on how to do this?

Thanks again for your assistance.

**Comment by itneau1** [comment]
think I just found the guide. I'll give it a go

**Comment by kmdewaal** [comment]
Compiling from source is OK but note that for ubuntu the ppa packages for master are here: https://launchpad.net/~mythbuntu/+archive/ubuntu/32

As a bit of background, in v31 the mythtv video code has been completely refactored and simplified but there are still some wrinkles to iron out. If you do not need any of the features of v31 and later it could be that you are happier with v30.

**Comment by itneau1** [comment]
I did have 30 installed and was quite happy with it however I also experienced the same problem on 30 changing to channel 70 and 74. I upgraded from 30 hoping it was fixed in 31 or at least the MPEG-TS demuxer option would help.

**Comment by itneau1** [comment]
quick follow up, I have installed v 32 from ppa and channel 70 and 74 are now working. 

Thanks for your help

**Comment by kmdewaal** [comment]
I'm happy that this works for you and thanks for reporting back. Considering this issue fixed and closing the ticket.
