### ISSUE TITLE
Comparison of Services-API on devel/http branch to fixes/31

### ISSUE THREAD

**Issue by rcrdnalor** [MythTV/mythtv#414]
* **Platform**:  Ubuntu 21.10

* **MythTV version**: v32-Pre-3062-g6ea1342b40

* **MythTV branch**: devel/http

* **Package version**: N/A

* **Component**: MythTV Services 

**Comparison of Services-API on devel/http branch to fixes/31**

**General**:
 'Interface Version' are reset to '1.0' in every wsdl

*Note:* 
Each schema referenced below is created by resolving the 'imports' from the wsdl.
The schema and wsdl files are made canonical with 'xmllint --exc-c14n'.  
 

**Service "Channel":**  schema on devel/http (port 6744) can not be created:

http://ip-addr:6744/Channel/wsdl  --> 'GetDDLineupList'  calls
http://ip-addr:6744/Channel/xsd?type=LineupList
which returns
```
XML Parsing Error: no root element found
Location: http://ip-addr:6744/Channel/xsd?type=LineupList
Line Number 2, Column 1:
 ```

**Service "Content":**
Live stream missing as stated on wiki "Services_API_V2_Conversion"

**Service "Dvr":** wsdl: 
These operations are of type "POST" on v32 and of type "GET" on v31
    "AddDontRecordSchedule"
    "ReactivateRecording"
    "RescheduleRecordings"
    "StopRecording"
    "UnDeleteRecording"

**Service "Dvr"**: schema:
<xs:complexType name="Input">:
   these elements are of type "xs:unsignedInt" on v32 and "xs:int" on v31
   "RecPriority"
   "ScheduleOrder"
   "LiveTVOrder"
   
<xs:complexType name="RecordingInfo">:
name="Status" type="tns:RecStatus.Type" on v.31
name="Status" type="xs:string" on v.32

Enumeration 
<xs:element name="RecStatus.Type" is missing on v32

**Service "Frontend"**: wsdl:
<xs:element name="SendNotification">:
    "Timeout" type="xs:long" on v32
    "Timeout" type="xs:int" on v31
    
    
**Service "Guide":** schema:
<xs:complexType name="RecordingInfo">:
  name="Status" type="tns:RecStatus.Type" on v.31
  name="Status" type="xs:string" on v.32

Enumeration 
<xs:element name="RecStatus.Type" is missing on v32

**Service "Myth":** wsdl:
Change Password is missing as stated on wiki "Services_API_V2_Conversion"

**Service "Myth"**: schema
element name="Frontend":
  element name="OnLine" type="xs:boolean" on v32
  element name="OnLine" type="xs:int" on v31

**Final Note:**
Since we do now make a "v2" Version of the Services API, can we resolve the
circular dependency in the "Guide" service (which is probably for backward compatibility) ?

http://ip-addr:6744/Guide/wsdl
'GetProgramDetails' returns a 'Program' defined in 
http://ip-addr:6744/Guide/xsd?type=Program
which has a 'ChannelInfo' member defined in
http://ip-addr:6744/Guide/xsd?type=ChannelInfo
which itself has a an 'ArrayOfProgram' as member

'Program' --> 'ChannelInfo' --> 'ArrayOfProgram' --> 'Program'

I know, that this loop is interrupted by not filling in the programs into 'ChannelInfo', at least on v31.

**Comment by rcrdnalor** [comment]
Attached
[0001-channel_services_lineup.zip](https://github.com/MythTV/mythtv/files/7611811/0001-channel_services_lineup.zip)
 a patch that fixes the issue that the schema on devel/http (port 6744) for the Service "Channel" can not be created.
This minimal patch may not be complete, and may un-hide further bugs.

```
diff --git a/mythtv/programs/mythbackend/servicesv2/v2channel.cpp b/mythtv/programs/mythbackend/servicesv2/v2channel.cpp
index fc89df6852..04eef25e0d 100644
--- a/mythtv/programs/mythbackend/servicesv2/v2channel.cpp
+++ b/mythtv/programs/mythbackend/servicesv2/v2channel.cpp
@@ -61,6 +61,7 @@ void V2Channel::RegisterCustomTypes()
     qRegisterMetaType<V2VideoSourceList*>("V2VideoSourceList");
     qRegisterMetaType<V2VideoSource*>("V2VideoSource");
     qRegisterMetaType<V2LineupList*>("V2LineupList");
+    qRegisterMetaType<V2Lineup*>("V2Lineup");
     qRegisterMetaType<V2VideoMultiplexList*>("V2VideoMultiplexList");
     qRegisterMetaType<V2VideoMultiplex*>("V2VideoMultiplex");
     qRegisterMetaType<V2Program*>("V2Program");
diff --git a/mythtv/programs/mythbackend/servicesv2/v2lineup.h b/mythtv/programs/mythbackend/servicesv2/v2lineup.h
index 7d5c63c666..5e16f9a192 100644
--- a/mythtv/programs/mythbackend/servicesv2/v2lineup.h
+++ b/mythtv/programs/mythbackend/servicesv2/v2lineup.h
@@ -64,7 +64,7 @@ class V2LineupList : public QObject
 
     public:
 
-        V2LineupList(QObject *parent = nullptr)
+        Q_INVOKABLE V2LineupList(QObject *parent = nullptr)
             : QObject( parent )
         {
         }
@@ -85,6 +85,8 @@ class V2LineupList : public QObject
             return pObject;
         }
 
+    private:
+        Q_DISABLE_COPY(V2LineupList);
 };
 
 Q_DECLARE_METATYPE(V2LineupList*)
```

**Comment by rcrdnalor** [comment]
@bennettpeter , @billmeek 
Could you please look at this issue?
I have no clue, what the Service  'GetDDLineupList'  does.
And, according to the last MySQL problems, I believe that a  'RecPriority' can be negative as well.

Roland

**Comment by garybuhrmaster** [comment]
> I have no clue, what the Service 'GetDDLineupList' does. 

As I recall GetDDLineupList (and some associated other support) was intended/used as part of the (now removed) Data Direct support in MythTV.  It (and other other lingering DD code artifacts) likely need to just be removed.

**Comment by bennettpeter** [comment]
> 

I committed the change from Roland to fix the wsdl for GetDDLineupList

**Comment by bennettpeter** [comment]
> **Service "Content":** Live stream missing as stated on wiki "Services_API_V2_Conversion"
> 
We are not converting those as they do not work and require an old version of proprietary software.
> **Service "Dvr":** wsdl: These operations are of type "POST" on v32 and of type "GET" on v31 "AddDontRecordSchedule" "ReactivateRecording" "RescheduleRecordings" "StopRecording" "UnDeleteRecording"

This is on purpose, because these methods perform updates and thus should use POST. Should we still allow GET for backward compatibility?

**Comment by bennettpeter** [comment]
> **Service "Dvr"**: schema: <xs:complexType name="Input">: 
> 
> <xs:complexType name="RecordingInfo">: name="Status" type="tns:RecStatus.Type" on v.31 name="Status" type="xs:string" on v.32
> 
> Enumeration <xs:element name="RecStatus.Type" is missing on v32

That is not working in the old system (port 6544) on v32. In the wsdl display if you click on the link for tns:RecStatus.Type, you get this response: _Invalid arguments to xsd query: enum=RecStatus.Type_. I could not find an easy way to fix it in  the new system. However the status is a string and now it is reflected as a string, so I think it should be OK that way.

**Comment by bennettpeter** [comment]
> **Service "Dvr"**: schema: <xs:complexType name="Input">: these elements are of type "xs:unsignedInt" on v32 and "xs:int" on v31 "RecPriority" "ScheduleOrder" "LiveTVOrder"

Fixed 
* 669290426e 2021/12/12 Peter Bennett : V2 Services: Fix DVR service input structure unsigned ints

**Comment by bennettpeter** [comment]
> **Service "Myth"**: schema element name="Frontend": element name="OnLine" type="xs:boolean" on v32 element name="OnLine" type="xs:int" on v31

This is a bit silly. The value returned is actually a boolean that is being converted to an int for output. It is based on connectioncount > 0. If it is going to return an int why not just return the connectioncount and call it connectioncount?

For backwards compatibility, should we leave it as an int, converted from a boolean ?

**Comment by bennettpeter** [comment]
> **General**: 'Interface Version' are reset to '1.0' in every wsdl

Commit 95682924e9: Version numbers are now set to match what they were before

**Comment by bennettpeter** [comment]
> Should we still allow GET for backward compatibility?

The consensus is we should not allow GET for methods that update the server. We will be leaving these as POST.

**Comment by billmeek** [comment]
Updated https://www.mythtv.org/wiki/DVR_Service to reflect POST requirements for v32+.

**Comment by rcrdnalor** [comment]
@bennettpeter , @billmeek 
Thank you for implementing this issue.
Closing this issue because everything have been implemented or justified.
Note:
The "Guide" service still has this mentioned circular dependency, it is accepted because of keeping backwards compatibility.
