### ISSUE TITLE
Version 32 crashes (reproducible)

### ISSUE THREAD

**Issue by vidtek** [MythTV/mythtv#415]
I have an issue detailed here: 
After zapping 31 and re-installing 32, I have the crashing issue back again.
It is easily repeatable as it happens when scrolling fast through many episodes in the video list menu, as well as sometimes when fast scrolling through the epg.

There is nothing in the frontend or backend logs of any help, but if I start via the command line, when it crashes I get this at the end: 

`2021-11-18 09:18:07.834251 N  Resuming idle timer
2021-11-18 09:18:41.313141 E  XMLParseBase: Parent is NULL
2021-11-18 09:18:44.316598 I  Qt: libpng warning: iCCP: known incorrect sRGB profile
2021-11-18 09:18:44.762858 I  Qt: libpng warning: iCCP: known incorrect sRGB profile
2021-11-18 09:18:44.838071 I  Qt: libpng warning: iCCP: known incorrect sRGB profile
*** stack smashing detected ***: terminated
Handling Aborted
Aborted (core dumped)
tony@linuxmint:~$`

**Kernel: 5.11.0-40-generic

System:** 

`/etc/lsb-release
::::::::::::::
DISTRIB_ID=neon
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="KDE neon User - Plasma 25th Anniversary Edition"
::::::::::::::
/etc/os-release
::::::::::::::
NAME="KDE neon"
VERSION="5.23"
ID=neon
ID_LIKE="ubuntu debian"
PRETTY_NAME="KDE neon User - Plasma 25th Anniversary Edition"
VARIANT="User Edition"
VARIANT_ID=user
VERSION_ID="20.04"`

**Hardware:**

**Mobo, ram and cpu**
`root@linuxmint:/home/tony# lshw
linuxmint                   
    description: Desktop Computer
    product: System Product Name (SKU)
    vendor: System manufacturer
    version: System Version
    serial: System Serial Number
    width: 64 bits
    capabilities: smbios-3.0.0 dmi-3.0.0 smp vsyscall32
    configuration: boot=normal chassis=desktop family=To be filled by O.E.M. sku=SKU uuid=4038F42E-DAD7-DD11-A3AD-107B44F25051
  *-core
       description: Motherboard
       product: STRIX Z270E GAMING
       vendor: ASUSTeK COMPUTER INC.
       physical id: 0
       version: Rev 1.xx
       serial: 170706774500147
       slot: Default string
     *-firmware
          description: BIOS
          vendor: American Megatrends Inc.
          physical id: 0
          version: 1302
          date: 03/15/2018
          size: 64KiB
          capacity: 16MiB
          capabilities: pci apm upgrade shadowing cdboot bootselect socketedrom edd int13floppy1200 int13floppy720 int13floppy2880 int5printscreen int9keyboard int14serial int17printer acpi usb biosbootspecification uefi
     *-memory
          description: System Memory
          physical id: 46
          slot: System board or motherboard
          size: 16GiB
        *-bank:0
             description: [empty]
             physical id: 0
             slot: ChannelA-DIMM1
        *-bank:1
             description: DIMM DDR4 Synchronous Unbuffered (Unregistered) 2133 MHz (0.5 ns)
             product: CMK16GX4M2B3000C15
             vendor: Corsair
             physical id: 1
             serial: 00000000
             slot: ChannelA-DIMM2
             size: 8GiB
             width: 64 bits
             clock: 2133MHz (0.5ns)
        *-bank:2
             description: [empty]
             physical id: 2
             slot: ChannelB-DIMM1
        *-bank:3
             description: DIMM DDR4 Synchronous Unbuffered (Unregistered) 2133 MHz (0.5 ns)
             product: CMK16GX4M2B3000C15
             vendor: Corsair
             physical id: 3
             serial: 00000000
             slot: ChannelB-DIMM2
             size: 8GiB
             width: 64 bits
             clock: 2133MHz (0.5ns)
     *-cache:0
          description: L1 cache
          physical id: 4c
          slot: L1 Cache
          size: 256KiB
          capacity: 256KiB
          capabilities: synchronous internal write-back unified
          configuration: level=1
     *-cache:1
          description: L2 cache
          physical id: 4d
          slot: L2 Cache
          size: 1MiB
          capacity: 1MiB
          capabilities: synchronous internal write-back unified
          configuration: level=2
     *-cache:2
          description: L3 cache
          physical id: 4e
          slot: L3 Cache
          size: 8MiB
          capacity: 8MiB
          capabilities: synchronous internal write-back unified
          configuration: level=3
     *-cpu
          description: CPU
          product: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
          vendor: Intel Corp.
          physical id: 4f
          bus info: cpu@0
          version: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
          serial: To Be Filled By O.E.M.
          slot: LGA1151
          size: 4318MHz
          capacity: 4500MHz
          width: 64 bits
          clock: 100MHz`

**Video and audio hardware:**

` *-display
                description: VGA compatible controller
                product: TU116 [GeForce GTX 1660]
                vendor: NVIDIA Corporation
                physical id: 0
                bus info: pci@0000:01:00.0
                version: a1
                width: 64 bits
                clock: 33MHz
                capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
                configuration: driver=nvidia latency=0
                resources: irq:161 memory:de000000-deffffff memory:c0000000-cfffffff memory:d0000000-d1ffffff ioport:e000(size=128) memory:c0000-dffff
           *-multimedia
                description: Audio device
                product: TU116 High Definition Audio Controller
                vendor: NVIDIA Corporation
                physical id: 0.1
                bus info: pci@0000:01:00.1
                version: a1
                width: 32 bits
                clock: 33MHz
                capabilities: pm msi pciexpress bus_master cap_list
                configuration: driver=snd_hda_intel latency=0
                resources: irq:17 memory:df080000-df083fff`

**PCI TV Tuner card  Hauppage Quad tuner**

`*-multimedia
                      description: Multimedia video controller
                      product: CX23887/8 PCIe Broadcast Audio and Video Decoder with 3D Comb
                      vendor: Conexant Systems, Inc.
                      physical id: 0
                      bus info: pci@0000:08:00.0
                      version: 04
                      width: 64 bits
                      clock: 33MHz
                      capabilities: pciexpress pm vpd msi bus_master cap_list
                      configuration: driver=cx23885 latency=0
                      resources: irq:16 memory:df400000-df5fffff
*-multimedia
                      description: Multimedia video controller
                      product: CX23887/8 PCIe Broadcast Audio and Video Decoder with 3D Comb
                      vendor: Conexant Systems, Inc.
                      physical id: 0
                      bus info: pci@0000:09:00.0
                      version: 04
                      width: 64 bits
                      clock: 33MHz
                      capabilities: pciexpress pm vpd msi bus_master cap_list
                      configuration: driver=cx23885 latency=0
                      resources: irq:17 memory:df200000-df3fffff`

### _The same hardware works well with version 31, but there are issues with EIT on 31 I have been unable to resolve._

Thank you for reporting an issue in MythTV.

This issue tracker is for bugs and issues found within MythTV.
If you require more general support please see the support section
of our website: https://www.mythtv.org/support

Please fill in as much of the template below as you're able to.

Platform: Distro and output of `uname -a` (Linux/UNIX), or version and 32/64-bit (Windows)
MythTV version: the version of MythTV you are running (master, fixes/31, etc)
Package version: if using a packaged version of MythTV, please provide repository/version
Component: if known, please specify the affected component (e.g. frontend/backend)
-->

* **Platform**:Kernel: 5.11.0-40-generic

* **MythTV version**: 32

* **Package version**:n/a

* **Component**: Video menu and EPG display mainly

### What is the expected behaviour?  Normal scrolling without crashes.

  see above

**Comment by vidtek** [comment]
Since filing this bug report a suggestion was made by @paulh  to install the debug version of mythtv.

I have just done this and the debugging installed these replcement files:
`Setting up mythtv-backend (2:32.0~master.202111171603.57a388e222~ubuntu20.04.1) ...
Setting up mythtv-dbg (2:32.0~master.202111171603.57a388e222~ubuntu20.04.1) ...
`

I have since tried to reproduce this issue and it isn't crashing at the moment.  Perhaps the backend update may have corrected the error?

If it happens again in the next few days I will advise you guys.  Thank for all your hard work.
Cheers Tony.

**Comment by bennettpeter** [comment]
Is the frontend or backend crashing?

**Comment by vidtek** [comment]
@bennettpeter   The frontend.  Although as I have just posted, when installing the debug bits it updated the backend and has not crashed since that update.
Before I could reproduce the crash at will.

**Comment by bennettpeter** [comment]
I can't see why installing debugging files on the backend would solve a problem with the frontend. It likely just masked the problem by making things a bit slower.

To debug the issue will need debug information on the frontend, and then to capture a core dump and get a backtrace from that.

**Comment by Jpilk** [comment]
I have seen this occasionally;  it seemed to occur on scrolling rapidly upwards in the EPG immediately after starting the frontend.

**Comment by vidtek** [comment]
@bennetpeter I can't get it to crash now!  I installed mythv-dbg and that also installed a new version of mythtv-backend (2:32.0~master.202111171603.57a388e222~ubuntu20.04.1)
I think that's what fixed it.
Thanks again for your help, I'll mark this as solved....Cheers Tony.

**Comment by kmdewaal** [comment]
I have incidentally seen the "stack smashing" error also when scrolling.
