### ISSUE TITLE
scheduler breaks with negative priorities

### ISSUE THREAD

**Issue by tapanitarvainen** [MythTV/mythtv#417]
* **Platform**: Ubuntu 20.04

* **MythTV version**:  31.0

* **Package version**:  2:31.0+fixes.20200323.9579662cdc-0ubuntu1

* **Component**: backend

### What steps will reproduce the bug?

Deliberately triggering it is difficult. I encountered it when I used negative values as channel priorities, but other negative values in the calculation of powerpriority could trigger it as well.

### How often does it reproduce? Is there a required condition?

The bug occurs at seemingly random, hard to predict times. After I'd set some negative values to some channel priorities it took several months before I noticed it, after that it became a constant, daily problem.

It only occurs when at least one of the values used in powerpriority calculation in the scheduler is negative, so as a workaround I changed all the priorities to be positive.

### What is the expected behaviour?

Normal scheduling of recordings.

### What do you see instead?

Some schedules are effectively disabled, sometimes all of them. Adding a new recording rule can disable others, with no apparent reason.

The bug can be seen in mythbackend.log with error messages like this:

Nov 23 19:22:40 kaiku mythbackend: mythbackend[153000]: E Scheduler mythdb.cpp:181 (DBError) DB Error (AddNewRecords):#012Query was:#012SELECT [...]

### Additional information

Testing the error-triggering SELECT statement manually gave this error:

ERROR 1690 (22003): BIGINT UNSIGNED value is out of range in '((`mythconverg`.`c`.`recpriority` + `mythconverg`.`capturecard`.`recpriority`) + ((`mythconverg`.`capturecard`.`cardid` = `mythconverg`.`record`.`prefinput`) * 2))'

The cause of the problem is clear: capturecard.cardid is unsigned and it causes all values in the expression to be treated as unsigned as well. When some of them are small negative values, they become big positive values that can easily cause an overflow, or just a wrong value as the result.

The calculation is done in scheduler.cpp:

    if (prefinputpri)
        pwrpri += QString(" + "
        "(capturecard.cardid = RECTABLE.prefinput) * %1").arg(prefinputpri);

I looked at the latest development version, the code is somewhat different but the bug seems to be still there (I didn't try building it):

    if (prefinputpri)
    {
        pwrpri += QString(" + "
        "IF(capturecard.cardid = RECTABLE.prefinput, 1, 0) * %1")
            .arg(prefinputpri);
    }

Obvious fix would be casting cardid as signed, e.g., replace capturecard.cardid with

cast(capturecard.cardid as signed)

in the above.

**Comment by paul-h** [comment]
Should be fixed in master 8646ad3 and 8ebfeb3 and in fixes/31 bb507cf and 5d6f06c

You probably need to switch to use the MythBuntu PPA (https://launchpad.net/~mythbuntu/+archive/ubuntu/31) for fixes/31 so you can get a more up to date version.

**Comment by tapanitarvainen** [comment]
Right you are. It has indeed been fixed, I should've looked at the development version more carefully.

Thank you!
