### ISSUE TITLE
Unable to builld with x264 3:0.163 or newer on Arch Linux

### ISSUE THREAD

**Issue by JohnLBergqvist** [MythTV/mythtv#419]
* **Platform**: Arch Linux - `Linux Server 5.10.82-1-lts #1 SMP Fri, 26 Nov 2021 10:51:51 +0000 x86_64 GNU/Linux`

* **MythTV version**: `fixes/31`

* **Package version**: [mythtv 31+fixes.20210401.563a05b7-1](https://aur.archlinux.org/packages/mythtv/)

* **Component**: 

### What steps will reproduce the bug?

Building MythTV from source when `x264 3:0.163` (or newer) is installed. 

### How often does it reproduce? Is there a required condition?

Rolling back to a previous version of the package (`3:0.161` is the next oldest released for Arch) will resolve the issue

### What is the expected behaviour?

the build should succeed

### What do you see instead?

The build fails at:

```
CC      libavutil/hwcontext_cuda.o
CC      libavcodec/cuviddec.o
CC      libavcodec/nvdec.o
CC      libavcodec/nvdec_h264.o
CC      libavcodec/nvdec_hevc.o
CC      libavcodec/nvdec_mjpeg.o
CC      libavcodec/nvdec_mpeg12.o
CC      libavcodec/nvdec_mpeg4.o
CC      libavcodec/nvdec_vc1.o
CC      libavcodec/nvdec_vp8.o
CC      libavcodec/nvdec_vp9.o
GEN     libavutil/libavutil.ver
GEN     libavcodec/libavcodec.ver
LD      libavutil/libmythavutil.so.56
LD      libpostproc/libmythpostproc.so.55
LD      libswscale/libmythswscale.so.5
LD      libswresample/libmythswresample.so.3
LD      libavcodec/libmythavcodec.so.58
LD      libavformat/libmythavformat.so.58
LD      libavfilter/libmythavfilter.so.7
LD      libavdevice/libmythavdevice.so.58
LD      ffmpeg_g
LD      ffprobe_g
/usr/bin/ld: libavcodec/libmythavcodec.so: undefined reference to `x264_encoder_open_161'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:111: ffprobe_g] Error 1
make[2]: *** Waiting for unfinished jobs....
/usr/bin/ld: libavcodec/libmythavcodec.so: undefined reference to `x264_encoder_open_161'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:111: ffmpeg_g] Error 1
make[2]: Leaving directory '/home/mythtv/mythtv/src/mythtv/mythtv/external/FFmpeg'
make[1]: *** [Makefile:25: FFmpeg-all] Error 2
make[1]: Leaving directory '/home/mythtv/mythtv/src/mythtv/mythtv/external'
make: *** [Makefile:66: external] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

In Arch's package management system, `x264 v163` is technically tied to `ffmpeg 2:4.4-5` and newer, but in practice, forcing `x264 v161` over a system which has the latest (at the time of writing) `ffmpeg-2:4.4.1-1` version installed does not prevent the build succeding when using `x264 v161`.
Below is a table showing the build success vs the relationship betwen the 2 packages at their different versions:
||x264 3:0.161|x264 3:0.163|
|:-:|:-:|:-:|
|FFmpeg 2:4.4-5|:white_check_mark:|:x:|
|FFmpeg2:4.4.1-1|:white_check_mark:|:x:|

**Comment by linuxdude42** [comment]
I have x264-3:0.163.r3060.5db6aa6-1and ffmpeg-2:4.4.1-1installed on my arch builder, and I'm able to compile. Have you tried a 'git clean -xfd ..' from the mythtv directory, and then configured and compiled again? Based on the missing symbol names I would guess that your mythtv tree still has some remnant left from when it was compiled against x264-0.161.

**Comment by JohnLBergqvist** [comment]
Ah yes, that did it. Thanks!
