### ISSUE TITLE
"Error opening jump program file buffer" on Live TV channel change

### ISSUE THREAD

**Issue by kmdewaal** [MythTV/mythtv#452]
A Live TV channel change sometimes fails with a "Error opening jump program file buffer" popup message.
This happens in the following sequence.
- Given a capture card with at least 2 instances, one physical and one (or more) virtual
- Start Live TV, e.g. by pressing "Watch TV" on the main menu page or by selecting a channel in the guide and start watching
- Live TV is started on a virtual capture card
- Select a new channel on a different multiplex
- After about 10 seconds the "Error opening jump program file buffer" appears.
- This is 100% reproducible.

This problem does not happen when:
- the second channel is on the same multiplex; then also subsequent channel changes are OK
- the first channel is on the physical capture card; then all subsequent channel changes are OK

This problem is caused by code in TVRec::CreateChannel introduced by the following commits:
90f98e621a7efdf0bd3faf3905a7055322d3f24a Don't set the channel when initializing child inputs.
0c6fd96275f63b742d823c1ce0a37aca9990b828  Do not set channel for child recorder

What happens is that only the real capture card is compietely initalized. This sets si_standard to "dvb".
The virtual capture cards are only partially initialized; the si_standard is left at the initial value of "mpeg".
The m_sistandard value is later called m_tuningMode.

Tuning is done in TVRec::SetupDTVSignalMonitor.
With Live TV the first channel tuning is done in mode "mpeg". After tuning the m_sistandard value of the channel is set to "dvb".
Tuning to a new channel in another mulitplex does then tune in mode "dvb". 
Here a check is done if the existing StreamData is a DVBStreamData. There is a StreamData from the first tuning but this is not a DVBStreamData and hence a new DVBStreamData is created.
The Live TV playback was attached to the first StreamData; the "dvb" tune caused a switch to the DVBStreamData and therefore no video data was sent to the Live TV playback anymore.

The obvious fix is to do full initalisation for all capturecards. it is the intention to apply this fix at short notice.

The reason for creating this Github issue is to document this and to be able to refer to this issue in the forthcoming fix.

![Screenshot from 2022-01-06 22-28-29](https://user-images.githubusercontent.com/10491032/148459321-72f1cd55-144c-4b97-8f47-d8a93e790ebe.png)

**Comment by gigem** [comment]
Klaas, please find a solution which initializes the child inputs as much as needed but no more.  The referenced commits which bypass much of the initialization are HIGHLY desirable as performing the full initialization causes the already way too long backend start up times to be much, much worse when there are large numbers of child inputs.  My backend start up times are still 3-4 minutes as it is now.  If I remember correctly, before those commits, my start up times were 7 minutes or more.

**Comment by kmdewaal** [comment]
Hi David, yes, I do share your concern about startup times. As I understand it, the purpose of the tuning at startup is to determine if the card is really present and working and consequently this only needs to be done for the parent input. I have not really worked out the logic for this but it should be possible to do the initial tuning only for parent inputs and then immediately initialize also all child inputs of that parent. 
However, I cannot promise that this is done and fully tested in time for the version 32 freeze.

Also, consider the following.
Your commit 90f98e621a7efdf0bd3faf3905a7055322d3f24a from Nov 20, 2017 has all the logic for skipping the tuning when initializing the child inputs but the code is not used/disabled due the "if" condition on kState_Error in line 142.
Commit 0c6fd96275f63b742d823c1ce0a37aca9990b828 from Nov 21, 2020 does fix this and effectively enables the code. This commit is only in master and not in v31 so only people running master actually have the benefits of the faster startup time.

So by reverting the second commit the startup behavior of v32 will be the same as of v31 and the regression in Live TV is avoided.

We could do the following:
- revert the second commit before the v32 cut
- reapply the second commit after the v32 cut
- 
This would keep master the way it is now, with faster start-up and with the Live TV regression.

What do you think?

The second issue that has surfaced when analyzing this problem is the switch from a StreamData to a DVBStreamData when there is a change from a "mpeg" channel to a "dvb" channel. Live TV has a listener to the StreamData and this listener does not hear anything anymore after a change to a new DVBStreamData instance.This can happen when there are "mpeg" and "dvb" channels in one Video Source and Live TV is started on a "mpeg" channel. Have to think about this a bit more.

**Comment by kmdewaal** [comment]
Thinking about this a bit more, the root cause can be considered that the tuning and the StreamData setup is based on what is the result of the previous tuning. It would be better to use the si_standard value from the database for the channel that is to be tuned. This makes the si_standard used independent of what is done or not at startup and hence is the best solution.

**Comment by gigem** [comment]
the check for kState_Error was definitely messed up by me.  I think I added that at the very end of that work and didn't test it properly.  Your fix should be kept.

I'm not familiar with the difference between mpeg and dvb channels.  It's not something that is possible over here in the States as far as I know.  You idea of using what is in the database instead of whatever was last used sounds reasonable.  I see you've already committed something for that.  Does it work?

**Comment by kmdewaal** [comment]
Commit  has been tested with a PCIe satellite card, with Sat>IP and with a HDHomeRun cable box.

**Comment by gigem** [comment]
Great.

**Comment by kmdewaal** [comment]
As mentioned in a previous comment:

> The second issue that has surfaced when analyzing this problem is the switch from a StreamData to a DVBStreamData when there is a change from a "mpeg" channel to a "dvb" channel. Live TV has a listener to the StreamData and this listener does not hear anything anymore after a change to a new DVBStreamData instance.This can happen when there are "mpeg" and "dvb" channels in one Video Source and Live TV is started on a "mpeg" channel. Have to think about this a bit more.

This problem does still exist and can be demonstrated by changing one multiplex from "dvb" to "mpeg" with an sql command and then starting Live TV on an mpeg channel and then a channel change to a dvb channel.
This is however not realistic; in a "DVB country" all channels that are relevant for MythTV are marked "dvb".
In MythTV for instance the IPTV channels are marked as "mpeg" but they are on a different video source.
Also, this problem has existed in MythTV for a very long time and nobody has ever noticed.
The main problem as described here was triggered by the mythbackend startup optimizations and that has now been fixed.
This ticket is now closed, but if the problem does reappear please re-open this issue or create a new issue.
