### ISSUE TITLE
gui application launcher fails unless --service removed

### ISSUE THREAD

**Issue by jfabernathy** [MythTV/mythtv#461]
* **Platform**:
Kubuntu 21.10
* **MythTV version**:
32
* **Package version**:
v32-Pre-3388-gd392ac9f16
* **Component**:
mythfrontend
### What steps will reproduce the bug?
in the multimedia apps category run mythfrontend. It fails to open. Seems to flash the icon in the task bar then goes away. I can run mythfrontend from a terminal. I edited the application in KDE and removed --service to fix it.

**Comment by rcrdnalor** [comment]
MythTV provides no launchers, neither for the frontend, nor for the backend.
It looks like, you have mythtv installed from Ubuntu or mythbuntu ppa installed.
Please post the "Package Version", i.e.: the output of

`dpkg -l |grep -i mythtv-frontend`

What does the following commands give?

`ls -la /usr/bin/mythfrontend`
`ls -la /usr/local/bin/mythfrontend`

Does this comment still make sense, is applicable for v32?
https://code.mythtv.org/trac/ticket/13221#comment:3

**Comment by jfabernathy** [comment]
Should I just close this?
