### ISSUE TITLE
Database update failed for EL7 (SL7.9) master. 

### ISSUE THREAD

**Issue by Jpilk** [MythTV/mythtv#468]
EL7 (SL7.9) x86_64

Old   mythtv-32.Pre.2788.g4d21b95e4f-100.el7.x86_64.rpm built 20210710
New mythtv-32.Pre.3464.g2c33d4c4f9-100.el7.x86_64.rpm built 20220124

Run mythtv-setup after update.  The DB is partially updated before it stops.  After reinstallation of the old packages I had to drop and restore from backup.

Reported this initially on the mythtv-dev list.  The main part of the failure report is below.

The old set of packages was my last build before the libzip resync incompatibility prevented installatiion
The new one was the first with gtb's compatibility upgrades. 
{{{
2022-01-24 15:58:50.777560 C  Upgrading to MythTV schema version 1371
2022-01-24 15:58:50.844346 E  DB Error (Performing MythtTV database upgrade):
Query was: CREATE TABLE sportsapi (
              id INT UNSIGNED PRIMARY KEY,
              provider TINYINT UNSIGNED DEFAULT 0,
              name VARCHAR(128) NOT NULL,
              key1 VARCHAR(256) NOT NULL,
              key2 VARCHAR(256) NOT NULL,
              UNIQUE(provider,key1,key2)
              );
Error was: Driver error was [2/1071]:
QMYSQL: Unable to execute query
Database error was:
Specified key was too long; max key length is 767 bytes 
}}}
Looks likely to be related to
https://github.com/MythTV/mythtv/commit/21bad111aa686ac5e083c409c97e4ba24252797d

**Comment by linuxdude42** [comment]
Fixed by commit 84a2beeaef on Jan 31.

**Comment by garybuhrmaster** [comment]
Somehow I missed this update.  This is not a proper fix, as documented in a post to the dev list.  I'll open the critical release blocker issue by the end of the weekend.
