### ISSUE TITLE
g754d740d00 makes LiveTV stuttering at start

### ISSUE THREAD

**Issue by warpme** [MythTV/mythtv#481]
* **Platform**:
n3450; x86_64/vaapi
H6/RK33xx/RK356x; aarch64 v4l2_request
RPi3/S912; aarch64 v4l2_m2m

* **MythTV version**:
master and 32/fixes

* **Package version**:

* **Component**:
LiveTV

### What steps will reproduce the bug?
Start LiveTV. 
Video starts with "lapsed movie like" video; audio is ok.
Sometimes - after 10..15 or more sec. - LiveTV becomes ok. 
Pause (even very short) restores LiveTV play to ok (smooth video + audio)
  

### How often does it reproduce? Is there a required condition?
always

### Additional information

bisecting shows:
872dad39a4407a77a5a9c0bfdfbf0d3bc4586fd7 - ok
5b448312ba2956176c2f081aeba48bfbf13d1a84 - ok
32420c58703bfc39dcf96c874c5bcc99e421e232 - ok
754d740d00455aaacbe7926520816dc72830b67e - nok

**Comment by gigem** [comment]
Klaas, I already know about the issue and am testing a fix.  Piotr, that commit is not actually the real cause, it just made ithe problem worse.  The real cause is much older.
