### ISSUE TITLE
Add ffmpeg patch for atomic detection

### ISSUE THREAD

**Issue by marillat** [MythTV/mythtv#499]
With some arches (armel or powerpc) ffmpeg doesn't detect atomic and thus the build fail.
A bug has been submitted
https://trac.ffmpeg.org/ticket/9275
and a patch is available here
http://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=2f0a214a6202516b4dda2bb22b6b3ac20e465d6d

Patch tested with ffmpeg 4.4.1 and mythtv 0.32 build under Debian unstable armel and powerpc arches.

**Comment by bennettpeter** [comment]
Is this fix needed in the version for Ubuntu 22.04?
