### ISSUE TITLE
Fails to build on Celeron with gcc-10.3

### ISSUE THREAD

**Issue by pcrow** [MythTV/mythtv#500]
When building from source on a Celeron CPU, at least with gcc-10.3, the build will fail complaining about lrint() being already defined.  The error is that the configure script is getting an illegal instruction when testing lrint(), and it boils down to the compiler using -march=haswell for my Haswell Celeron CPU, which enables AVX instructions even though AVX is disabled on Celeron and Pentium processors in that family.  Changing the configure scripts to use -march=native fixes this.

Presumably, if you just fixed the lrint issue, but kept using -march=haswell, the binary would fail with illegal instructions on Celeron systems.

I would argue that this is a gcc bug, but regardless, if the intention is to build for the processor doing the building (i.e., non-distribution builds), then why not use -march=native and be done with it?  That should take care of all the avx, sse, mmx, etc. settings.  You simply can't rely on the processor family alone to determine which instructions are available, as it is not the same across the entire family.

I'm running with gcc 10.3.1: gcc (Gentoo 10.3.1_p20211126 p0) 10.3.1 20211126

I haven't tried other compilers to see how widespread the issue is.

This is also a Gentoo bug report:
https://bugs.gentoo.org/791088

**Comment by ulmus-scott** [comment]
Which configure fails the lrint check?  i.e. what is `HAVE_LRINT` in mythtv/config.h and mythtv/external/FFmpeg/config.h?

Also, where does the build fail (MythTV or FFmpeg)?  What branch are you building?

**Comment by pcrow** [comment]
I'm building fixes/31.

We were actually just lucky that it was coming up with HAVE_LRINT being no, as it was setting -march=haswell for the full build, causing the use of invalid instructions.  The configure script must not set -march to to a processor family unless told to do so for cross compiling.

There are tons of details in the linked Gentoo bug report.

**Comment by ulmus-scott** [comment]
I can confirm on master `./configure --cpu=host` sets `-march=haswell` on my Pentium G3258, Xubuntu 21.10, with GCC 11.2.0.

This will generate illegal AVX instructions.

Running FFmpeg's `./configure --cpu=host` also sets `CFLAGS= -march=haswell`.

I would expect `-march=native`.

**Comment by linuxdude42** [comment]
pcrow: Did you get a change to test this?

**Comment by pcrow** [comment]
Yes, I just double-checked, and it works fine with the sources as linked two comments above.
