### ISSUE TITLE
Failed to download themes after V32 upgrade

### ISSUE THREAD

**Issue by jfabernathy** [MythTV/mythtv#502]
On a PC I had v31 mythfrontend only installed via the package mythtv-frontend from the PPA for ubuntu 21.10.

After changed the PPA to the v32 new release, I get an error when using Setup to change Themes. I get a popup error:

Failed to Download 'http://themes.mythtv.org/themes/repository/32/themes.zip'.  If I put that URL in a browser I get 404 Not Found.

**Comment by stuarta** [comment]
Should be resolved around 4:30pm GMT when the next theme build run occurs
