### ISSUE TITLE
Times longer than 1 day are not rendered (MythFormatTime returns empty string)

### ISSUE THREAD

**Issue by ijc** [MythTV/mythtv#520]
* **Platform**:

```
Linux iranon 5.16.0-3-amd64 #1 SMP PREEMPT Debian 5.16.11-1 (2022-02-25) x86_64 GNU/Linux
```

* **MythTV version**:

32

* **Package version**:

`1:32.0-dmo2`

* **Component**:

I noticed it in mythmusic with the blue-abstract-wide theme.

Possibly/probably anywhere which uses `MythFormatTime` and can see times > 24h will see it. Other than long mythmusic playlists I'm not aware of any cases (but I didn't hunt for them).

### What steps will reproduce the bug?

Create a playlist with more than 24h total music on it.

The display of how far you are through the playlist will omit the total time element of it.

e.g. after 1s of playtime it will say `0:00:01 / `

after > 24hrs of playtime it will just say ` / `.

### How often does it reproduce? Is there a required condition?

Deterministic

### What is the expected behaviour?

Prior to https://github.com/MythTV/mythtv/commit/c47ae6d443ddd2e305ee862e616e5ad0b0b46509 the hours field was allowed to exceed 23 hours. So you would see `0:00:01 / 324:45:12` or `310:12:54 / 324:45:12`.

### What do you see instead?

Either ` / ` or ` h::mm:ss / ` depending where you are in the list

**Comment by ijc** [comment]
I've got a patch with the (failing) test cases but haven't hacked up the actual change yet. 

My inclination is to reinstate the previous behaviour by moving `MythFormatTime` away from `QTime` internally. I can't see a class which deals in times >24hrs which isn't doing dates (which is not what we want here) so it may have to be the more manual way previously seen in `MusicCommon::getTimeString` before https://github.com/MythTV/mythtv/commit/c47ae6d443ddd2e305ee862e616e5ad0b0b46509.

The only other alternative I can think of is to do "dd:hh:mm:ss" (by pulling the days out first then using `QTime`) but that's a rather unconventional way of displaying such times I think.

**Comment by ijc** [comment]
`MythFormatTime` is `MythDate::formatTime` of course...

**Comment by linuxdude42** [comment]
I have a patch that will pull out the days and print something like "13 day(s), 12:45:12" but I haven't tested it yet.

**Comment by ulmus-scott** [comment]
I think it would be better to just use `std::chrono` (and not QTime) and have `MythDate::formatTime()` take a parameter for the maximum unit and minimum unit used, with an automatic option for choosing the smallest unit necessary.  This would allow hours > 23, minutes and seconds > 59, etc.

**Comment by ulmus-scott** [comment]
@linuxdude42 https://github.com/MythTV/mythtv/pull/521 is what I had in mind.

**Comment by ijc** [comment]
Thanks @linuxdude42 & @ulmus-scott , 2d7a09e40f55c13e203994aa4031f7de111fc97f + 65b9c73adacabe38877c3e18af5d4a0545799c16 + 19b0a7b2184a730f6e55c0cd2f41e26fb71ae2cf + 259a7fbe911da2ca229a513786172fcefeb8af07 altogether look good to me!

Do you plan to backport to fixes/32 once they've soaked for a bit?

**Comment by ijc** [comment]
@linuxdude42 when I asked Christian (DMO package maintainer) about a mythmusic bump he mentioned that 36c5630035864fa5d8efdaec8b0ef6c98067bc67 should likely have bumped `MYTH_BINARY_VERSION` in `mythtv/libs/libmythbase/mythversion.h`.

Perhaps 2d7a09e40f55c13e203994aa4031f7de111fc97f (the master original) should have too?
