### ISSUE TITLE
mythfrontend does not properly detect audio devices on macOS

### ISSUE THREAD

**Issue by acediac** [MythTV/mythtv#539]
* **Platform**: macOS Monterey 12.1

* **MythTV version**: v33 master

* **Package version**: 

* **Component**: mythfrontend CoreAudio devices

### What steps will reproduce the bug?

On macOS (Monterey 12.1), mythfrontend does not enumerate all the CoreAudio devices properly, and does not detect speaker systems with greater than 2 channels, ie for 5.1 Surround Sound systems.

### What do you see instead?

My system is using HDMI to a 5.1 dolby capable amplifier, and mythfrontend only shows it as 2 channel stereo.

### Additional information

I've actually spent some time and done some bugfixes for this issue including a memory corruption/leak, and it works for me now. The patchfile is enclosed (only 4 files changed, mostly audiooutputca.cpp). I just don't know what the protocol for submitting bug fixes is.

[0001-mythfrontend-audio-fixes-for-macOS.patch.zip](https://github.com/MythTV/mythtv/files/8428691/0001-mythfrontend-audio-fixes-for-macOS.patch.zip)

**Comment by linuxdude42** [comment]
You can submit a bug fix by opening a pull request. Click on "pull requests" at the top of this page, then click on "new pull request" near the top right of that page. If its easier for you, I can use the patch file you already sent, but I would like your email address to give you credit for it.

**Comment by linuxdude42** [comment]
Oh, and if you do decode to submit a pull request please remove the change to audiooutput.cpp.

**Comment by acediac** [comment]
Alright, I'll give it a try. Thanks.

**Comment by acediac** [comment]
With regard to audiooutput.cpp, the capabilities string is just a continuation of the details of the Device found (as evidenced by the closing bracket appended on line 385) so the newline on line 351 seems out of place and (it seems to me) breaks the log output in a conspicuously unusual way as all other log entries are on one line. However I will defer to your judgement and it only shows up when audio is logged anyway.

**Comment by linuxdude42** [comment]
Its also used in "Setup -> Audio -> Audio Output Device". When you choose a new audio output device this is the string displayed in the message box at the bottom of the screen. It probably should also be shown when you first enter that dialog, but that's a different issue.

**Comment by acediac** [comment]
Ah ok, I did notice the text only appears when you select a new device and not for an already selected one.
