### ISSUE TITLE
cancel = cancel all when reviewing added channels?

### ISSUE THREAD

**Issue by RossBoylan** [MythTV/mythtv#552]
* **Platform**:
* `Linux barley 4.19.0-20-amd64 #1 SMP Debian 4.19.235-1 (2022-03-17) x86_64 GNU/Linux`
* Debian 10

* **MythTV version**:
```
$ mythtv-setup --version
Please attach all output as a file in bug reports.
MythTV Version : v30.0-82-g541f52c2e4-dirty
MythTV Branch : rb02
Network Protocol : 91
Library API : 30.20181231-1
QT Version : 5.11.3
Options compiled in:
 linux profile use_hidesyms using_alsa using_jack using_oss using_pulse using_pulseoutput using_backend using_bindings_perl using_bindings_python using_bindings_php using_dvb using_firewire using_frontend using_hdhomerun using_vbox using_ceton using_hdpvr using_ivtv using_joystick_menu using_libcec using_libcrypto using_libdns_sd using_libfftw3 using_libxml2 using_lirc using_mheg using_opengl using_opengl_video using_opengl_themepainter using_qtwebkit using_qtscript using_qtdbus using_taglib using_v4l2 using_x11 using_xnvctrl using_xnvctrl_external using_libbluray_external using_xrandr using_xv using_profiletype using_bindings_perl using_bindings_python using_bindings_php using_freetype2 using_mythtranscode using_opengl using_vaapi using_vaapi2 using_vdpau using_ffmpeg_threads using_mheg using_libass using_libxml2 using_libmp3lame
```

* **Package version**:
mythtv-backend 30.0-dmo4-rb02 amd64 

Basically from Marillat's repo, but I backported some code so I could use the Python3 interface.

* **Component**:
* channel scanner
* mythtv-setup

### What steps will reproduce the bug?

* stop the backend
* this assumes channels were previously scanned and some were deleted
* run mythtv-setup (as user mythtv)
* select channel editor
* do a channel scan over the air
* popups appear about channels added/deleted/changed
* the channels added asks if you want to ignore, accept, or process the new channels manually.  Choose the latter.
* a box pops up with the first added channel.  Choices include add, edit, ignore (?), cancel, or cancel all.  Since there was no delete option, I picked cancel.  I didn't get asked about any other channels to add, which is what I thought cancel all would do.  Setup proceeded to the next category.

This is from memory.

### How often does it reproduce? Is there a required condition?

I think it has happened the few times I have tried it.  As noted, there are quite a few required conditions to produce the problem.

### What is the expected behaviour?

First, it would be nice if I simply got a grid with checkboxes for all the added channels, so that I could quickly indicate which ones to keep.  There were 80, and I only wanted a handful.  So processing them one at a time would have been painful.

Second, I would expect the buttons to have names that correspond to the immediate task, which is to either add the channel or not.  I assumed "cancel" meant "do not add" because it was the closest thing available.  "delete" would have been meaningful to me, though perhaps it wasn't chosen because you can't delete what isn't already on the channel list.

Third, narrowly the problem is that "cancel" cancelled all additions, not just the current channel that was being displayed.

### Additional information

I found the whole process of managing channels through the GUI baffling and tedious, even after consulting the documentation.  Focusing just on the channel scan, it wasn't clear to me what the different categories of results were (though in retrospect I guess it was channels added, deleted, and changed between the previous scan and this one), or what the implications of different choices were.

I had originally scanned the channels, accepting all, and then manually deleted the ones I didn't want through a later step in the channel editor.

Since "cancel" wasn't working to make  selective additions, I simply accepted everything.
This time I reviewed the code in mythtv-setup to see what deleting a channel did, leading to routines in the myth library that simply deleted entries from the channel table.  Then I wrote some sql to do the mass deletion I wanted.

**Comment by kmdewaal** [comment]
Channel scanning has been improved a lot since version 30, I suggest to upgrade to fixes/32.
The behavior when adding channels in fixes/32 is now as you would expect, with "cancel" cancelling only adding that channel and "cancel all" cancelling adding all remaining channels.

There is documentation in the Wiki in https://www.mythtv.org/wiki/Channel_Scanning although this does not describe this particular dialog.

About having a nice GUI.. There is work-in-progress in making a web-based GUI to handle all of this but there is still a  lot to be done and volunteers to help are very welcome! 

As the current behavior of fixes/32 and master is correct and fixes/30 will not be updated this ticket is now closed. 
Please re-open this ticket or create a new ticket if you find inconsistencies, irregularities, unexpected behavior or even plain errors in the channel scanner of fixes/32.

**Comment by RossBoylan** [comment]
Thanks for the info.  Glad it's fixed.
