### ISSUE TITLE
Invalid Content-Length in GetFile response when file length > 2GB

### ISSUE THREAD

**Issue by AndyJRobinson** [MythTV/mythtv#555]
* **Platform**: Linux mythtv 5.4.0-109-generic 123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* **MythTV version**: fixes/32

* **Package version**: Mythbuntu 2:32.0+fixes.202204250633.daa4e7e447~ubuntu20.04.1
* **Component**: mythbackend

### What steps will reproduce the bug?
curl -i --head 'http://192.168.218.162:6744/Content/GetFile?StorageGroup=Default&FileName=/1041_20220427003000.ts' -H 'Range: bytes=0-' --ignore-content-length

HTTP/1.1 206 Partial Content
Date: Sat, 07 May 2022 00:11:33 GMT
Server: MythTV/32.0+fixes.202204250633.daa4e7e447~ubuntu20.04.1 Linux/5.4.0-109-generic UPnP/1.0
Accept-Ranges: bytes
Connection: Keep-Alive
Keep-Alive: timeout=10
Content-Type: video/mp2t
Content-Range: bytes 0-2164624103/2164624104
Content-Length: **-2130343192**
Cache-Control: no-cache="Ext",max-age=31536000
Last-Modified: Wed, 27 Apr 2022 01:00:00 GMT

### How often does it reproduce? Is there a required condition?

File length > 2GB

### What is the expected behaviour?

Correct Content-Length is in the response

### What do you see instead?

The Content-Length header contains a negative value

**Comment by Jpilk** [comment]
I see this too, in master, using port 6744.  It looks ok at 6544.

**Comment by bennettpeter** [comment]
The following line causes the problem. All of the fields used are unit64_t. However at the end of this the result is truncated to a 32 bit value. I do not know why. The std::accumulate method seems to be truncating.

https://github.com/MythTV/mythtv/blob/969235ed8abea04a3a39607bf6b699c743394bc5/mythtv/libs/libmythbase/http/mythhttpranges.cpp#L284

My solution is to replace that line with this
```
    PartialSize = 0;
    for (HTTPRange r : ranges)
    {
        PartialSize += r.second + 1 - r.first;
    }

```
Unless somebody knows how to wrangle the std::accumulate to stop truncating, I will implement this.

Possibly it is the sumrange lambda that is at fault. I would therefore change the other place where sumrange is used, and remove sumrange.

https://github.com/MythTV/mythtv/blob/969235ed8abea04a3a39607bf6b699c743394bc5/mythtv/libs/libmythbase/http/mythhttpranges.cpp#L105

Change to this

`        uint64_t newsum = oldsum + range.second + 1 - range.first;`

Please let me know of any suggestions, objections, etc.

**Comment by kmdewaal** [comment]
On Sat, 7 May 2022 at 22:13, Peter Bennett ***@***.***> wrote:

> The following line causes the problem. All of the fields used are
> unit64_t. However at the end of this the result is truncated to a 32 bit
> value. I do not know why. The std::accumulate method seems to be truncating.
>
>
> https://github.com/MythTV/mythtv/blob/969235ed8abea04a3a39607bf6b699c743394bc5/mythtv/libs/libmythbase/http/mythhttpranges.cpp#L284
>
> My solution is to replace that line with this
>
>     PartialSize = 0;
>     for (HTTPRange r : ranges)
>     {
>         PartialSize += r.second + 1 - r.first;
>     }
>
>
> Unless somebody knows how to wrangle the std::accumulate to stop
> truncating, I will implement this.
>
> Possibly it is the sumrange lambda that is at fault. I would therefore
> change the other place where sumrange is used, and remove sumrange.
>
>
> https://github.com/MythTV/mythtv/blob/969235ed8abea04a3a39607bf6b699c743394bc5/mythtv/libs/libmythbase/http/mythhttpranges.cpp#L105
>
> Change to this
>
> uint64_t newsum = oldsum + range.second + 1 - range.first;
>
> Please let me know of any suggestions, objections, etc.
>
> —
>
> According to Visual Code the type of "auto sumrange" as defined on 10 is
shown as "unsigned long".
Maybe declaring it as uint64_t instead of auto is enough to fix this.

Klaas.

**Comment by garybuhrmaster** [comment]
On Sat, May 7, 2022, 16:13 Peter Bennett ***@***.***> wrote:

> Unless somebody knows how to wrangle the std::accumulate to stop
> truncating, I will implement this.
>

The 3rd parm defines the type.  0 is an int.  Coerce it to be int64.  (All
theory until tested, of course).

>

**Comment by bennettpeter** [comment]
> On Sat, May 7, 2022, 16:13 Peter Bennett ***@***.***> wrote: Unless somebody knows how to wrangle the std::accumulate to stop truncating, I will implement this.
> The 3rd parm defines the type. 0 is an int. Coerce it to be int64. (All theory until tested, of course).
> […](#)

Thank you Gary, that did the trick. I will implement that simple change.

**Comment by kmdewaal** [comment]
On Sat, 7 May 2022 at 22:21, klaas de waal ***@***.***> wrote:

>
>
> On Sat, 7 May 2022 at 22:13, Peter Bennett ***@***.***>
> wrote:
>
>> The following line causes the problem. All of the fields used are
>> unit64_t. However at the end of this the result is truncated to a 32 bit
>> value. I do not know why. The std::accumulate method seems to be truncating.
>>
>>
>> https://github.com/MythTV/mythtv/blob/969235ed8abea04a3a39607bf6b699c743394bc5/mythtv/libs/libmythbase/http/mythhttpranges.cpp#L284
>>
>> My solution is to replace that line with this
>>
>>     PartialSize = 0;
>>     for (HTTPRange r : ranges)
>>     {
>>         PartialSize += r.second + 1 - r.first;
>>     }
>>
>>
>> Unless somebody knows how to wrangle the std::accumulate to stop
>> truncating, I will implement this.
>>
>> Possibly it is the sumrange lambda that is at fault. I would therefore
>> change the other place where sumrange is used, and remove sumrange.
>>
>>
>> https://github.com/MythTV/mythtv/blob/969235ed8abea04a3a39607bf6b699c743394bc5/mythtv/libs/libmythbase/http/mythhttpranges.cpp#L105
>>
>> Change to this
>>
>> uint64_t newsum = oldsum + range.second + 1 - range.first;
>>
>> Please let me know of any suggestions, objections, etc.
>>
>> —
>>
>> According to Visual Code the type of "auto sumrange" as defined on 10 is
> shown as "unsigned long".
> Maybe declaring it as uint64_t instead of auto is enough to fix this.
>
>
Please ignore this remark. It turns out that an unsigned long is nowadays
64 bits....

Klaas.
