### ISSUE TITLE
Release Date Delivered by tmdb3.py

### ISSUE THREAD

**Issue by johnlatz** [MythTV/mythtv#572]
* **MythTV version**:  0.31/0.32

* **Package version**:  tmdb3.py

* **Component**:tmdb3.py

### What steps will reproduce the bug?
[ 1 ]  /usr/share/mythtv/metadata/Movie/tmdb3.py -D 414906  --debug    
[ 2 ]  /usr/share/mythtv/metadata/Movie/tmdb3.py -D 414906 -a US --debug

Result of [ 1 ]:  <releasedate>2022-04-17</releasedate>
Result of [ 2 ]:  <releasedate>2022-04-23</releasedate>

Expected Result:  <releasedate>2022-03-01</releasedate>  or  <releasedate>2022-03-04</releasedate>  

Note - using the " --debug " option shows the following lines in the original source data:

...
'release_date': '2022-03-01',
...
               {'certification': 'PG-13',
                'iso_3166_1': 'US',
                'primary': False,
                'release_date': '2022-03-04'},

What I very much do not understand is where April 17th is selected - as that date is embedded in the original source data as the release date for Brazil 

How can I force tmdb3.py to select the certification date for the US, if not using the " -a US " option?
[the_batman.txt](https://github.com/MythTV/mythtv/files/8789412/the_batman.txt)
[the_batman_us.txt](https://github.com/MythTV/mythtv/files/8789413/the_batman_us.txt)

**Comment by rcrdnalor** [comment]
The most important information is missing: the `locale` setting of your terminal where you run [1] and [2].

I cannot remember that MythTV is using tmdb3.py without the language setting `-l`.
Where have you seen such command? MythWeb, MythTV Python Bindings, Mythbackend? Mythfrontend?
How does this failure impact MythTV?

The python bindings to themoviedb.org are now maintained by [opacam](https://github.com/opacam/python3-tmdb3).
You should ask questions like this directly to the maintainer. 

Please note: This is the bug tracker for MythTV, not supposed to provide support. MythTV has an excellent support forum (https://forum.mythtv.org/) and  a mailing list (http://lists.mythtv.org/mailman/listinfo/mythtv-users/) where you can ask for questions related to MythTV .

**Comment by rcrdnalor** [comment]
The wrong value of the first command may be related to
a `ToDo` comment in the source code [tmdb3/lookup.py#80](https://github.com/MythTV/mythtv/blob/master/mythtv/bindings/python/tmdb3/tmdb3/lookup.py#L80)

In other words, it needs to be implemented.
A pull request (including tests) is welcomed.

Using locale setting `LANG=en_US.UTF-8`, the second command
/usr/share/mythtv/metadata/Movie/tmdb3.py -D 414906 -a US --debug
returned ambigous values for the release dates:
```
{'certification': 'PG-13',
'iso_3166_1': 'US',
'primary': False,
'release_date': '2022-03-02'},
{'certification': 'PG-13',
'iso_3166_1': 'US',
'primary': False,
'release_date': '2022-03-04'},
{'certification': 'PG-13',
'iso_3166_1': 'US',
'primary': False,
'release_date': '2022-04-18'},
{'certification': 'PG-13',
'iso_3166_1': 'US',
'primary': False,
'release_date': '2022-05-24'},
{'certification': 'PG-13',
'iso_3166_1': 'US',
'primary': False,
'release_date': '2022-04-23'}],
```
tmdb3.py takes the last one as valid:
```
<releasedate>2022-04-23</releasedate>
```

Again, a tested patch is welcomed to get the latest certification.

Out of curiosity, what is your impact on receiving wrong release dates ?

**Comment by johnlatz** [comment]
Unfortunately, my coding skills topped out at FORTRAN77 and C - I’m as proficient in Swahili as I am in Python.  I am still orienting myself to the concept that “pull” is viewed from the repository (code is uploaded) not form the viewpoint of the submitter (pulling the codebase down to local disk).

As for the implications to my MythTV experience - does not preclude the operation of the software in the slightest.  It is one of those mildly OCD responses to my downloaded videometadata of “but it’s not right, dammit”…

So I thought I would make y’all aware of it.  Absolutely a minor nit, but still thought I’d mention it.

John

**Comment by rcrdnalor** [comment]
I pushed 6c3260c to master that should fix this issue.
Needs extensive testing.

**Comment by johnlatz** [comment]
Thank you all - your dedication is appreciated

John

**Comment by rcrdnalor** [comment]
I pushed 1544bc2 to fixes/32, closing that issue.
Please fee free to re-open it or crate a new one if this does not fix your expectations.
