### ISSUE TITLE
MythCenter-wide theme -- recording date and time not correctly formatted

### ISSUE THREAD

**Issue by daveu8282** [MythTV/mythtv#578]
* **Platform**:  Fedora Linux 35

* **MythTV version**: fixes/31 (v32.0-v32.0-30-g26079f815a)

* **Package version**: rpmfusion/mythtv-base-themes-32.0-1.30.20220510git26079f815a.fc35.x86_64

* **Component**: frontend

### What steps will reproduce the bug?
1. Switch to MythCenter-wide theme using Setup / Theme Chooser
2. Verify that a 12-hour (USA style) time format is selected using Setup / Appearance / Localization.
3. Visit Media Library / Watch Recordings.
4. In the upper-right pane where the episodes are listed, the date and time will be incorrectly formatted when the hour is two digits wide.

Instead of 6/2 10:00 AM it reads 6/2 10 ...
Instead of 6/2 10:00 PM it reads 6/210:00 PM

Date and time when the hour is one digit are formatted correctly:

6/2 9:00 AM
6/2 9:00 PM

Note that the similar MythCenter theme is not affected by this issue. With that theme, dates and times are always formatted correctly.

### How often does it reproduce? Is there a required condition?

It always occurs if the MythCenter-wide theme is in effect.

### What is the expected behaviour?

Dates and times should be consistently formatted.

Correctly formatted date and times:

6/2 10:00 AM
6/2 10:00 PM

### What do you see instead?

6/2 10 ...
6/210:00 PM

**Comment by kmdewaal** [comment]
The "watched percentage" and "recorded percentage" feature in version 32 does need a bit of screen space.
Part of the space for the percentage was found by reducing the size of the start time field.
Unfortunately, what needs to be displayed in the start time field is just as big as it was, causing the problem described here.
The solution is to make the title field shorter, move the percentage and date fields to the left and increase the size of the start time field.

**Comment by kmdewaal** [comment]
Problem is solved, closing this ticket.
