### ISSUE TITLE
Time format messed up on LCD

### ISSUE THREAD

**Issue by Mark-Clegg** [MythTV/mythtv#579]
* **Platform**: AMD64
* Linux nostromo 5.18.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 30 May 2022 17:53:11 +0000 x86_64 GNU/Linux

* **MythTV version**: 32/fixes

* **Package version**: Arch linux AUR package

* **Component**: mythlcdserver

### What steps will reproduce the bug?

Start myth, observe time on LCD display

On the LCD the time is alternatly displayed as "hh:mm" and "hhmm",

### How often does it reproduce? Is there a required condition?

always

### What is the expected behaviour?

time should alternate between "hh:mm"  and "hh mm" (note the space replacing the colon) to give the illusion of a blinking colon.

### Additional information

suggested fix:
```
--- package.orig/mythtv/mythtv/programs/mythlcdserver/lcdprocclient.cpp 2022-06-04 15:30:09.000000000 +0100
+++ package.new/mythtv/mythtv/programs/mythlcdserver/lcdprocclient.cpp  2022-06-04 15:33:30.591887745 +0100
@@ -1891,7 +1891,7 @@
         aString += time + "\"";
         if ( m_timeFlash )
         {
-            aString = aString.remove(":");
+            aString = aString.replace(':',' ');
             m_timeFlash = false;
         }
         else
```

**Comment by twitham1** [comment]
Yes, I got this odd moving time on the LCD at v32 upgrade.   Appears to be from 2bc6c314c2f6 and your fix here should work well.
