### ISSUE TITLE
The buffer of the job export parameters is too small

### ISSUE THREAD

**Issue by rolle5** [MythTV/mythtv#580]
* **Platform**:
Desktop PC, 64 Bit, Ubuntu 22.04LTS

* **MythTV version**:
ppa:mythbuntu/32

* **Package version**:
v32.0+fixes.202206011303.8347647e42~ubuntu20.04.1

* **Component**:
MythTV

### What steps will reproduce the bug?

I use the job export parameter for external batch scripts. Sometimes the description of a record is very long. I have now for the second time the situation that the long description is cut off. Maybe it is due to a fixed maximum buffer size. So I suggest to double the size of the description export buffer or do a dynamic buffer allocation.

### How often does it reproduce? Is there a required condition?
always

### What is the expected behaviour?
create a valid video file

### What do you see instead?
a corrupted video file or a null byte video file

**Comment by rolle5** [comment]
Yes, I originally meant that a very long text string in the DESCRIPTION is truncated during parameter transfer to a shell script.

But now I have new knowledge. That the text string in the DESCRIPTION was apparently not truncated because of the large length, but because of quotes. I have now removed the quotation marks in the "Edit metadata" on a trial basis and then transferred them via "Running a job" using the parameters and the length was no longer a problem.
I think the original intention of this bug report is no longer given and this bug report can be closed. For the problem with the quotes I may have to open a new bug report.

**Comment by linuxdude42** [comment]
Closed as per your request.

**Comment by billmeek** [comment]
@rolle5, I changed the way quotes are handled in master. I've got it on my calendar to  push to v32 next week.
dd68df467
