### ISSUE TITLE
Recording info, the year of the "recording timestamp" is doubled

### ISSUE THREAD

**Issue by rolle5** [MythTV/mythtv#582]
* **Platform**:
Desktop PC, 64 bit, Ubuntu 22.04 LTS

* **MythTV version**:
ppa:mythbuntu/32

* **Package version**:
v32.0+fixes.202206011303.8347647e42~ubuntu20.04.1

* **Component**:
MythTV (frontend?)

### What steps will reproduce the bug?
It must exist recordings from the current year and the last year.

In the recording info, the year of the "recording timestamp" is doubled if it is not the current year. So now for all recordings from 2022 on, the timestamp is correct. But for older recordings from last year, the year of the recording timestamp is doubled.

The (German) format in the current year 2022 is correct:
So. 27 Feb. 2022, 01:35

For a recording from last year 2021, the (German) format is incorrect (year 2021 doubled):
Di. 16 Feb. 2021 2021, 05:05

### How often does it reproduce? Is there a required condition?
always

### What is the expected behaviour?
The recording info of recordings of last year(s) should show the year only once.

### What do you see instead?
recordings from the last year show a doubled year

**Comment by rolle5** [comment]
> What do you have the Date format setting set to in Setting -> Appearence -> Localisation ?

I have selected german localisation everythere.
- Date format (Datumsformat):                      Mo. 6 Juni 2022
- Short date format (Kurzes Datumsformat): 06.06. (day.month.)

**Comment by Jpilk** [comment]
I have:  
 
Wed 8 Jun 2022
Wed 08.06
09:15

and see on that line, for example,

50 GREAT! movies christ       18:48 - 21:04 Wed 23 Jun 2021 c10050 r34837              1.02 GB
