### ISSUE TITLE
cannot find taglib 1.11.1 or later (found 1.10) -- but I just built 1.12...?

### ISSUE THREAD

**Issue by IngwiePhoenix** [MythTV/mythtv#587]
* **Platform**:
* Host: Debian 11 @ WSL2
* Target: WebOS 6.2.4 @ LG OLED TV (C1) via WebOSBrew/OpenLGTV toolchain (provided TC is a modified of the OSS release with additional stubs/APIs)

* **MythTV version**:
* Git says: `v33-Pre-433-gdd68df4676`

* **Package version**: Git

* **Component**: MythTV

### What steps will reproduce the bug?

- Install [the WebOSBrew toolchain](https://github.com/webosbrew/meta-lg-webos-ndk)
- Build a static Qt 5.12.12
  * Create/add [this mkspec](https://gist.github.com/IngwiePhoenix/23e65eb879e71f48397613450ade0d59) in `qt5/qtbase/mkspecs/webos-aarch64-gnu-g++`
  * Configure && build + install: `../qt-everywhere-src-5.12.12/configure -opensource -confirm-license -static -optimize-size -strip -xplatform webos-aarch64-gnu-g++ -sysroot /opt/webos-sdk-x86_64/1.0.g/sysroots/armv7a-neon-webos-linux-gnueabi/ -gcc-sysroot -no-eglfs -nomake examples -nomake tests -make libs -prefix /opt/qt5.12.12/ && gmake install`
- Build taglib from Github
  * Configure: `cmake -G Ninja .. -DCMAKE_INSTALL_PREFIX=/opt/webos-sdk-x86_64/1.0.g/extra/`
- Configure MythTV: `env PATH="/opt/webos-sdk-x86_64/1.0.g/sysroots/armv7a-neon-webos-linux-gnueabi/opt/qt5.12.12/bin/:$PATH" CFLAGS="-I/opt/webos-sdk-x86_64/1.0.g/sysroots/armv7a-neon-webos-linux-gnueabi/opt/qt5.12.12/include -I /opt/webos-sdk-x86_64/1.0.g/extra/include $CFLAGS" LDFLAGS="-L/opt/webos-sdk-x86_64/1.0.g/sysroots/armv7a-neon-webos-linux-gnueabi/opt/qt5.12.12/lib -L/opt/webos-sdk-x86_64/1.0.g/extra/lib $LDFLAGS"  CXXFLAGS="-I/opt/webos-sdk-x86_64/1.0.g/sysroots/armv7a-neon-webos-linux-gnueabi/opt/qt5.12.12/include -I /opt/webos-sdk-x86_64/1.0.g/extra/include $CXXFLAGS" ./configure --enable-cross-compile --cc="$CC" --cxx="$CXX" --ld="$CC" --arch=armv7-a --target-os=linux --sysroot=/opt/webos-sdk-x86_64/1.0.g/sysroots/armv7a-neon-webos-linux-gnueabi/ --prefix=/opt/webos-sdk-x86_64/1.0.g/extra/`

The variables used evaluate to this:
```
CC = arm-webos-linux-gnueabi-gcc  -march=armv7-a -mfpu=neon  -mfloat-abi=softfp --sysroot=/opt/webos-sdk-x86_64/1.0.g/sysroots/armv7a-neon-webos-linux-gnueabi
CXX = arm-webos-linux-gnueabi-g++  -march=armv7-a -mfpu=neon  -mfloat-abi=softfp --sysroot=/opt/webos-sdk-x86_64/1.0.g/sysroots/armv7a-neon-webos-linux-gnueabi
CFLAGS =  -O2 -pipe -g -feliminate-unused-debug-types
CXXFLAGS =  -O2 -pipe -g -feliminate-unused-debug-types
LDFLAGS = -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed
```

### How often does it reproduce? Is there a required condition?
Always.

### What is the expected behaviour?
That the configure script passes configuration

### What do you see instead?
That my taglib is outdated; which can not be true as I literally just built and included the folders neccessary. However, I also do not see anything related to this in the configure output.

See [configure.ep](https://gist.github.com/IngwiePhoenix/fe2c9e80e363cb2829d8d7616bb5052f)

### Additional information
I literally spent two days to compile Qt so I could have MythTV find a suitable version of Qt after both TVHeadend and Kodi/XMBC gave me massive headaches. I am so tired xD. Something tells me that the issue is actually not taglib, but something else. But, as the configure script produces no output except the `configure.ep` file, I have no way of telling where it *actually* stops. In fact, I expect it to fail on the MySQL driver not actually being there.

I am not sure if I want to run just the frontend or also the backend on my TV. For now, I just want to see how far I can actually get this compiled. Although this is technically an embedded system, it runs the full GNU/Linux base - so... it should work. Technically.

Hopefuly someone of you has an idea, because my head is spinning in confusion now. ^^;

Thank you very much and kind regards,
Ingwie

**Comment by linuxdude42** [comment]
The MythTV configure script is running the command "pkg-config --modversion taglib" to get the version number of the taglib library, but it isn't finding the taglib.pc file installed by your build of taglib.  I think that setting PKG_CONFIG_PATH=/opt/webos-sdk-x86_64/1.0.g/extra/lib/pkgconfig should fix the problem.

**Comment by IngwiePhoenix** [comment]
That did sort of fix it...

```
ingwie@bigboi:/opt/mythtv/mythtv$ env PKG_CONFIG_PATH="/opt/webos-sdk-x86_64/1.0.g/extra/lib/pkgconfig:$PKG_CONFIG_PATH" PATH="/opt/webos-sdk-x86_64/1.0.g/sysroots/armv7a-neon-webos-linux-gnueabi/opt/qt5.12.12/bin/:$PATH" CFLAGS="-I/opt/webos-sdk-x86_64/1.0.g/sysroots/armv7a-neon-webos-linux-gnueabi/opt/qt5.12.12/include -I /opt/webos-sdk-x86_64/1.0.g/extra/include $CFLAGS" LDFLAGS="-L/opt/webos-sdk-x86_64/1.0.g/sysroots/armv7a-neon-webos-linux-gnueabi/opt/qt5.12.12/lib -L/opt/webos-sdk-x86_64/1.0.g/extra/lib $LDFLAGS" CXXFLAGS="-I/opt/webos-sdk-x86_64/1.0.g/sysroots/armv7a-neon-webos-linux-gnueabi/opt/qt5.12.12/include -I /opt/webos-sdk-x86_64/1.0.g/extra/include $CXXFLAGS" ./configure --enable-cross-compile --cc="$CC" --cxx="$CXX" --ld="$CC" --arch=armv7-a --target-os=linux --sysroot=/opt/webos-sdk-x86_64/1.0.g/sysroots/armv7a-neon-webos-linux-gnueabi/ --prefix=/opt/webos-sdk-x86_64/1.0.g/extra/
ERROR: cannot find taglib 1.11.1 or later (found 1.12).

If you think configure made a mistake, make sure that you are using the latest
version of MythTV from git.  If the latest version fails, report the problem to the
mythtv-dev@mythtv.org mailing list or IRC #mythtv on irc.libera.chat
Include the log file "config.ep" produced by configure as this will help
solve the problem.
```

Would've thought using the latest version would suffice, guess I'll downgrade the taglib then. But, the root problem is indeed fixed now. Thanks!

Closing this for now though as the root issue is fixed.

**Comment by linuxdude42** [comment]
Line 5871 of configure has this subsequent test:

```check_class_headers_cpp "taglib/fileref.h stdlib.h" TagLib::FileRef $tagincludes $taglibs -lstdc++```

This is probably failing to compile and link, which is what is causing the new error.

**Comment by IngwiePhoenix** [comment]
Turns out it had undefined references to `log10`; so I added `-lm` to `LDFLAGS`. Problem solved. Now I can work on the other deps - and there are a good lot of them that I need to fix... (Well, compile and install, really.)

Thanks for the help!

**Comment by IngwiePhoenix** [comment]
Configure finally passed - all problems solved.

Thanks for your help!

**Comment by IngwiePhoenix** [comment]
Welp, that adventure came to a crashing end:

```
el_processor.cpp:189:58: error: ‘clamp’ is not a member of ‘std’
     static inline float clamp_unit_mag(float x) { return std::clamp(x, -1.0F, 1.0F); }
                                                          ^~~
el_processor.cpp: In member function ‘void fsurround_decoder::Impl::block_decode(InputBufs, InputBufs, OutputBufs, float, float, float)’:
el_processor.cpp:313:46: error: ‘clamp’ is not a member of ‘std’
                     back * m_surroundLevel * std::clamp( (1.0F - (m_xFs[f] / m_surroundBalance) ) / 2.0F, 0.0F, 1.0F),// left surround
                                              ^~~
el_processor.cpp:314:46: error: ‘clamp’ is not a member of ‘std’
                     back * m_surroundLevel * std::clamp( (1.0F + (m_xFs[f] / m_surroundBalance) ) / 2.0F, 0.0F, 1.0F) // right surround
                                              ^~~
```

The toolchain uses GCC 6.2.0, which only has C++ 14 as far as I am aware. That's unfortunate. Oh well, at least I learned a lot!
