### ISSUE TITLE
Replace UDisks with UDisks2 for media handling

### ISSUE THREAD

**Issue by rcrdnalor** [MythTV/mythtv#605]
* **Platform**: Ubuntu 22.04, Ubuntu 20.04, Ubuntu 18.04

* **MythTV version**: mythtv master and fixes/32

* **Package version**: N/A

* **Component**: MediaMonitor

UDisks is long time deprecated and not available in modern Linux distributions anymore.
It was replaced by UDisks2 which is now provided by the storaged.org project and linked from freedesktop.org.
See https://udisks.freedesktop.org/
This is the continuation of the bug raised at the old trac issue tracker at https://code.mythtv.org/trac/ticket/12307 .

**Comment by warpme** [comment]
@rcrdnalor 

This is great improvement!
Many thx for working on this!

For me it means we finally may address things like: https://code.mythtv.org/trac/changeset/e5b664a242b2b03a40c2a0fce07d69f385238d97/mythtv
Or maybe functionality like above is already available? (i not tested yet udisks2 as now i'm working to get current udsisk2 on cross-compiled env without object-introspection (which is _real pain_ to crocs-compile))

If not - i have working MVP hack for udisks1 in my distro:
https://github.com/warpme/minimyth2/blob/master/script/myth-master/mythtv/files/0204-Mediamonitor-add-UI-to-select-preferred-media-handler.patch
This is _dirty hack_ code - so it will be great to implement this properly in current master....
(btw: iirc code still requires QT5_MIN_VERSION_STR="4.8" to get compiling)

**Comment by linuxdude42** [comment]
Can this issue be closed?

**Comment by warpme** [comment]
David
I think no as my comment/request is about functional enhancement.
Patch https://github.com/warpme/minimyth2/blob/master/script/myth-master/mythtv/files/0204-Mediamonitor-add-UI-to-select-preferred-media-handler.patch current offers kind of MVP of following functionality:
1. user inserts CDaudio/DVD/CDmp3/CDimages/DVD/Bluray
2. MythTV pop-ups dialog with selection of all relevant play/listen capabilities (e.g. CDdata with mp3 + band images)
3. user selects what user wants to do (e.g. play mp3 in MythMusic or watch images in MythGallery)
4. pressing enter on selection launches desired action (e.g. starts MythMusic)
I think you may ty to apply above patch on current master to see how it works.
I described here exemplary implementation of given use-case. Maybe you will have better idea how to nicelly handle multi-type media)?

(in past this request was refused due devs not want to add extra user functionalities relying on system outdated/need-to-replace udisks1 system component. Now this argument disappearing as we have alive udisks2...)

**Comment by rcrdnalor** [comment]
@warpme 
About functional enhancements, please see
https://github.com/MythTV/mythtv/pull/606#issuecomment-1192893691 and 
https://github.com/MythTV/mythtv/pull/606#issuecomment-1192914800
In other words, this is beyond this issue/pullrequest, please open an issue and reference your desired  behavior.

@linuxdude42 
Yes, this issue can can be closed, becaue some enhancements have been additionally committed at https://github.com/MythTV/mythtv/pull/735
