### ISSUE TITLE
Mythburn.py error while processing streaminfo.xml

### ISSUE THREAD

**Issue by bshanteau** [MythTV/mythtv#609]
* **Platform**:
`Linux dvr 5.15.0-41-generic #44~20.04.1-Ubuntu SMP Fri Jun 24 13:27:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

* **MythTV version**:
MythFrontend Version fixes/32 (v32.0+fixes.202207162302.365406638a~ubuntu20.04.01)

* **Package version**:
PPA: mythbuntu/32

* **Component**:
mythburn.py

### What steps will reproduce the bug?
MythFrontend->Utilities->Archive Files->Create DVD ->Select Destination: File: Make ISO Image->DVD Menu Theme: Simple-Autoplay->Select Archive Items: Add File-->Select short mp4 recording->Next

### How often does it reproduce? Is there a required condition?
Every time. No apparent required condition.

### What is the expected behaviour?
Create iso file

### What do you see instead?
mythburn.log:
Using simple_fix_rtl
mythburn.py (0.2.20200122-1) starting up...
script path:/usr/share/mythtv/mytharchive/scripts
myth share path:/usr/share/mythtv
passed job file: /storage/mytharchive/config/mydata.xml
passed progress log file: /storage/mytharchive/logs/progress.log
mythburn.py (0.2.20200122-1) starting up...
Found 4 CPUs
Obtaining MythTV settings from MySQL database for hostname dvr
temppath: /storage/mytharchive/work
logpath:  /storage/mytharchive/logs
Setting process priority to 10
Setting ionice level to idle
Processing Mythburn job number 1.
Options - mediatype = 3, doburn = 1, createiso = 1, erasedvdrw = 0
          savefilename = '/storage/mytharchive/p-r.iso'
Looking for: /usr/share/mythtv/mytharchive/themes/Simple_-_Autoplay/theme.xml
Loading font 0, /usr/share/mythtv/fonts/FreeSans.ttf size 19
Loading font 1, /usr/share/mythtv/fonts/FreeSans.ttf size 15
Loading font 2, /usr/share/mythtv/fonts/FreeSans.ttf size 13
wantIntro: 0, wantMainMenu: 0, wantChapterMenu: 0, wantDetailsPage: 0
Final DVD Video format will be ntsc
There are 1 file(s) to process
Pre-processing file 1: '/storage/mytharchive/10787_20210108140000.mp4'
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/storage/mytharchive/10787_20210108140000.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:01:24.08, start: 0.100000, bitrate: 3574 kb/s
  Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv), 1280x720 [SAR 1:1 DAR 16:9], Closed Captions, 3178 kb/s, 59.95 fps, 59.94 tbr, 90k tbn, 119.88 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(eng): Audio: ac3 (ac-3 / 0x332D6361), 48000 Hz, 5.1(side), fltp, 384 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
    Side data:
      audio service type: main
/storage/mytharchive/work/1/streaminfo.xml:-
```
<?xml version="1.0" ?><!DOCTYPE FILEINFO><file cutduration="84" type="mov,mp4,m4a,3gp,3g2,mj2" filename="/storage/mytharchive/10787_20210108140000.mp4" duration="84">    
        <streams count="2">        
                <video fps="59.9401" aspectratio="1.77778" codec="h264 (High) (avc1 / 0x31637661)" bitrate="3178701" start_time="0.9000" streamindex="0" ffmpegindex="0" height="720" width="1280" id="1"/>        
                <audio samplerate="48000" language="eng" codec="ac3 (ac-3 / 0x332D6361)" bitrate="384000" start_time="0.9312" streamindex="1" ffmpegindex="1" channels="6" id="2"/>        
        </streams>    
</file>
```
Node = chanid, Data = 
Node = type, Data = file
Node = filename, Data = /storage/mytharchive/10787_20210108140000.mp4
Node = title, Data = /storage/mytharchive/10787_20210108140000.mp4
Node = recordingdate, Data = 
Node = recordingtime, Data = 
Node = subtitle, Data = 
Node = description, Data = 
Node = rating, Data = 
Node = coverfile, Data = 
Node = cutlist, Data = 
Video resolution is 1280 by 720
\************************************************************
Processing file 1: '/storage/mytharchive/10787_20210108140000.mp4'
\************************************************************
File type is 'mov,mp4,m4a,3gp,3g2,mj2'
Video codec is 'h264 (High) (avc1 / 0x31637661)'
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/storage/mytharchive/10787_20210108140000.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:01:24.08, start: 0.100000, bitrate: 3574 kb/s
  Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv), 1280x720 [SAR 1:1 DAR 16:9], Closed Captions, 3178 kb/s, 59.95 fps, 59.94 tbr, 90k tbn, 119.88 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(eng): Audio: ac3 (ac-3 / 0x332D6361), 48000 Hz, 5.1(side), fltp, 384 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
    Side data:
      audio service type: main
/storage/mytharchive/work/1/streaminfo.xml:-
```
<?xml version="1.0" ?><!DOCTYPE FILEINFO><file duration="84" filename="/storage/mytharchive/10787_20210108140000.mp4" cutduration="84" type="mov,mp4,m4a,3gp,3g2,mj2">    
        <streams count="2">        
                <video codec="h264 (High) (avc1 / 0x31637661)" fps="59.9401" start_time="0.9000" aspectratio="1.77778" height="720" width="1280" bitrate="3178701" id="1" streamindex="0" ffmpegindex="0"/>        
                <audio codec="ac3 (ac-3 / 0x332D6361)" language="eng" start_time="0.9312" id="2" bitrate="384000" streamindex="1" ffmpegindex="1" samplerate="48000" channels="6"/>        
        </streams>    
</file>
```
Preferred audio languages eng and eng
Video id: 0x1, Audio1: [1] 0x2 (AC3 (AC-3 / 0X332D6361), eng), Audio2: [-1] - 0x-1 (N/A, N/A)
Aspect ratio is 16:9
Re-encoding audio and video
Using encoder profiles from /usr/share/mythtv/mytharchive/encoder_profiles/ffmpeg_dvd_ntsc.xml
Encoding profile (LP) found
mythffmpeg -threads 4 -v 1 -i "/storage/mytharchive/10787_20210108140000.mp4" -r ntsc -target ntsc-dvd -b:v 2344k -s 352x480 -acodec ac3 -b:a 192k -ac 2 -aspect 16:9 "/storage/mytharchive/work/1/newfile2.mpg" -map 0:0 -map 0:1 
[mpeg @ 0x55d0bcfe1440] start time for stream 0 is not set in estimate_timings_from_pts
Input #0, mpeg, from '/storage/mytharchive/work/1/newfile2.mpg':
  Duration: 00:01:24.15, start: 0.533367, bitrate: 2176 kb/s
  Stream #0:0[0x1bf]: Data: dvd_nav_packet
  Stream #0:1[0x1e0]: Video: mpeg2video (Main), yuv420p(tv, progressive), 352x480 [SAR 80:33 DAR 16:9], 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Side data:
      cpb: bitrate max/min/avg: 9000000/0/0 buffer size: 1835008 vbv_delay: N/A
  Stream #0:2[0x80]: Audio: ac3, 48000 Hz, stereo, fltp, 192 kb/s
Traceback (most recent call last):
  File "/usr/share/mythtv/mytharchive/scripts/mythburn.py", line 5318, in main
    processJob(job)
  File "/usr/share/mythtv/mytharchive/scripts/mythburn.py", line 5009, in processJob
    processFile(node,folder,filecount)
  File "/usr/share/mythtv/mytharchive/scripts/mythburn.py", line 4502, in processFile
    doProcessFile(file, folder, count)
  File "/usr/share/mythtv/mytharchive/scripts/mythburn.py", line 4678, in doProcessFile
    getStreamInformation(mediafile, os.path.join(folder, "streaminfo.xml"), 1)
  File "/usr/share/mythtv/mytharchive/scripts/mythburn.py", line 1735, in getStreamInformation
    infoDOM = xml.dom.minidom.parse(xmlFilename)
  File "/usr/lib/python3.8/xml/dom/minidom.py", line 1959, in parse
    return expatbuilder.parse(file)
  File "/usr/lib/python3.8/xml/dom/expatbuilder.py", line 911, in parse
    result = builder.parseFile(fp)
  File "/usr/lib/python3.8/xml/dom/expatbuilder.py", line 207, in parseFile
    parser.Parse(buffer, 0)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 4, column 37
\------------------------------------------------------------

### Additional information
This Forum post says the problem is related to null characters being created in the streaminfo.xml file.
#https://forum.mythtv.org/viewtopic.php?f=36&t=4792

**Comment by rcrdnalor** [comment]
Mythburn.py from mytharchive calls several times "mytharchivehelper --getfileinfo"
to get a "streaminfo.xml" file but with different methods.

Please run in a terminal
(use the same file as previously posted, even if it is on different location)
```
mytharchivehelper --getfileinfo --infile /storage/mytharchive/10787_20210108140000.mp4 --outfile /tmp/fileinfo_0.xml --method 0
mytharchivehelper --getfileinfo --infile /storage/mytharchive/10787_20210108140000.mp4 --outfile /tmp/fileinfo_1.xml --method 1
mytharchivehelper --getfileinfo --infile /storage/mytharchive/10787_20210108140000.mp4 --outfile /tmp/fileinfo_2.xml --method 2
```
You can check the generated files for zeros with
```
hexdump -C -v /tmp/fileinfo_x.xml
```
where x is depicted to [0,1,2].

Attach the generated "fileinfo_x.xml" files as a compressed archive to this issue.
and also post the output of the following command on the same file
```
mythffprobe -hide_banner /storage/mytharchive/10787_20210108140000.mp4
```

**Comment by bshanteau** [comment]
[fileinfo_x.zip](https://github.com/MythTV/mythtv/files/9172690/fileinfo_x.zip)

> $ mythffprobe -hide_banner /storage/mytharchive/10787_20210108140000.mp4
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/storage/mytharchive/10787_20210108140000.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:01:24.08, start: 0.100000, bitrate: 3574 kb/s
  Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv), 1280x720 [SAR 1:1 DAR 16:9], Closed Captions, 3178 kb/s, 59.95 fps, 59.94 tbr, 90k tbn, 119.88 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(eng): Audio: ac3 (ac-3 / 0x332D6361), 48000 Hz, 5.1(side), fltp, 384 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
    Side data:
      audio service type: main

**Comment by bshanteau** [comment]
Done.

**Comment by rcrdnalor** [comment]
Interesting: Since all fileinfo_x.xml files are ok, matharchive complains about its own generated output file ;-)
This is in contrast to the log in the forum:
https://forum.mythtv.org/viewtopic.php?f=36&t=4792
 

Analysis:
A QString can embed '\0' characters (QChar::Null) as valid characters.
Thus, every item read from
```
std::string buf (256,'\0')
```
inside the function `getFileInfo` from `mytharchivehelper.cpp`
https://github.com/MythTV/mythtv/blob/109b9348c4ee077e0bece8bd3db01eaa51628ab1/mythplugins/mytharchive/mytharchivehelper/mytharchivehelper.cpp#L1909
needs to be checked for zeros:
```
QString::remove(QChar::Null);
```
If ffmpeg does not find a valid codec, the whole buffer is taken
in the function `getFileInfo`.
Since the buffer is filled by `avcodec_string` which is used in
mythmusic as well, we need to check this caller function as well.

Seems to be related to commit 52ba366 .


In the mean time, one can use this temporal workaraound:
```
diff --git a/mythplugins/mytharchive/mythburn/scripts/mythburn.py b/mythplugins/mytharchive/mythburn/scripts/mythburn.py
index f2485048a1..d07617c4d7 100755
--- a/mythplugins/mytharchive/mythburn/scripts/mythburn.py
+++ b/mythplugins/mytharchive/mythburn/scripts/mythburn.py
@@ -109,6 +109,7 @@ import unicodedata
 import time
 import tempfile
 from fcntl import ioctl
+import re
 
 try:
     import CDROM
@@ -1722,7 +1723,9 @@ def multiplexMPEGStream(video, audio1, audio2, destination, syncOffset):
 def getStreamInformation(filename, xmlFilename, lenMethod):
     """create a stream.xml file for filename"""
 
-    command = "mytharchivehelper -q -q --getfileinfo --infile %s --outfile %s --method %d" % (quoteCmdArg(filename), quoteCmdArg(xmlFilename), lenMethod)
+    tmpfile = xmlFilename.rsplit('.', 1)[0] + ".tmp"
+
+    command = "mytharchivehelper -q -q --getfileinfo --infile %s --outfile %s --method %d" % (quoteCmdArg(filename), quoteCmdArg(tmpfile), lenMethod)
 
 
     result = runCommand(command)
@@ -1731,10 +1734,25 @@ def getStreamInformation(filename, xmlFilename, lenMethod):
         fatalError("Failed while running mytharchivehelper to get stream information.\n"
                    "Result: %d, Command was %s" % (result, command))
 
+    # remove Nul characters from tmpfile
+    tflines = []
+    with open(tmpfile, 'r') as tf:
+        tflines = tf.readlines()
+
+    lines = []
+    for line in tflines:
+        x = re.sub(r'"[\x00]*"', r'""', line)
+        lines.append(x)
+
+    with open(xmlFilename, 'w') as f:
+        f.writelines(lines)
+
     # print out the streaminfo.xml file to the log
     infoDOM = xml.dom.minidom.parse(xmlFilename)
     write(xmlFilename + ":-\n" + infoDOM.toprettyxml("    ", ""), False)
 
+    os.unlink(tmpfile)
+
 #############################################################
 # Gets the video width and height from a file's stream xml file
 
```

**Comment by bshanteau** [comment]
@rcrdnalor Now works fine in mytharchive v33. Thanks.

**Comment by bshanteau** [comment]
@rcrdnalor Still does NOT work in v32. Have you applied commit https://github.com/MythTV/mythtv/commit/99a6e078027db5df7353dc2883d57dbb380acb92 to mytharchivehelper v32?

**Comment by bshanteau** [comment]
@rcrdnalor Mytharchivehelper is still broken in mytharchive v33.

`2:33.0~master.202209041802.8df204a377~ubuntu22.04.1`
[Vuelta a España 2022 Stage 11 0:27:51 Extended Highlights Cycling o_edit.mkv.zip](https://github.com/MythTV/mythtv/files/9489647/Vuelta.a.Espana.2022.Stage.11.0.27.51.Extended.Highlights.Cycling.o_edit.mkv.zip)
[mythburn.log.zip](https://github.com/MythTV/mythtv/files/9489648/mythburn.log.zip)

mythburn.log:
```
...
Extracting thumbnail image from /storage/mytharchive/work/1/stream.mv2 at position 10
Destination file /storage/mytharchive/work/1/title.jpg
Segmentation fault (core dumped)
************************************************************
ERROR: Failed while running mytharchivehelper to get thumbnails.
Result: 139, Command was mytharchivehelper -q -q --createthumbnail --infile "/storage/mytharchive/work/1/stream.mv2" --thumblist '10' --outfile "/storage/mytharchive/work/1/title.jpg"
See mythburn.log for more information.
************************************************************

Terminated
```

**Comment by Steve-Goodey** [comment]
Hi, any chance of a backport to V32 please?

**Comment by bshanteau** [comment]
@rcrdnalor Streaminfo.xml still has nulls in mytharchive v32. Any hope of fixing it any time soon?

**Comment by rcrdnalor** [comment]
I still have nulls in the fileinfo.xml file on master.
Probably related to https://github.com/MythTV/mythtv/blob/53dbe79f11fe2baafacf74559ac8ef5904f08bee/mythplugins/mytharchive/mytharchivehelper/mytharchivehelper.cpp#L2150
Could you please check an mpeg2ts file in SD that has subtitles as an additional stream?

**Comment by bshanteau** [comment]
> Could you please check an mpeg2ts file in SD that has subtitles as an additional stream?

I tried it with this short SD recording with subtitles: [30005_20221105124300.ts.zip](https://github.com/MythTV/mythtv/files/9943839/30005_20221105124300.ts.zip)

Same error:

```
...
Input #0, mpeg, from '/storage/mytharchive/work/1/newfile2.mpg':
  Duration: 00:00:17.36, start: 0.528033, bitrate: 2586 kb/s
  Stream #0:0[0x1bf]: Data: dvd_nav_packet
  Stream #0:1[0x1e0]: Video: mpeg2video (Main), yuv420p(tv, smpte170m, progressive), 352x480 [SAR 20:11 DAR 4:3], 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Side data:
      cpb: bitrate max/min/avg: 9000000/0/0 buffer size: 1835008 vbv_delay: N/A
  Stream #0:2[0x80]: Audio: ac3, 48000 Hz, stereo, fltp, 192 kb/s
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/share/mythtv/mytharchive/scripts/mythburn.py", line 5318, in main
    processJob(job)
  File "/usr/share/mythtv/mytharchive/scripts/mythburn.py", line 5009, in processJob
    processFile(node,folder,filecount)
  File "/usr/share/mythtv/mytharchive/scripts/mythburn.py", line 4502, in processFile
    doProcessFile(file, folder, count)
  File "/usr/share/mythtv/mytharchive/scripts/mythburn.py", line 4678, in doProcessFile
    getStreamInformation(mediafile, os.path.join(folder, "streaminfo.xml"), 1)
  File "/usr/share/mythtv/mytharchive/scripts/mythburn.py", line 1735, in getStreamInformation
    infoDOM = xml.dom.minidom.parse(xmlFilename)
  File "/usr/lib/python3.10/xml/dom/minidom.py", line 1988, in parse
    return expatbuilder.parse(file)
  File "/usr/lib/python3.10/xml/dom/expatbuilder.py", line 911, in parse
    result = builder.parseFile(fp)
  File "/usr/lib/python3.10/xml/dom/expatbuilder.py", line 207, in parseFile
    parser.Parse(buffer, False)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 4, column 21
------------------------------------------------------------
```
[mythburn.log](https://github.com/MythTV/mythtv/files/9943869/mythburn.log)

**Comment by bshanteau** [comment]
> Could you please check an mpeg2ts file in SD that has subtitles as an additional stream?

I still get an error on this SD recording with subtitles: [30005_20221105124300.ts.zip](https://github.com/MythTV/mythtv/files/9943964/30005_20221105124300.ts.zip)

It occurs while extracting thumbnails from [stream.mv2.zip](https://github.com/MythTV/mythtv/files/9943996/stream.mv2.zip) for a menu that I didn't request: [mythburn.log.zip](https://github.com/MythTV/mythtv/files/9943968/mythburn.log.zip)

```
...
Preferred audio languages eng and eng
Video id: 0x1e0, Audio1: [1] 0x80 (AC3, N/A), Audio2: [-1] - 0x-1 (N/A, N/A)
Splitting MPEG stream into audio and video parts
Running: mythreplex --demux --fix_sync -o "/storage/mytharchive/work/1/stream" -v 224 -c 128 "/storage/mytharchive/work/1/newfile2.mpg"
Audio is already in ac3 format
Extracting thumbnail image from /storage/mytharchive/work/1/stream.mv2 at position 10
Destination file /storage/mytharchive/work/1/title.jpg
Segmentation fault (core dumped)
************************************************************
ERROR: Failed while running mytharchivehelper to get thumbnails.
Result: 139, Command was mytharchivehelper -q -q --createthumbnail --infile "/storage/mytharchive/work/1/stream.mv2" --thumblist '10' --outfile "/storage/mytharchive/work/1/title.jpg"
See mythburn.log for more information.
************************************************************

chmod: changing permissions of '/storage/mytharchive/30005_20221105124300.ts': Operation not permitted
Terminated
```

That chmod error is strange, as the video file's owner is mythtv.

My configuration:
[mythfrontend_--version.zip](https://github.com/MythTV/mythtv/files/9943993/mythfrontend_--version.zip)
[mythbackend_--version.zip](https://github.com/MythTV/mythtv/files/9943994/mythbackend_--version.zip)

**Comment by bshanteau** [comment]
@rcrdnalor
> Could you please check an mpeg2ts file in SD that has subtitles as an additional stream?



I still get an error on this SD recording with subtitles: [30005_20221105124300.ts.zip](https://github.com/MythTV/mythtv/files/9943964/30005_20221105124300.ts.zip)

It occurs while extracting thumbnails from [stream.mv2.zip](https://github.com/MythTV/mythtv/files/9943996/stream.mv2.zip) for a menu that I didn't request: [mythburn.log.zip](https://github.com/MythTV/mythtv/files/9943968/mythburn.log.zip)

```
...
Preferred audio languages eng and eng
Video id: 0x1e0, Audio1: [1] 0x80 (AC3, N/A), Audio2: [-1] - 0x-1 (N/A, N/A)
Splitting MPEG stream into audio and video parts
Running: mythreplex --demux --fix_sync -o "/storage/mytharchive/work/1/stream" -v 224 -c 128 "/storage/mytharchive/work/1/newfile2.mpg"
Audio is already in ac3 format
Extracting thumbnail image from /storage/mytharchive/work/1/stream.mv2 at position 10
Destination file /storage/mytharchive/work/1/title.jpg
Segmentation fault (core dumped)
************************************************************
ERROR: Failed while running mytharchivehelper to get thumbnails.
Result: 139, Command was mytharchivehelper -q -q --createthumbnail --infile "/storage/mytharchive/work/1/stream.mv2" --thumblist '10' --outfile "/storage/mytharchive/work/1/title.jpg"
See mythburn.log for more information.
************************************************************

chmod: changing permissions of '/storage/mytharchive/30005_20221105124300.ts': Operation not permitted
Terminated
```

That chmod error is strange, as the video file's owner is mythtv.

My configuration:
[mythfrontend_--version.zip](https://github.com/MythTV/mythtv/files/9943993/mythfrontend_--version.zip)
[mythbackend_--version.zip](https://github.com/MythTV/mythtv/files/9943994/mythbackend_--version.zip)

**Comment by bshanteau** [comment]
@rcrdnalor Since I didn't want a menu, I commented out the command
`mytharchivehelper -q -q --createthumbnail --infile "/storage/mytharchive/work/1/stream.mv2"`
in v33 mythburn.py and the script ran successfully (and no chmod error).

Why get thumbnails when the user hasn't requested a menu?

In any case, mytharchivehelper still has an issue. Is somebody looking into it? Do you want me to?

**Comment by rcrdnalor** [comment]
The plugin mytharchive seems to be abandoned and poorly maintained since a decade.
If you want to contribute to MythTV open a pull-request against mythtv git/master describing the problem and the fix in detail. 
See https://www.mythtv.org/wiki/Contribute
BTW, creating ISOs or wasting blank DVDs for videos seems to be out-dated these days.
What's the need for you in this case?

**Comment by rcrdnalor** [comment]
Fixed on git master and fixes/32 . please re-open this issue in case you do not agree.
