### ISSUE TITLE
Mythburn.py fails to apply cut list to recording when creating iso file

### ISSUE THREAD

**Issue by bshanteau** [MythTV/mythtv#618]
* **Platform**:
`Linux dvr 5.15.0-43-generic #46-Ubuntu SMP Tue Jul 12 10:30:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

* **MythTV version**:
`2:33.0~master.202208012303.28d87d8bee~ubuntu22.04.1`

* **Package version**:
PPA: mythbuntu/33

* **Component**:
mythburn.py

### What steps will reproduce the bug?
Edit a recording to cut unwanted material, then:
MythFrontend->Utilities->Archive Files->Create DVD ->Select Destination: File: Make ISO Image->DVD Menu Theme: Simple-Autoplay->Select Archive Items: Add Recording-->Select recording->Next->Menu->Use Cut List->Next

### How often does it reproduce? Is there a required condition?
Happens every time. No apparent required condition.

### What is the expected behaviour?
Create iso file with cuts excluded

### What do you see instead?
Resulting iso file contains entire recording, ignoring cut list.

### Additional information
See attached 4 sec recording and iso files along with mythburn.log. The first 2 seconds of the recording should have been cut from the iso file, but isn't.
[Ms._Matched_4_sec.zip](https://github.com/MythTV/mythtv/files/9245531/Ms._Matched_4_sec.zip)

@rcrdnalor

**Comment by Jpilk** [comment]
It's a long time since I used mytharchive, and I always did as much processing as possible before entering it.  I have tens of Kg of DVDs, probably suffering from bit-rot.  
You have to use the menu key to 'Use Cut List' when you are in the 'Select Archive Items' page.  In the MythCenter-Wide' theme that turns the scissors red.

**Comment by bshanteau** [comment]
@Jpilk I know.

From my "What steps will reproduce the bug?"
`Select recording->Next->Menu->Use Cut List->Next`

**Comment by Jpilk** [comment]
Yes, apologies.  I just tried it in el7 fixes/32 using the SP encoder.  newfile2.mpg was full-length.  Then it crashed.    The reencode command line showed no attempt at cutting, which was supposed to be being done by Project-X, and maybe now I don't have that setting correct.  IMHO the attempt to do 'everything' is unwise, but I found a route, and some tweaks, that let me do what I wanted.

**Comment by rcrdnalor** [comment]
If you still have the files `newfile2.mpg` or `/storage/mytharchive/work/1/stream.mv2` could you please try
```
mytharchivehelper --createthumbnail --infile  /path/to/above/mentioned/file --thumblist '10' --outfile "/tmp/title_01.jpg"
```
Please replace the 'path to the file' accordingly and and if it crashes, create a backtrace according [wiki instructions ](https://www.mythtv.org/wiki/Debugging) ?

According my experience, the crash only occurs on a deinterlaced recordingt deep under  `MythAVUtil::DeinterlaceAVFrame(tmp);
https://github.com/MythTV/mythtv/blob/7be7e1677b2fdbc67b83e05928d3ea274f31cb5c/mythplugins/mytharchive/mytharchivehelper/mytharchivehelper.cpp#L1709
See issue #615  as well and 
([gdb_backtrace_01.zip](https://github.com/MythTV/mythtv/files/9254083/gdb_backtrace_01.zip))

**Comment by Jpilk** [comment]
That worked for me, with newfile2.mpg, and the thumbnail, 720x576, looks fine.

Input #0, mpeg, from '/home/john/mArchive/work/1/newfile2.mpg':
  Duration: 00:21:18.97, start: 0.534667, bitrate: 5008 kb/s
  Stream #0:0[0x1bf]: Data: dvd_nav_packet
  Stream #0:1[0x1e0]: Video: mpeg2video (Main), yuv420p(tv, progressive), 720x576 [SAR 64:45 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Side data:
      cpb: bitrate max/min/avg: 9000000/0/0 buffer size: 1835008 vbv_delay: N/A
  Stream #0:2[0x80]: Audio: ac3, 48000 Hz, stereo, fltp, 192 kb/s

I'm trying to get my old script and configuration working with py3, and at present it's not recognising my usual 'NONE' encoding profile.  Perhaps I need more quotes.

**Comment by bshanteau** [comment]
@rcrdnalor Are you confusing this cutlist issue with the mytharchive crash (issue #615) that I reported earlier? Because I am no longer able to recreate the mytharchive crash. This cutlist issue results in a failure to utilize the cutlist, not in a crash.

In case you need them, here are the work files for this cutlist issue: 
[cutlist_failure.zip](https://github.com/MythTV/mythtv/files/9255437/cutlist_failure.zip)

**Comment by Jpilk** [comment]
I've tried this with standard fixes/32 on my el7 box.  At present I can't get it to use Project-X, although that works in my normal cutting script.
The re-encoding using SP is fine, and the cutlist is applied.  But then, with all the themes I have tried, it fails with an 'invalid token' at line 4 column 37 of streaminfo.xml

[streaminfo.xml.log](https://github.com/MythTV/mythtv/files/9259254/streaminfo.xml.log)
[streaminfo_orig.xml.log](https://github.com/MythTV/mythtv/files/9259255/streaminfo_orig.xml.log)

**Comment by Jpilk** [comment]
I'm afraid I had missed  commit  99a6e078, not yet in fixes/32.   It's in devel/ffmpeg-resync,  building now...

**Comment by bshanteau** [comment]
@rcrdnalor Have you been able to recreate the problem of cutlists not being applied?

**Comment by Jpilk** [comment]
I have been looking at getting my MythArchive DVD-creation setup working again, although I don't expect to have much use for it.  It has changes from the distributed version and my usual input was mpeg2 video with one mp2 stream, already cut by ProjectX.  I used to be able to specify NONE as the encoder but at present that gets reset to one from the list.   

But I notice that in info.xml there is an empty cutlist while hascutlist is yes.  The log then shows a failure in mythburn.py at generateProjectXCutlist.  newfile2.mpg is reencoded but uncut.

**Comment by bshanteau** [comment]
@rcrdnalor @Jpilk I found the problem. My recording files (from Comcast Monterey) are type mpegts, which a comment at line 4540 in mythburn.py says mythtranscode cannot process:
`    #If this is an mpeg2 myth recording and there is a cut list available and the user wants to use it
    #run mythtranscode to cut out commercials etc
    if file.attributes["type"].value == "recording":
        #can only use mythtranscode to cut commercials on mpeg2 files
        write("File type is '%s'" % getFileType(folder))
        write("Video codec is '%s'" % getVideoCodec(folder))
        if (getVideoCodec(folder)).lower().startswith("mpeg2video"):`
I tried changing "mpeg2video" to "mpeg" and it worked fine with an mpegts recording. So that comment is not 100% correct.
[mythburn.log.zip](https://github.com/MythTV/mythtv/files/9388275/mythburn.log.zip)

**Comment by bshanteau** [comment]
My recording files (from Comcast Monterey) have video codec 'h264 (High) ([27][0][0][0] / 0x001B)', which a comment at line 4540 in mythburn.py says mythtranscode cannot process

**Comment by Jpilk** [comment]
I'm not sure where things stand now.  AIUI there has to be a transcode from h264 to mpeg2 to give DVD compatibility.  I think cutting should be  done after that initial transcode, although  I haven't (recently) tried following the python.  IIRC all my DVDs were from mpeg2video/mp2 recordings, cut outside MythArchive.

**Comment by bshanteau** [comment]
My HD recording files (from Comcast Monterey) have video codec h264, which a comment at line 4540 in mythburn.py as well as MythArchive documentation says mythtranscode cannot process for some reason.

**Comment by Steve-Goodey** [comment]
On Thursday, 4 August 2022 12:34:49 BST Jpilk wrote:
> I've tried this with standard fixes/32 on my el7 box.  At present I can't
> get it to use Project-X, although that works in my normal cutting script.
> The re-encoding using SP is fine, and the cutlist is applied.  But then,
> with all the themes I have tried, it fails with an 'invalid token' at line
> 4 column 37 of streaminfo.xml
> 
> [streaminfo.xml.log](https://github.com/MythTV/mythtv/files/9259254/streamin
> fo.xml.log)
> [streaminfo_orig.xml.log](https://github.com/MythTV/mythtv/files/9259255/st
> reaminfo_orig.xml.log)

Hi,

Sorry to stick my nose in and I'm coming into this thread late but your mention of 
invalid token struck a memory. I was also getting an ExpatError invalid token 
message which I found was due to an invalid character in the subtitle text. I found 
this by editing the recording metadata, in the plot: field I found "Derek□s" I changed 
this to "Derek's" and that fixed my problem.

Sorry if this is nothing to do with your problem, just thought I'd mention it.

-- 
Regards, Steve Goodey
Colchester, England
***@***.***

Hello to Jason Isaacs
