### ISSUE TITLE
Blocking artifacts with mpeg-ts in fixes/32 when using nvdec or vdpau

### ISSUE THREAD

**Issue by KungFuJesus** [MythTV/mythtv#634]
* **Platform**: ```Linux mythtvbox 5.17.5-gentoo #1 SMP PREEMPT Sun May 1 02:28:31 EDT 2022 x86_64 Intel(R) Core(TM)2 Quad CPU Q9650 @ 3.00GHz GenuineIntel GNU/Linux```

* **MythTV version**: fixes/32

* **Package version**: 

* **Component**: mythfrontend / mythavcodec

### What steps will reproduce the bug?
Playback 1080i video from OTA MPEG-TS with nvdec or VDPAU decoding.  

### How often does it reproduce? Is there a required condition?
Somewhat random but most often occurs during sharp scene transitions or high motion

### What is the expected behaviour?
No blocking artifacts

Here's the "debug" playback output when this issue occurs:
https://pastebin.com/m6cfem9q

Here's a screenshot:
![blocking_artifact](https://user-images.githubusercontent.com/3620277/189508720-48a69d9f-68c9-4f54-8144-071fa0f8c199.png)

### What do you see instead?
Blocking artifacts

### Additional information
This issue I believe to be inherited during a resync to ffmpeg 4.4 but it's hard to say for certain.  I _only_ exhibit this with VDPAU or nvdec decoding and the issue seems to disappear when the video is pulled from the transport stream into a regular mpeg2 container.  I was able to see this same buggy behavior with nvdec on a different machine with mpv for a while, but now that I've updated ffmpeg and mpv over the past year or so, I cannot observe it anymore.  The issue cropped up right around the v32 update and I seem to not be the only one exhibiting this issue, as this mailing list user also seems to have the symptoms: https://lists.archive.carbon60.com/mythtv/dev/638570

I'm attaching a minimally sized ts that exhibits the issue.  Hopefully it's not too large.
[problem.zip](https://github.com/MythTV/mythtv/files/9541664/problem.zip)

I've mentioned this issue in issue #428.  The machine using nvdec with mpv is leveraging ffmpeg 4.4.2, so it's at least fixed in that verison.  

Let me know if there's anything more I can provide.

**Comment by KungFuJesus** [comment]
Oh and the option to use FFmpeg's vanilla demuxer does _not_ make the issue go away.  It's unclear if an update to ffmpeg made the issue disappear with mpv or if a fix applied to mpv's ffmpeg usage made the issue go away, but mpv plays this file with no issues, and mythtv reliably has these artifacts, whether seeking / skipping or not.

**Comment by Jpilk** [comment]
I'm running current devel/ffmpeg-resync f813141 with the PR#610 patch and VDPAU with an nVidia 470 driver.  I see this blocking-after-skip only in recordings  from the 'local' mux, which is encoded with the 'field pictures' feature which the PR targets when using software decoding.   

I believe some channels in the USA also use that feature - but I suppose I may have the hammer/nail diagnosis syndrome.

**Comment by KungFuJesus** [comment]
I can't recall with any concreteness whether I see this with progress scan broadcasts but that could simply be coincidence or a consequence of the fact that most of what I view that's interlaced is 1080i content.  It could be the 1080 part that's the common factor when I see the issue and not the 'i' part.  I don't watch enough content stuck in 480i on broadcast to know.  

For me, there's no need to skip around, it just shows up.  For a while, it also showed up in mpv.  Either an update in mpv or an update to the ffmpeg it relies on made this issue disappear.  I haven't seen these artifacts on a va-api system which initially led me to believe that it was a hopeless nvidia-specific issue but with it disappearing in mpv...maybe it's something ffmpeg fixed upstream?

**Comment by bennettpeter** [comment]
Is this only with mpeg-2 and only on certain channels? There was a bug in NVidia mpeg-2 decoding that caused intermittent pixelation on certain channels that used a high level of compression. The explanation from NVidia was "longer than expected motion vector" or something to that effect. Newer NVidia cards may not have this problem.

**Comment by KungFuJesus** [comment]
Mpeg2 in pretty much every 1080i broadcast. It goes away after transcoding losslessly into an mpeg2 container. I have a Maxwell GPU with mpv I can test this on. Admittedly my most recent test was with an ampere. Let me see if mpv+newer ffmpeg on the Maxwell GPU is enough to make the issue disappear or if it's still affected.

This had not been an issue until v32 from what I recall.

**Comment by bennettpeter** [comment]
The problem started for me when they re-arranged channel frequencies to put more channels on one frequency.
Try this extract, put it in your videos directory
https://drive.google.com/file/d/1OTFY3MWJg8pM-bLgX-IWLXKQoDEYuSz-/view?usp=sharing
This used to show pixelation artifacts on older nvidia with VDPAU or NVDEC.

**Comment by KungFuJesus** [comment]
So mpv + nvdec with a Maxwell GPU does not exhibit this (mpv linked ffmpeg 4.4.2 in this case).  The same machine _does_ exhibit these artifacts when running mythtv when using both VDPAU and nvdec.  So, while that doesn't completely exonerate nvidia bugs, it definitely points the fingers at at least a potential workaround.

**Comment by KungFuJesus** [comment]
> The problem started for me when they re-arranged channel frequencies to put more channels on one frequency. Try this extract, put it in your videos directory https://drive.google.com/file/d/1OTFY3MWJg8pM-bLgX-IWLXKQoDEYuSz-/view?usp=sharing This used to show pixelation artifacts on older nvidia with VDPAU or NVDEC.

Yes, mythtv exhibits this with the internal player (however, mpv does _not_).  
![blocking_artifact2](https://user-images.githubusercontent.com/3620277/189536642-71f324d3-4b3c-426c-a4b4-4ffc066beed0.png)

It's less pronounced but it's there.

**Comment by KungFuJesus** [comment]
And on the Maxwell based machine, the issue is entirely concealed as well.  Though, perhaps relevant, we see this message printed:
[adam@lanbox2 ~]$ mpv --hwdec=nvdec Downloads/ch710_pixellating_extract.mkv 
 (+) Video --vid=1 (*) (mpeg2video 1920x1080 29.970fps)
 (+) Audio --aid=1 --alang=eng (*) (ac3 6ch 48000Hz)
     Audio --aid=2 --alang=spa (ac3 2ch 48000Hz)
[ffmpeg/video] mpeg2video: ignoring pic cod ext after 0
 (+) Video --vid=1 (*) (mpeg2video 1920x1080 29.970fps)
 (+) Audio --aid=1 --alang=eng (*) (ac3 6ch 48000Hz)
     Audio --aid=2 --alang=spa (ac3 2ch 48000Hz)
     Subs  --sid=1 (*) (eia_608)
AO: [pulse] 48000Hz 5.1(side) 6ch float
VO: [gpu] 1920x1080 yuv420p
AV: 00:00:30 / 00:00:34 (88%) A-V:  0.000 ct:  0.073 Dropped: 1

I see that message immediately at the start of play so it's hard to say if the troublesome area is causing that or not.  This could just be a red herring.  But the good news is that these issues seem absent with mpv, at least with newer ffmpeg (4.4.2 in this circumstance).

**Comment by bennettpeter** [comment]
On my laptop with NVidia GeForce GTX 1650, with latest master of MythTV, this clip is perfect. On older NVidia hardware it would show pixelation like you saw. I believe this is dependent on the hardware, and would happen irrespective of the ffmpeg or MythTV version.
The workaround is to use mythfrontend setup to force mythtv to use software decoding (i.e. OpenGL) for MPEG-2 and allow NVDEC for all other formats.

**Comment by KungFuJesus** [comment]
Yes that's the most obvious workaround however my frontend is fairly under powered and while it could do decode duty on mpeg2 without too much trouble it'd be a fair amount of fan noise and power consumption. Especially with software deinterlacing.

And more interestingly, the issue disappears in mpv for both recordings when compiled with a newer ffmpeg. It's still unclear if mpv fixed this or ffmpeg did but it seems fixable if it's specifically a decoder bug on certain models.

Maybe I could ld_preload an older ffmpeg to see if the issue comes back for mpv.

**Comment by ulmus-scott** [comment]
@KungFuJesus If you want to try the latest FFmpeg release/4.4 see the attached patch.  It was a straightforward merge without conflicts.
[0001-FFmpeg-update-to-current-version-4.4.2.patch.zip](https://github.com/MythTV/mythtv/files/9543245/0001-FFmpeg-update-to-current-version-4.4.2.patch.zip)

**Comment by KungFuJesus** [comment]
> @KungFuJesus If you want to try the latest FFmpeg release/4.4 see the attached patch. It was a straightforward merge without conflicts. [0001-FFmpeg-update-to-current-version-4.4.2.patch.zip](https://github.com/MythTV/mythtv/files/9543245/0001-FFmpeg-update-to-current-version-4.4.2.patch.zip)

Giving it a go now :crossed_fingers: .  Compiling on the Q9650, could be a bit.

**Comment by Jpilk** [comment]
As I said above, with vdpau I get blocking after skips.  nvdec decoding (with medium quality deinterlacers) on the same recording is fine.  Unfortunately, what works well in playback often gives artefacts in still pictures while editing cutpoints.

**Comment by KungFuJesus** [comment]
Unfortunately the issue is still there in its entirety when bringing things up to 4.4.  So, mpv is fixing it downstream somehow?  Or, mythtv was somehow identically inducing the same error with its patches?

**Comment by KungFuJesus** [comment]
I'm going to have to see how far back I can go with mpv to see if the issues comes back and bisect.  Maybe, just maybe, the commit that makes the issue disappear is one that is applicable to how mythtv calls into mythffmpeg.  The H.264 seemed to involve copying a frame out somewhere.

**Comment by KungFuJesus** [comment]
The only thing I've found so far is mpv initializes the hardware decoding context with image format cuda, while mythtv maybe does NV12?  I've never used ffmpeg as a library directly, but maybe I'm onto something?

**Comment by KungFuJesus** [comment]
@Jpilk do you think #610 would have a material effect on this behavior?

**Comment by bennettpeter** [comment]
Can you be sure that mpv is using hardware decoding? How is the CPU usage when playing on mpv?

**Comment by KungFuJesus** [comment]
That's a good point, on that test system it doesn't print "using hardware decoding".  On my other systems it does.  Ugh, sorry I missed that, but at least I can restart my search for the culprit here.

**Comment by KungFuJesus** [comment]
Ok good news, I got it to reproduce in the latest mpv with ffmpeg 4.4.1.  I was missing --hwdec-codecs=all to actually make it use hardware decoding for mpeg2.  Now I can bisect ffmpeg possibly and see what's going on.  The ffmpeg 4.4.2 machine with nvdec does not exhibit these artifacts, so that's a good range to look through, maybe I can find the fixing commit and see why mythtv isn't getting the benefit from it.

**Comment by KungFuJesus** [comment]
Though, it's now dawned on me that this could be a dreaded nvidia hardware specific issue like speculated and it's only not causing issues on the ffmpeg 4.4.2 machine because it's on Ampere :-/.  I hope that's not the case.

**Comment by KungFuJesus** [comment]
Well crap, that is the case.  Do we beg nvidia to fix this on their user forums?  Maxwell is technically still supported (though probably on the chopping block).  @Jpilk do you have a link to that particular bug being reported to nvidia?

**Comment by KungFuJesus** [comment]
I've made a post on their forums, I really hope they'll actually bother fixing things :-/.
https://forums.developer.nvidia.com/t/mpeg2-hardware-accelerated-decoding-broken-on-maxwell-pascal/227727

**Comment by Jpilk** [comment]
No, I don't know of any report to nvidia.  But this thread seems relevant.  There was a sample clip in it.

http://lists.mythtv.org/pipermail/mythtv-users/2021-December/408597.html

**Comment by KungFuJesus** [comment]
Hmm, the user in that ML post seems to conclude that issue is due to AMD's VDPAU implementation rather than NVidia's so I don't know that that is a good smoking gun.  It also cites lockups, which I do not experience.

**Comment by bennettpeter** [comment]
This problem has existed for a long time, probably 10 years. The reason nobody noticed is that it only affects high levels of compression, that have been in use in the last few years. Starting in 2017 the FCC took some frequencies from the TV stations which then had to start broadcasting multiple channels on one frequency, and they started using higher levels of mpeg-2 compression which triggered the pixelation bug in nvidia devices.

**Comment by KungFuJesus** [comment]
Well, that's frustrating if it is a bug in the hardware decoder block.  I certainly wouldn't prefer to spend $300 on the minimally priced ampere card, especially given the age of the system.  _Maybe_ could chase down a lower powered used Turing card or something.

**Comment by bennettpeter** [comment]
If it helps, my laptop seems to have the bug fixed. It has NVIDIA GeForce GTX 1650. I am not sure which generation of NVidia that is.

Is your system very old that it cannot use software decoding for mpeg-2? Even a raspberry pi can decode 1920x1080 mpeg-2 in software. It would be very hard to find a system that cannot handle it. 

This bug is the reason I added "Video Formats" to the playback profile, thus enabling you to select software decoding for mpeg-2 and let other formats use vdpau or nvdec.

I would not buy a new NVidia card hoping that will solve the problem. Even the NVidia Shield had this problem. I am actually surprised that this laptop has it solved.

Does your frontend have onboard Intel graphics? In that case you may be able to use VAAPI.

Rather than spend hundreds on a new graphics card, you could get a fire stick or Walmart "ONN" streaming device. These cost $20 and up. The fire stick 4K can run mythfrontend or leanfront. The lower powered non-4k version can run leanfront. The ONN can run leanfront.

**Comment by KungFuJesus** [comment]
It's not that it couldn't if just can't do it efficiently per watt. The pre-nehalem CPUs lack a lot of efficiency gains in the micro architecture, and not just for the idct portion.  The fan ramps up and gets fairly noisy and I'd probably end up consuming a steady constant 160 watts over the duration of the viewing as opposed to maybe 100 watts with the CPU idling and the GPU consuming maybe 10 or 15 watts.

That and it's a frontend +backend, so there's other side effects that could happen (eg dropped frames from the tuner cards, other microstutters, severe playback degradation during commercial flagging).

**Comment by kmdewaal** [comment]
On my NVidia GT1030 card the pixelation is also visible. However, as this is a NVidia hardware issue it cannot be fixed in MythTV.  Therefore closing this issue.
