### ISSUE TITLE
Ambiguous title in sql 

### ISSUE THREAD

**Issue by grandmastermarclar** [MythTV/mythtv#640]
Platform: ubuntu 22.04
MythTV version: 32/fixes
Package version: fixes/32 [v32.0+fixes.202209121203.b6ef30288f~ubuntu22.04.1] www.mythtv.org
Component: backend

### What steps will reproduce the bug?

I've got a recording rule which seems to constantly spit out the following in mythbackend.log:

Sep 24 17:42:00 babylon mythbackend: mythbackend[1297068]: E Scheduler mythdb.cpp:229 (DBError) DB Error (UpdateMatches3):#012Query was:#012REPLACE INTO recordmatch (recordid, chanid, starttime, manualid,                           oldrecduplicate, findid) SELECT record.recordid, program.chanid, program.starttime,  IF(search = 5, record.recordid, 0), (CASE   WHEN record.type IN (1, 7, 8) THEN  0   WHEN record.type IN (6, 2, 5) THEN  -1   ELSE (program.generic - 1)  END) , (CASE record.type   WHEN 6    THEN record.findid   WHEN 2    THEN to_days(date_sub(convert_tz(program.starttime, 'UTC', 'SYSTEM'),             interval time_format(record.findtime, '%H:%i') hour_minute))   WHEN 5    THEN floor((to_days(date_sub(convert_tz(program.starttime, 'UTC',             'SYSTEM'), interval time_format(record.findtime, '%H:%i')             hour_minute)) - record.findday)/7) * 7 + record.findday   WHEN 7    THEN record.findid   ELSE 0  END) FROM (record, program INNER JOIN channel       ON channel.chanid = program.chanid)  WHERE record.recordid = '390' AND program.manualid = 0 AND ( title like '%The Labour Party%'#012and program.hdtv > 0#012and channel.sourceid = 2 ) AND channel.deleted IS NULL  AND channel.visible > 0  AND program.endtime > (NOW() - INTERVAL 480 MINUTE) AND channel.sourceid = 1 AND program.starttime <= '2022-09-24T05:15:00Z' AND (((record.filter & 1) = 0) OR (program.previouslyshown = 0)) AND (((record.filter & 2) = 0) OR (program.generic = 0)) AND (((record.filter & 4) = 0) OR (program.first > 0)) AND (((record.filter & 8) = 0) OR (HOUR(CONVERT_TZ(program.starttime, 'Etc/UTC', 'SYSTEM')) >= 19 AND HOUR(CONVERT_TZ(program.starttime, 'Etc/UTC', 'SYSTEM')) < 22)) AND (((record.filter & 16) = 0) OR (channel.commmethod = -2)) AND (((record.filter & 32) = 0) OR (program.hdtv > 0)) AND (((record.filter & 64) = 0) OR ((record.programid <> '' AND program.programid = record.programid) OR (record.programid = '' AND program.subtitle = record.subtitle AND program.description = record.description))) AND (((record.filter & 128) = 0) OR ((record.seriesid <> '' AND program.seriesid = record.seriesid))) AND (((record.filter & 256) = 0) OR (ABS(TIMESTAMPDIFF(MINUTE, CONVERT_TZ(  ADDTIME(record.startdate, record.starttime), 'Etc/UTC', 'SYSTEM'),   CONVERT_TZ(program.starttime, 'Etc/UTC', 'SYSTEM'))) MOD 1440 <= 10)) AND (((record.filter & 512) = 0) OR (ABS(TIMESTAMPDIFF(MINUTE, CONVERT_TZ(  ADDTIME(record.startdate, record.starttime), 'Etc/UTC', 'SYSTEM'),   CONVERT_TZ(program.starttime, 'Etc/UTC', 'SYSTEM'))) MOD 10080 <= 10)) AND (((record.filter & 1024) = 0) OR (channel.callsign = record.station)) AND (((record.filter & 2048) = 0) OR (program.category_type <> 'series')) AND (((record.filter & 4096) = 0) OR (channel.recpriority > 0)) AND ( (record.type = 4   OR record.type = 6   OR record.type = 2   OR record.type = 5)  OR   ((record.type = 1    OR record.type = 7    OR record.type = 8)   AND    ADDTIME(record.startdate, record.starttime) = program.starttime    AND    record.station = channel.callsign) ) #012Bindings were:#012:MAXSTARTTIME=2022-09-24T05:15:00.000Z, :NR67RECID="390", :SOURCEID=1#012Driver error was [2/1052]:#012QMYSQL: Unable to execute query#012Database error was:#012Column 'title' in where clause is ambiguous

### Additional information

Running with mariadb  Ver 15.1 Distrib 10.8.5-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper

**Comment by linuxdude42** [comment]
How did you define your recording for "The Labour Party"?  This appears to be a power search for  ```( title like '%The Labour Party%' and program.hdtv > 0 and channel.sourceid = 2 )```. Changing ```title``` to ```program.title``` should eliminate this warning.

**Comment by grandmastermarclar** [comment]
Good spot! My bad...

Ian
