### ISSUE TITLE
MythTV Bricked My COMPUTER

### ISSUE THREAD

**Issue by lewtwo** [MythTV/mythtv#644]
How it started: I installed ZoneMinder using the Synatpics Package Manager on Linux mint.
Release Linux Mint 20.3 Una 64-bit
Kernel Linux 5.4.0-126-generic x86_64
MATE 1.26.0

The only menu entry added (that I could find) was MythTV, so I ran it.
Now its UI come up, full screen and fails to connect to the Database ....
When I press the exit button, it exits and restarts.
I only have about 5 seconds to get to anything else on my computer before it wipes out the display again.

WORST UI DESIGN THAT I HAVE EVER SEEN !!!

**Comment by billmeek** [comment]
On 9/28/22 16:51, lewtwo wrote:
> How it started: I installed ZoneMinder using the Synatpics Package Manager on Linux mint.
> Release Linux Mint 20.3 Una 64-bit
> Kernel Linux 5.4.0-126-generic x86_64
> MATE 1.26.0
> 
> The only menu entry added (that I could find) was MythTV, so I ran it.
> Now its UI come up, full screen and fails to connect to the Database ....
> When I press the exit button, it exits and restarts.
> I only have about 5 seconds to get to anything else on my computer before it wipes out the display again.
> 
> WORST UI DESIGN THAT I HAVE EVER SEEN !!!

Sounds like the issue that was fixed a year ago in July. See if the following
line in mythfrontend.sh matches this:

   https://github.com/MythTV/packaging/blob/master/deb/debian/mythfrontend.sh#L48

The fix was applied in the Ubuntu packaging for v32 and not backported.

-- 
Bill

**Comment by ulmus-scott** [comment]
The commit that fixed it was https://github.com/MythTV/packaging/commit/bc160d097b1de3c6a25e659b87951f06a3e12bc8 .  Restarting the computer or killing mythfrontend.real will break the loop.  I had that fix backported to fixes/30 and fixes/31, but that might only effect the ppa users.

What version of MythTV do you have?  And does the line in mythfrontend.sh match 
```
[ "$RET" = "0" -o "$RET" = "1" -o "$RET" = "130" -o "$RET" = "254" ]
```

?

**Comment by lewtwo** [comment]
Powering off broke the loop . Then I restored the system from backup made that morning.
