### ISSUE TITLE
Support latest libhdhomerun api (2022-10)

### ISSUE THREAD

**Issue by linuxdude42** [MythTV/mythtv#649]
Silicondust released a new version of the libhdhomerun API on 2022-10-10. This release does the following:

Removes the following API:

- hdhomerun_discover_find_devices_custom

Marks the following APIs as legacy:

- hdhomerun_discover_find_devices_custom_v2
- hdhomerun_discover_find_devices_custom_v3

Introduces a new discovery API:
- hdhomerun_discover_create
- hdhomerun_discover_destroy
- hdhomerun_discover2_find_devices_xxx
- hdhomerun_discover2_iter_device_xxx
- hdhomerun_discover2_device_is_xxx
- hdhomerun_discover2_device_get_xxx
- hdhomerun_discover2_device_if_xxx

This update will cause MythTV to fail to compile because as hdhrstreamhandler.cpp requires the removed API function. The code in cardutil.cpp was updated in 2018 to use hdhomerun_discover_find_devices_custom_v2 and will still compile.

The following needs to be done:

Short term:
- [x] Drop support for hdhomerun_discover_find_devices_custom.
- - The _v2 version of this function has existed for seven years.

Long term:
- [ ] Convert to the new hdhomerun_discover2 API.

**Comment by ulmus-scott** [comment]
`configure` says:
https://github.com/MythTV/mythtv/blob/167e016e38b30fb2984e1959dc323bbdaea30468/mythtv/configure#L6045

The `hdhrstreamhandler.cpp` code is protected by `ifdef`:
https://github.com/MythTV/mythtv/blob/167e016e38b30fb2984e1959dc323bbdaea30468/mythtv/configure#L6054-L6057

It appears `hdhomerun_device_selector_load_from_str` was added in libhdhomerun version 20160130.  Our version was added in November 2018 https://github.com/MythTV/mythtv/commit/e50d9c7d3a90ad4e877347068cfd913d114fe23c .

Is this a candidate for removing the old `ifdef`ed code?
