### ISSUE TITLE
Metadata lookup and display fails too often

### ISSUE THREAD

**Issue by SteveErl** [MythTV/mythtv#656]
* **Platform**: All

* **MythTV version**: fixes/32

* **Package version**:

* **Component**: metadata

### What steps will reproduce the bug?

Metadata lookup and display fail fairly often. These failures are more common when using Manual Record rules because there is no specified season, episode, or subtitle before a TV episode is recorded. The routine to guess the lookup type (movie or TV) tends to presume movie when there is no subtitle or episode number specified. If the title of the recording has a close match in movies, then a better match in television shows gets ignored.

There are some TV show titles which have exact matches for shows in multiple countries. For example, "Good Witch" matches both an American show and a Korean show. A recording of the American show ended up displaying the artwork from the Korean show.

When trying to find a "best" match, the Levenshtein distance tolerance algorithm has a severe weakness when applied to short title names.

For Manual Record rule sourced recordings, season, episode, subtitle, and description information doesn't get displayed, even when it is available.

### How often does it reproduce? Is there a required condition?
Too often. It depends on many factors.

Failure to display season, episode, subtitle, and description information for Manual Record rule recordings happens always.
### What is the expected behaviour?

When trying to guess the lookup type, we should use additional information such as the recording type (Single, All, Daily, Weekly) and the length of the recording to get a more accurate determination.

When trying to pick the best match for metadata information, some degree of preference should be given to entries with a matching language, and the Levenshtein distance tolerance algorithm needs to be replaced with something which handles short title strings better.

If the metadata lookup is successful enough to identify the season, episode, subtitle, and description for a particular episode of a TV show, that information should be displayed to the user in MythTvFrontend.

**Comment by ulmus-scott** [comment]
You should open a Pull Request with your commit, for easier review and possibility of merging.

It looks to me that the commit should be split into several commits: 

- GuessLookupType improvements
- apply Levenshtein distance as a fraction
- update metadata with what was found

**Comment by rcrdnalor** [comment]
It looks to me that the attached patch has focus on a single use case:
Update metadata  (with the grabber for tvmaze) of a recording having a manual recording rule.
Other use cases, like the bulk retrieving of metadata or the lookup by command line are less considered:
Keyword: Automatic Mode
Please consider all use cases and the characteristics of different metadata grabbers. 

Some background information:
Metadata Lookup:
See wiki page https://www.mythtv.org/wiki/Enhancing_Recordings_with_Metadata_Lookup

The MetadataFactory is used recursively for fetching metadata for
recordings and videos satisfying two use cases:
Automatic Mode: Return a single data if an exact match is found (non interactive)
Manual Mode: return a list of data and present a list for interactive selection.

Both use cases can be triggered either by the frontend or by the backend.
Both use cases can run at different times, not only on creation of a recording-rule.

These flags are available by 
```
MetadataFactory->Lookup(object, bool automatic = true,
                                getimages = true, 
                                bool allowgeneric = false);
```
These are the sources where one can initiate a metadata lookup:

The program mythmetadatalookup calls
   (see file programs/mythmetadatalookup/lookup.cpp)
   using automatic mode:
 - for a single recording:
   `m_metadataFactory->Lookup(pginfo, true, false, false);`
 - for bulk update of the recordings:
   `m_metadataFactory->Lookup(pginfo, true, false, false);`
 - for a bulk update of the recording rules:  
   `m_metadataFactory->Lookup(pginfo, true, false, true);`
 - for a bulk update of artworks:
   `m_metadataFactory->Lookup(pginfo, true, false, true/false);`
   (for aggressive mode it is true)
   Note: Can be executed at any time.
   
The frontend gui for editing metadata of a recording :
    `lookup->SetAutomatic(false);`
    `m_metadataFactory->Lookup(lookup);`
    in `void RecMetadataEdit::PerformQuery()` of playbackbox.cpp
    Note: Steppes Theme: recordings-ui.xml has a 'query_botton'
    Note: Can be executed on a valid recording
   
The frontent gui for editing/creating a recording rule calls
    `lookup->SetAutomatic(false);`
    `m_metadataFactory->Lookup(lookup);`
     when called from the "Metadata Options" window
    in `void MetadataOptions::PerformQuery()` of scheduleeditor.cpp
    Note: Single recording rules are deleted shortly after the recording was made.

The frontend gui for finding the artwork of a recording in the "Metadata Options" window calls
    `lookup->SetAutomatic(true);`
    `m_imageLookup->addLookup(lookup);
    in `void MetadataOptions::FindNetArt(VideoArtworkType type)` of scheduleeditor.cpp
    Note: Can be executed on a valid recording.

The frontend gui for updating the artwork of a recording in the "Metadata Options" window calls
    `lookup->SetAutomatic(true);`
    `m_imageDownload->addDownloads(lookup);`
    see `void MetadataOptions::OnImageSearchListSelection(...)` of scheduleeditor.cpp
    Note: Can be executed on a valid recording.
	
The frontend gui for editing/creating a schedule for a recording allows
    the program mythmetadatalookup as a job which calls "HandleSingleRecording"
    if "Automatically Look Up Metadata" is selected for post processing of a recording
    Note: Runs directly after the recording was made.

The program mythutil allows to scan for videos ("--scanvideos") and	
    if enabled, this will also trigger the bulk metadata scanner upon completion.
    Note: Can be executed at any time.

The frontend can also trigger a video scan including a bulk update of the metadata
    `m_metadataFactory->Lookup(metadata, automode, true);`
    see mythfrontend/videodlg.cpp, `VideoDialog::VideoAutoSearch` and `VideoDialog::VideoSearch`
    Note: automode is true in this case
    Note: The VideoScan itself runs on the backend.
    Note: Can be executed at any time.
	
The frontend can also fetch the metadata for a single video	("Retrieve All Details")
    using `VideoDialog::VideoAutoSearch:
    `m_metadataFactory->Lookup(metadata, automode, true);`
    see mythfrontend/videodlg.cpp, `VideoDialog::VideoAutoSearch` and `VideoDialog::VideoSearch`
    Note: automode is false in this case
    Note: Can be executed at any time.
	
MythServices offer a service to get the metadata: This uses 
    `MetadataFactory::SynchronousLookup()`, using 
    `lookup->SetAutomatic(false);`
    on the backend.
    Note: Can be executed at any time.

**Comment by rcrdnalor** [comment]
Closing this issue as fixed by https://github.com/MythTV/mythtv/commit/9076f82
