### ISSUE TITLE
Timezone data version 3 is not supported

### ISSUE THREAD

**Issue by SteveErl** [MythTV/mythtv#672]
* **Platform**: Linux Mint 20.3
`Linux Doom 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

* **MythTV version**: fixes/32, master

* **Component**: python bindings

### What steps will reproduce the bug?
/usr/share/mythtv/metadata/Television/tvmaze.py -l en -a US -N "The Masked Singer" "2022-11-24 19:00:00"

When the last argument holds a timestamp, the script looks for any episode with a matching date and time. This particular show has many versions originating in many countries, so the script searches across all those versions. 

### How often does it reproduce? Is there a required condition?
Always, when the TV show has a version in timezone 'Asia/Jerusalem'.

### What is the expected behaviour?
It should just show the metadata information for a matching TV show, which is the US version, inetref 38104, Season 8, Episode 10.

### What do you see instead?
ERROR: <class 'UnboundLocalError'> : local variable 'ttmfmt' referenced before assignment

### Additional information
Adding the '--debug' flag will show a Traceback.

```
/usr/share/mythtv/metadata/Television/tvmaze.py --debug -N "The Masked Singer" "2022-11-24 19:00:00"
Args:  ['The Masked Singer', '2022-11-24 19:00:00']
Opts:  {'version': False, 'test': False, 'tvlist': False, 'tvdata': False, 'collectiondata': False, 'tvnumbers': True, 'language': 'en', 'country': None, 'debug': True, 'doctest': False}
Function 'buildNumbers' called with arguments: 'The Masked Singer' '2022-11-24 19:00:00'
Recording in range of inetref 38104, season 8, episode 10 (2022-11-25 01:00:00+00:00 ... 2022-11-25 02:00:00+00:00)
Traceback (most recent call last):
  File "programs/scripts/metadata/Television/tvmaze.py", line 746, in <module>
    main()
  File "programs/scripts/metadata/Television/tvmaze.py", line 723, in main
    buildNumbers(args, opts)
  File "programs/scripts/metadata/Television/tvmaze.py", line 231, in buildNumbers
    dtInTgtZone = dtInLocalZone.astimezone(posixtzinfo(show_tz))
  File "/usr/lib/python3/dist-packages/MythTV/utility/singleton.py", line 49, in __call__
    inst = type.__call__(cls, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/MythTV/utility/dt.py", line 234, in __init__
    self._process(fd, version)
  File "/usr/lib/python3/dist-packages/MythTV/utility/dt.py", line 167, in _process
    t = unpack(ttmfmt, fd.read(calcsize(ttmfmt)))[0]
UnboundLocalError: local variable 'ttmfmt' referenced before assignment
```

The failure happens when trying to process the Israeli version of "The Masked Singer", which has a timezone (_show_tz_) of 'Asia/Jerusalem'. The tzmaze.py script converts the local timestamp to the timezone of the possible target match using `.astimezone(posixtzinfo(show_tz)`.
```
$ file /usr/share/zoneinfo/Asia/Jerusalem 
/usr/share/zoneinfo/Asia/Jerusalem: timezone data, version 3, 9 gmt time flags, 9 std time flags, no leap seconds, 149 transition times, 9 abbreviation chars
```

This particular timezone is in version 3, which doesn't seem to be supported by MythTV.

**Comment by rcrdnalor** [comment]
The RFC 8536 (1) defines 'The Time Zone Information Format (TZif)', 
including version 3.

One extra item in version 3 is the section 'TZ String Extensions',
which says:
    DST is considered to be in effect all year if it starts January 1
    at 00:00 and ends December 31 at 24:00 plus the difference between
    daylight saving and standard time, leaving no room for standard
    time in the calendar.
      
I have not found such an implementation on the current zoneinfo files
installed at '/usr/share/zoneinfo'.

However, the iana time zone news (2) state:
    Much of Greenland, represented by America/Nuuk, stops observing
    winter time after March 2023, so its daylight saving time becomes
    standard time.  (Thanks to Jonas Nyrup and Jürgen Appel.)
      
This means, that this issue has to be re-evaluated, once the 
'Release 2022g' of the iana zoneinfo is available.
'dpkg --list | grep tzdata' shows on an up-to-date Ubuntu 22.04
'2022f-0ubuntu0.22.04.1'.

Since python 3.9, support for timezones (3) is included in
the standard installation, a backport for python 3.6+ is
available at pypi.org (4).
See issue #675 for the implementation of this task.


(1) https://datatracker.ietf.org/doc/html/rfc8536
    February 2019
(2) https://data.iana.org/time-zones/tzdb/NEWS
    Release 2022g - 2022-11-29 08:58:31 -0800
(3) https://docs.python.org/3/library/zoneinfo.html
(4) https://pypi.org/project/backports.zoneinfo/

**Comment by SteveErl** [comment]
It's good that you've fixed this integer division bug, but even with that, timezone data version 3 is still not supported. 
```
140     def _process(self, fd, version=1, skip=False):
141         from struct import unpack, calcsize
142         if version == 1:
143             ttmfmt = '!l'
144             lfmt = '!ll'
145         elif version == 2:
146             ttmfmt = '!q'
147             lfmt = '!ql'
148 
```
I think we need something like
```
149         elif version == 3:
150             ttmfmt = '!q'
151             lfmt = '!ql'
```

but that's not enough, because my example still fails when the timezone is Asia/Jerusalem, which uses version 3. My test version of tvmaze.py has an extra debug message to show the country data.

```
$ programs/scripts/metadata/Television/tvmaze.py --debug  -N "The Masked Singer" "2022-11-24 19:00:00"
Args:  ['The Masked Singer', '2022-11-24 19:00:00']
Opts:  {'version': False, 'test': False, 'tvlist': False, 'tvdata': False, 'collectiondata': False, 'tvnumbers': True, 'language': 'en', 'country': None, 'debug': True, 'doctest': False}
Function 'buildNumbers' called with arguments: 'The Masked Singer' '2022-11-24 19:00:00'
country = {'name': 'United States', 'code': 'US', 'timezone': 'America/New_York'}, show_tz =America/New_York
ep.airtime = 20:00, ep.airdate = 2022-11-24, ep.timestamp = 2022-11-25T01:00:00+00:00
Recording matches 'S8E10 Battle of the Semi Finals' at 2022-11-25 01:00:00+00:00
country = {'name': 'United Kingdom', 'code': 'GB', 'timezone': 'Europe/London'}
country = {'name': 'Australia', 'code': 'AU', 'timezone': 'Australia/Sydney'}
country = {'name': 'Belgium', 'code': 'BE', 'timezone': 'Europe/Brussels'}
country = {'name': 'Germany', 'code': 'DE', 'timezone': 'Europe/Busingen'}
country = {'name': 'Israel', 'code': 'IL', 'timezone': 'Asia/Jerusalem'}
Traceback (most recent call last):
  File "programs/scripts/metadata/Television/tvmaze.py", line 791, in <module>
    main()
  File "programs/scripts/metadata/Television/tvmaze.py", line 768, in main
    buildNumbers(args, opts)
  File "programs/scripts/metadata/Television/tvmaze.py", line 236, in buildNumbers
    dtInTgtZone = dtInLocalZone.astimezone(posixtzinfo(show_tz))
  File "/usr/lib/python3/dist-packages/MythTV/utility/singleton.py", line 49, in __call__
    inst = type.__call__(cls, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/MythTV/utility/dt.py", line 237, in __init__
    self._process(fd, version)
  File "/usr/lib/python3/dist-packages/MythTV/utility/dt.py", line 181, in _process
    raise e
  File "/usr/lib/python3/dist-packages/MythTV/utility/dt.py", line 173, in _process
    tt = time.gmtime(t)
OSError: [Errno 75] Value too large for defined data type
```

It's breaking here...
```
169         for i in range(counts.transitions):  # read in epoch time data
170             t = unpack(ttmfmt, fd.read(calcsize(ttmfmt)))[0]
171 
172             try:
173                 tt = time.gmtime(t)
```

I'm running on a 64-bit version of Linux, but the call to gmtime() fails when 0x30010800001c2000 seconds is passed to it. Maybe this number of seconds is being incorrectly calculated because we're missing handling of something in 'TZ String Extensions'?

**Comment by rcrdnalor** [comment]
Maybe you missed my last commit ? https://github.com/MythTV/mythtv/commit/f43e2f0a36ba577c4c9209887a999bd31a3c49a2

**Comment by SteveErl** [comment]
Sorry, yes, I did. With those commit changes included it does appear to work. I verified with an Israeli episode of The Masked Singer.

```
$ programs/scripts/metadata/Television/tvmaze.py --debug  -N "The Masked Singer" "2020-11-22 15:00:00"
Args:  ['The Masked Singer', '2020-11-22 15:00:00']
Opts:  {'version': False, 'test': False, 'tvlist': False, 'tvdata': False, 'collectiondata': False, 'tvnumbers': True, 'language': 'en', 'country': None, 'debug': True, 'doctest': False}
Function 'buildNumbers' called with arguments: 'The Masked Singer' '2020-11-22 15:00:00'
country = {'name': 'United States', 'code': 'US', 'timezone': 'America/New_York'}, show_tz =America/New_York
country = {'name': 'United Kingdom', 'code': 'GB', 'timezone': 'Europe/London'}, show_tz =Europe/London
country = {'name': 'Australia', 'code': 'AU', 'timezone': 'Australia/Sydney'}, show_tz =Australia/Sydney
country = {'name': 'Belgium', 'code': 'BE', 'timezone': 'Europe/Brussels'}, show_tz =Europe/Brussels
country = {'name': 'Germany', 'code': 'DE', 'timezone': 'Europe/Busingen'}, show_tz =Europe/Busingen
country = {'name': 'Israel', 'code': 'IL', 'timezone': 'Asia/Jerusalem'}, show_tz =Asia/Jerusalem
ep.airtime = , ep.airdate = 2020-11-22, ep.timestamp = 2020-11-22T10:00:00+00:00
Adding episode 'S1E19 #19' to date match list
country = None, show_tz =None
country = {'name': 'Finland', 'code': 'FI', 'timezone': 'Europe/Helsinki'}, show_tz =Europe/Helsinki
country = {'name': 'Mexico', 'code': 'MX', 'timezone': 'America/Monterrey'}, show_tz =America/Monterrey
<?xml version='1.0' encoding='UTF-8'?>
<metadata>
  <item>
    <title>The Masked Singer</title>
    <subtitle>#19</subtitle>
    <description></description>
    <season>1</season>
    <episode>19</episode>
    <inetref>52045</inetref>
    <collectionref>52045</collectionref>
    <language>he</language>
    <releasedate>2020-11-22</releasedate>
    <popularity>20.0</popularity>
    <year>2020</year>
    <runtime>90</runtime>
    <studios>
      <studio name="Keshet 12"/>
    </studios>
    <people>
      <person name="Ido Rozenblum" character="Himself" job="Actor"/>
      <person name="Ofira Asayag" character="Herself" job="Actor"/>
    </people>
    <images>
      <image type="fanart" url="https://static.tvmaze.com/uploads/images/original_untouched/284/711315.jpg"/>
    </images>
  </item>
</metadata>
```

Thanks. Good job!
