### ISSUE TITLE
 Update to python3-mysqlclient conflicts with python3-mysql 

### ISSUE THREAD

**Issue by candelab** [MythTV/mythtv#679]
* **Platform**:
 Intel 64 Bit

* **MythTV version**:
see below
* **Package version**:
see below
* **Component**:
see below
### What steps will reproduce the bug?
dnf update mythtv
Here's the fedora report:
https://ask.fedoraproject.org/t/update-to-python3-mysqlclient-conflicts-with-python3-mysql/29896

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/II7NZSUVHLT4ITT6AUWHCZUDGR4TFRYX/

And the redhat orig from Feb 2021:
https://bugzilla.redhat.com/show_bug.cgi?id=1929101

Update to python3-mysqlclient conflicts with python3-mysql 
### What is the expected behaviour?
Upgrade 

### What do you see instead?
dnf update 'mythtv'
Last metadata expiration check: 2:20:13 ago on Thu 15 Dec 2022 12:27:41 PM EST.
Dependencies resolved.
===============================================================================
 Package             Arch   Version               Repository              Size
===============================================================================
Upgrading:
 mytharchive         x86_64 32.0-6.76.20221129git44f88ed468.fc36
                                                  rpmfusion-free-updates  12 M
 mythbrowser         x86_64 32.0-6.76.20221129git44f88ed468.fc36
                                                  rpmfusion-free-updates 106 k
 mythffmpeg          x86_64 32.0-6.76.20221129git44f88ed468.fc36
                                                  rpmfusion-free-updates 8.3 M
 mythgame            x86_64 32.0-6.76.20221129git44f88ed468.fc36
                                                  rpmfusion-free-updates 179 k
 mythmusic           x86_64 32.0-6.76.20221129git44f88ed468.fc36
                                                  rpmfusion-free-updates 644 k
 mythnews            x86_64 32.0-6.76.20221129git44f88ed468.fc36
                                                  rpmfusion-free-updates 111 k
 mythplugins         x86_64 32.0-6.76.20221129git44f88ed468.fc36
                                                  rpmfusion-free-updates  11 k
 mythtv              x86_64 32.0-6.76.20221129git44f88ed468.fc36
                                                  rpmfusion-free-updates  26 k
 mythtv-backend      x86_64 32.0-6.76.20221129git44f88ed468.fc36
                                                  rpmfusion-free-updates 7.7 M
 mythtv-base-themes  x86_64 32.0-6.76.20221129git44f88ed468.fc36
                                                  rpmfusion-free-updates  13 M
 mythtv-common       x86_64 32.0-6.76.20221129git44f88ed468.fc36
                                                  rpmfusion-free-updates 4.4 M
 mythtv-docs         noarch 32.0-6.76.20221129git44f88ed468.fc36
                                                  rpmfusion-free-updates 114 k
 mythtv-frontend     x86_64 32.0-6.76.20221129git44f88ed468.fc36
                                                  rpmfusion-free-updates  12 M
 mythtv-libs         x86_64 32.0-6.76.20221129git44f88ed468.fc36
                                                  rpmfusion-free-updates 8.3 M
 mythtv-setup        x86_64 32.0-6.76.20221129git44f88ed468.fc36
                                                  rpmfusion-free-updates 143 k
 mythweather         x86_64 32.0-6.76.20221129git44f88ed468.fc36
                                                  rpmfusion-free-updates 412 k
 mythzoneminder      x86_64 32.0-6.76.20221129git44f88ed468.fc36
                                                  rpmfusion-free-updates 175 k
 perl-MythTV         noarch 32.0-6.76.20221129git44f88ed468.fc36
                                                  rpmfusion-free-updates  32 k
 php-MythTV          noarch 32.0-6.76.20221129git44f88ed468.fc36
                                                  rpmfusion-free-updates  22 k
 python3-MythTV      noarch 32.0-6.76.20221129git44f88ed468.fc36
                                                  rpmfusion-free-updates 335 k
Installing dependencies:
 python3-mysqlclient x86_64 2.0.3-4.fc36          fedora                  89 k

Transaction Summary
===============================================================================
Install   1 Package
Upgrade  20 Packages

Total download size: 68 M
Is this ok [y/N]: y
Downloading Packages:
(1/21): python3-mysqlclient-2.0.3-4.fc36.x86_6 170 kB/s |  89 kB     00:00    
(2/21): mythbrowser-32.0-6.76.20221129git44f88 198 kB/s | 106 kB     00:00    
(3/21): mythgame-32.0-6.76.20221129git44f88ed4 770 kB/s | 179 kB     00:00    
(4/21): mythmusic-32.0-6.76.20221129git44f88ed 2.4 MB/s | 644 kB     00:00    
(5/21): mythnews-32.0-6.76.20221129git44f88ed4 1.1 MB/s | 111 kB     00:00    
(6/21): mytharchive-32.0-6.76.20221129git44f88 9.6 MB/s |  12 MB     00:01    
(7/21): mythplugins-32.0-6.76.20221129git44f88  85 kB/s |  11 kB     00:00    
(8/21): mythtv-32.0-6.76.20221129git44f88ed468 294 kB/s |  26 kB     00:00    
(9/21): mythffmpeg-32.0-6.76.20221129git44f88e 7.2 MB/s | 8.3 MB     00:01    
(10/21): mythtv-backend-32.0-6.76.20221129git4  14 MB/s | 7.7 MB     00:00    
(11/21): mythtv-docs-32.0-6.76.20221129git44f8 1.1 MB/s | 114 kB     00:00    
(12/21): mythtv-common-32.0-6.76.20221129git44  14 MB/s | 4.4 MB     00:00    
(13/21): mythtv-base-themes-32.0-6.76.20221129  18 MB/s |  13 MB     00:00    
(14/21): mythtv-setup-32.0-6.76.20221129git44f 1.4 MB/s | 143 kB     00:00    
(15/21): mythweather-32.0-6.76.20221129git44f8 3.8 MB/s | 412 kB     00:00    
(16/21): mythtv-libs-32.0-6.76.20221129git44f8  20 MB/s | 8.3 MB     00:00    
(17/21): mythzoneminder-32.0-6.76.20221129git4 1.4 MB/s | 175 kB     00:00    
(18/21): mythtv-frontend-32.0-6.76.20221129git  19 MB/s |  12 MB     00:00    
(19/21): php-MythTV-32.0-6.76.20221129git44f88 159 kB/s |  22 kB     00:00    
(20/21): perl-MythTV-32.0-6.76.20221129git44f8 208 kB/s |  32 kB     00:00    
(21/21): python3-MythTV-32.0-6.76.20221129git4 3.3 MB/s | 335 kB     00:00    
-------------------------------------------------------------------------------
Total                                           19 MB/s |  68 MB     00:03     
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction test error:
  file /usr/lib64/python3.10/site-packages/MySQLdb/__init__.py from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/__pycache__/__init__.cpython-310.opt-1.pyc from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/__pycache__/__init__.cpython-310.pyc from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/__pycache__/_exceptions.cpython-310.opt-1.pyc from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/__pycache__/_exceptions.cpython-310.pyc from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/__pycache__/connections.cpython-310.opt-1.pyc from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/__pycache__/connections.cpython-310.pyc from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/__pycache__/converters.cpython-310.opt-1.pyc from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/__pycache__/converters.cpython-310.pyc from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/__pycache__/cursors.cpython-310.opt-1.pyc from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/__pycache__/cursors.cpython-310.pyc from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/__pycache__/release.cpython-310.opt-1.pyc from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/__pycache__/release.cpython-310.pyc from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/__pycache__/times.cpython-310.opt-1.pyc from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/__pycache__/times.cpython-310.pyc from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/_exceptions.py from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/_mysql.cpython-310-x86_64-linux-gnu.so from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/connections.py from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/constants/CLIENT.py from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/constants/CR.py from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/constants/ER.py from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/constants/__init__.py from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/constants/__pycache__/CLIENT.cpython-310.opt-1.pyc from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/constants/__pycache__/CLIENT.cpython-310.pyc from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/constants/__pycache__/CR.cpython-310.opt-1.pyc from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/constants/__pycache__/CR.cpython-310.pyc from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/constants/__pycache__/ER.cpython-310.opt-1.pyc from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/constants/__pycache__/ER.cpython-310.pyc from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/constants/__pycache__/FIELD_TYPE.cpython-310.opt-1.pyc from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/constants/__pycache__/FIELD_TYPE.cpython-310.pyc from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/constants/__pycache__/FLAG.cpython-310.opt-1.pyc from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/constants/__pycache__/FLAG.cpython-310.pyc from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/constants/__pycache__/__init__.cpython-310.opt-1.pyc from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/constants/__pycache__/__init__.cpython-310.pyc from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/converters.py from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/cursors.py from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/release.py from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64
  file /usr/lib64/python3.10/site-packages/MySQLdb/times.py from install of python3-mysqlclient-2.0.3-4.fc36.x86_64 conflicts with file from package python3-mysql-1.4.6-9.fc36.x86_64

**Comment by garybuhrmaster** [comment]
This is not a MythTV issue.  It is an issue upstream (and should be closed accordingly).  This was a result of the RPMFusion maintainer apparently changing requirements (and then apparently not testing the upgrade path) combined with the open upstream bug https://bugzilla.redhat.com/show_bug.cgi?id=1929101

You should, however, consider opening a RPMFusion bug to remind the maintainer of QA.

Instructions as to how to deal with the issue have been posted on the mythtv-users list.

**Comment by candelab** [comment]
Thanks thought I would share. Can you point me to the link where the workaround is?

**Comment by candelab** [comment]
http://lists.mythtv.org/pipermail/mythtv-users/2022-December/410863.html
from "Chris":


I performed the ugprade using these commands in "dnf shell":

> remove python3-mysql
> install python3-mysqlclient
> upgrade
> run

Works great
