### ISSUE TITLE
Sony Bravia DLNA - Can not seek in recording. Faulty duration format

### ISSUE THREAD

**Issue by mholmqvist** [MythTV/mythtv#687]
* **Platform**:  Ubuntu 22.04.1

* **MythTV version**: Mythtv 2:32.0+fixes.202212280105.1efbcb1493~ubuntu22.04.1

* **Package version**: 2:32.0+fixes.202212280105.1efbcb1493~ubuntu22.04.1

* **Component**: libmythupnp  

### What steps will reproduce the bug?
Seek, forward / backward worked on Mythtv 31. Since 32 it  "response content not supporting operations"

### How often does it reproduce? Is there a required condition?
All the time.

### What is the expected behaviour?
That it's possible to seek with the TV remote control.

### What do you see instead?
Seek not supported.

### Additional information

I traced and compared the DLNA trafic on myth31 and myth32 to understant the differnce.

The observation was a different format of the duration attrbute. 

```
myth31: 
<res  protocolInfo="http-get:*:video/mpeg:DLNA.ORG_PN=AVC_TS_EU_ISO;DLNA.ORG_OP=01;DLNA.ORG_FLAGS=22020096000000000000000000000000" duration="1:50:00.0" resolution="1280x720" size="6767156068">http://10.1.1.116:6544/Content/GetRecording?RecordedId=4422</res>
```

```
myth32:
<res protocolInfo="http-get:*:video/mpeg:DLNA.ORG_PN=MPEG_TS_SD_EU_ISO;DLNA.ORG_OP=01;DLNA.ORG_FLAGS=22020096000000000000000000000000" duration="1:50:00:000" resolution="1280x720" size="6767156068">http://10.1.1.116:6544/Content/GetRecording?RecordedId=4422</res>
```

According to the didl-lite  xml schema duration should have a decimal dot as separator between seconds and fraction

         The 'duration' attribute identifies the duration of the playback of the resource, at normal speed.
                    The form of the duration string is: H*:MM:SS.F*, or H*:MM:SS.F0/F1 where :
                    H* means any number of digits (including no digits) to indicate elapsed hours
                    MM means exactly 2 digits to indicate minutes (00 to 59)
                    SS means exactly 2 digits to indicate seconds (00 to 59)
                    F* means any number of digits (including no digits) to indicate fractions of seconds
                    F0/F1 means a fraction, with F0 and F1 at least one digit long, and F

**Comment by mholmqvist** [comment]
Corrected in PR  https://github.com/MythTV/mythtv/pull/688

**Comment by linuxdude42** [comment]
I merged the pull request, and cherry-picked it into v32.
