### ISSUE TITLE
Mythfrontend crashes when playing a radio station (live or a recording) in fixes/32

### ISSUE THREAD

**Issue by TheGorbag** [MythTV/mythtv#689]
* **Platform**: Gentoo, Linux feynman 5.15.80-gentoo #1 SMP Wed Nov 30 09:56:12 GMT 2022 x86_64 Intel(R) Core(TM) i3 CPU 550 @ 3.20GHz GenuineIntel GNU/Linux

* **MythTV version**: fixes/32, v32.0-ba52c132238

* **Package version**:

* **Component**: frontend

### What steps will reproduce the bug?

Play a recording of a radio programme. This is from Freeview (DVB-T) in the UK.

Also happens when playing a radio station live.

### How often does it reproduce? Is there a required condition?

It always happens

### What is the expected behaviour?

The radio recording or station plays.

### What do you see instead?

mythfrontend crashes.

### Additional information

I have investigated using gdb. The crash occurs on line 112 of mythtv/libs/libmythtv/DetectLetterbox.cpp in function DetectLetterbox::Detect:

    // Establish the level of light in the edge
    int averageY = 0;
    for (int pos : xPos)
    {
        averageY += buf[offsets[0] + 5 * pitches[0]            + pos];
        averageY += buf[offsets[0] + (height - 6) * pitches[0] + pos];
    }

because buf is NULL.

Comparing the code with that in fixes/31 which works fine the older version had code like this at the start of the function. This stops it doing anything if there is no video, which would be the case for radio:

    if (!m_player->GetVideoOutput())
        return;

that code no longer exists in fixes/32. The function GetVideoOutput()  has been removed from fixes/32 due to the rewrite of mythplayerui.cpp. It appears to have been replaced by FlagIsSet(kVideoIsNull) which is not available in DetectLetterbox::Detect. So I have solved the problem by simply checking that buf is not NULL. This can be seen in the attached patch.

**Comment by TheGorbag** [comment]
I could not get github to accept the patch as a attachment, so I include it as text here:

`diff --git a/mythtv/libs/libmythtv/DetectLetterbox.cpp b/mythtv/libs/libmythtv/DetectLetterbox.cpp
index a92a262a26..2d2aa5b8fd 100644
--- a/mythtv/libs/libmythtv/DetectLetterbox.cpp
+++ b/mythtv/libs/libmythtv/DetectLetterbox.cpp
@@ -30,6 +30,9 @@ bool DetectLetterbox::Detect(MythVideoFrame *Frame, float VideoAspect, AdjustFil
         return false;
 
     unsigned char *buf = Frame->m_buffer;
+    if (!buf)
+        return false;
+
     const FramePitches pitches = Frame->m_pitches;
     const FrameOffsets offsets = Frame->m_offsets;
     const int height = Frame->m_height;
`

**Comment by Jpilk** [comment]
In the last 14 months I have made over 5000 DVB-T radio recordings, mostly from the BBC.  But I see that  Klaas is on the case....

**Comment by kmdewaal** [comment]
I tried this with DVB radio from FreeSat/Astra-2, channel Classic FM, but it did not crash here. There are however many issues with DVB radio and this really needs a complete overhaul but until then I am happy to apply a band-aid now and then.

Fix will be backported to fixes/32 in a few days .
