### ISSUE TITLE
etree.tostring() returning a byte string in database.py

### ISSUE THREAD

**Issue by fe31nz** [MythTV/mythtv#707]
Platform:
Ubuntu 22.04.1 just upgraded from 20.04
Linux mypvr 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

MythTV version:
MythTV Version : v32.0+fixes.202301292148.749472ba33~ubuntu22.04.1
MythTV Branch : fixes/32
Network Protocol : 91
Library API : 32.20200101-1
QT Version : 5.15.3
Options compiled in:
 linux profile use_hidesyms using_alsa using_oss using_pulse using_pulseoutput using_backend using_bindings_perl using_bindings_python using_bindings_php using_dvb using_firewire using_frontend using_hdhomerun using_satip using_vbox using_ceton using_joystick_menu using_libcec using_libcrypto using_gnutls using_libdns_sd using_libfftw3 using_libxml2 using_lirc using_mheg using_opengl using_egl using_qtwebkit using_qtscript using_qtdbus using_taglib using_v4l2 using_v4l2prime using_x11 using_system_libbluray using_system_libudfread using_systemd_notify using_systemd_journal using_drm using_bindings_perl using_bindings_python using_bindings_php using_freetype2 using_mythtranscode using_opengl using_egl using_drm using_vaapi using_nvdec using_vdpau using_ffmpeg_threads using_mheg using_libass using_libxml2 using_libmp3lame

Component:
MythTV Python bindings, file database.py

### What steps will reproduce the bug?
Get a copy of my gaps program here:

http://www.jsw.gen.nz/mythtv/gaps

On an Ubuntu 22.04 system with MythTV v32, and no /root/.mythtv/config.xml file, run gaps from a root terminal.  It will report:

Unable to get BackendStatusPort settings from MythTV database, using defaults

and will then connect using default localhost:6554 settings.  That message is produced by a print() at about line 156 where it handles an exception from the MythTV Python bindings.  If you add these two lines after that line:

        import traceback
        traceback.print_exc()

and run it again, you will get a traceback telling you what the real problem is:

Unable to get BackendStatusPort settings from MythTV database, using defaults
Traceback (most recent call last):
  File "/root/temp/temp/./gaps", line 145, in <module>
    db = MythTV.MythDB()
  File "/usr/lib/python3/dist-packages/MythTV/database.py", line 1281, in __init__
    self.dbconfig.writeXML(self.log)
  File "/usr/lib/python3/dist-packages/MythTV/database.py", line 1074, in writeXML
    fp.write(etree.tostring(doc, pretty_print=True))
TypeError: write() argument must be str, not bytes

So the problem is line 1074 in database.py:

        fp.write(etree.tostring(doc, pretty_print=True))

which has not been converted from Python 2 to Python 3.  It should read:

        fp.write(etree.tostring(doc, encoding='unicode', pretty_print=True))

**Comment by Jpilk** [comment]
I haven't knowingly experienced this issue, but have made the equivalent change in my Fedora 36 system 

/usr/lib/python3.10/site-packages/MythTV/database.py

without apparent problems.

**Comment by Jpilk** [comment]
More generally useful would be this reference to the git download:

/mythtv/bindings/python/MythTV/database.py 

but   '2to3 -w database.py'  

suggests many more changes in this file.   I haven't tried it for others in that folder. Should they have been applied?

**Comment by fe31nz** [comment]
The piece of code where the problem is does not get used much - otherwise other people would have had problems.  It writes out a new config.xml if it can not find any login credentials anywhere it has searched for them.  The problem with etree.tostring() in Python 3 is a bit of an abomination as it does not follow the normal Python rules - it apparently works as it does only for Python 2 compatibility.

I tried 2to3 on database.py and got lots of places where it wanted to apply list().  The explanation for this can be found here:

https://stackoverflow.com/questions/27476079/why-does-2to3-change-mydict-keys-to-listmydict-keys

I have not gone through all of database.py, but I do not think it needs any of those list() changes, or I would have had problems with it before now.  I am sure that most of the code for the Python bindings will report the same sort of recommended but unnecessary changes from 2to3 also.

**Comment by rcrdnalor** [comment]
There are a lot of tests for python3 in https://github.com/rcrdnalor/MythTV-Python-Tests
which built the base of the initial python 2 to 3 conversion of the MythTV's python bindings.
You need to to download a tarball of https://github.com/rcrdnalor/MythTV-Python-Tests
and open `MythTV-Python-Tests/coverage_reports_python3/htmlcov/index.html` ,
then select `dataheap_py`
The path which is mentioned by the OP is not tested.

**Comment by rcrdnalor** [comment]
Fixed in https://github.com/MythTV/mythtv/commit/4f01f0ad0cf132798dc61323f0da3c1aa9fbee07
