### ISSUE TITLE
mythnetvision needs to be updated to support python-oauthlib rather than python-oauth

### ISSUE THREAD

**Issue by garybuhrmaster** [MythTV/mythtv#713]
This is really a future developer task (although I can't assign the task:developer label), but I did not want the discussion from July 2022 which included a comment by stuarta to be lost:

```
I've just fixed the same issue with the github workflow.
There is no python3-oauth package in ubuntu-22.04 (or derivatives)

The replacement appears to be python3-oauthlib, but mythnetvision
will require coding changes to be able to use it.
```

**Comment by rcrdnalor** [comment]
It looks like that mythnetvision is only using its own implementation of oauth. See
https://github.com/MythTV/mythtv/blob/c2d2e1ab996eb294b5087885a9ec80ed14ee41a1/mythtv/programs/scripts/internetcontent/nv_python_libs/vimeo/vimeo_api.py#L63
and
https://github.com/MythTV/mythtv/blob/master/mythtv/programs/scripts/internetcontent/nv_python_libs/vimeo/oauth/oauth_api.py

In other words, neither the python3-oauth packages is used, nor the python-oauthlib package is needed.

**Comment by garybuhrmaster** [comment]
> In other words, neither the python3-oauth package is used, nor the python-oauthlib package is needed.

In which case the developer task would be to remove the check in the plugins configure that disables mythnetvision if oauth is not available.
