### ISSUE TITLE
Services API ChannelInfo does not include RecPriority

### ISSUE THREAD

**Issue by gigem** [MythTV/mythtv#714]
* **Platform**: All

* **MythTV version**: All

* **Package version**: All

* **Component**: Services API

### What steps will reproduce the bug?

Query any ChannelInfo using the services API.

### How often does it reproduce? Is there a required condition?

Always.

### What is the expected behaviour?

The returned ChannelInfo should include a RecPriority member.

### What do you see instead?

A ChannelInfo with no RecPriority member.

**Comment by bennettpeter** [comment]
From the comments I assume that you only want RecPriority in the GetChannelInfo and GetChannelInfoList.

I am not adding it to the AddDBChannel or UpdateDBChannel. Let me know if you need those.

**Comment by gigem** [comment]
On Wed, Feb 08, 2023 at 05:28:54PM -0800, Peter Bennett wrote:
> From the comments I assume that you only want RecPriority in the GetChannelInfo and GetChannelInfoList.
> 
> I am not adding it to the AddDBChannel or UpdateDBChannel. Let me know if you need those.

If RecPriority is added, which is what I want, it should be added
everywhere.  Anything that can be configured using mythtv-setup should
also be configurable through the API.

FWIW, my current use case will only warn me when the channel priority
doesn't match my desired, business rules.  I might eventually make it
also make the required change in the future.

David
-- 
David Engel
***@***.***
