### ISSUE TITLE
Themes and theme list fail to download for pre-release builds

### ISSUE THREAD

**Issue by mspieth** [MythTV/mythtv#720]
* **Platform**:
All

* **MythTV version**:
latest master

* **Package version**:

* **Component**:
Theme Chooser

### What steps will reproduce the bug?
Build a prerelease which is version 34 currently and attempt to load a new theme that is not already downloaded

A popup appears saying the theme failed to download. 
If the theme list needs to be updated, it fails to get the theme list too.

### How often does it reproduce? Is there a required condition?
Every time

### What is the expected behaviour?
Theme and theme list should be obtained from trunk if the specific version is not available

### Additional information
This is only a problem for those that run pre-releases in their early incarnations.

**Comment by mspieth** [comment]
Fix pushed. Tested on android frontend

**Comment by linuxdude42** [comment]
I suspect that its a bad git tag, but this fix doesn't hurt.

**Comment by paul-h** [comment]
Congratulations you win the award for the messiest commit ever in the history of MythTV :)

**Comment by bennettpeter** [comment]
I Tested successfully on master.

**Comment by mspieth** [comment]
Apologies for the double commit. I missed a final squash.
And VSCode did the reformat. We should have a .clangformat file. That would fix this in the future.

**Comment by linuxdude42** [comment]
Ooh. Clang-format. Tempting. :-)
