### ISSUE TITLE
Debian Header Dependency Fails

### ISSUE THREAD

**Issue by ISO8807** [MythTV/mythtv#726]
* **Platform**: Debian 11.6 (amd64)

* **MythTV version**: 33.1

* **Package version**:

* **Component**:

### What steps will reproduce the bug?

Follow the instructions at https://www.mythtv.org/wiki/Installing_MythTV_on_Debian and install dependencies. In passing, the page lists dependencies only up to version 32 and not later.

### How often does it reproduce? Is there a required condition?

Always.

### What is the expected behaviour?

Configure should find the appropriate Linux kernel headers and complete its work.

### What do you see instead?

Configure fails to find the "linux-kernel-headers:amd64" package.

### Additional information

As far as I can see, configure should be expecting (for example) "linux-headers-5.10.0-21-amd64.deb". That is, the kernel version is part of the package name.

**Comment by rcrdnalor** [comment]
The generic package you are looking for is for Debian and for Ubuntu 'linux-headers-generic', see
https://packages.debian.org/bullseye/linux-headers-generic
https://packages.ubuntu.com/search?keywords=linux-headers-generic

Feel free to update the wiki accordingly.
Or consider 'ansible' at https://github.com/MythTV/ansible for installing dependencies.

MythTV has an excellent support forum at https://forum.mythtv.org/ where such questions will be answered usually at the same day.
