### ISSUE TITLE
Database Connection Fails Using mythtv-setup

### ISSUE THREAD

**Issue by ISO8807** [MythTV/mythtv#728]
* **Platform**: Debian 11.6 (amd64)

* **MythTV version**: 33.1

* **Package version**:

* **Component**:

### What steps will reproduce the bug?

Having completed the build and installation, I had to guess that mythtv-setup was the first thing to use.

### How often does it reproduce? Is there a required condition?

Always.

### What is the expected behaviour?

mythtv-setup should find a database already set up for it.

### What do you see instead?

mythtv-setup says that it cannot connect to the database and lists the parameters it is using.

### Additional information

It looks like MySQL (MaridaDB) should have been set up. However, this is not in the dependencies. I installed it, and manually set up a database and user for MythTV.

I would have expected this to all be done automatically. Perhaps there is some script I missed, or something automatic that didn't run?

**Comment by ISO8807** [comment]
What I needed is in fact well documented at the end of https://www.mythtv.org/wiki/Build_from_Source#Installing_Build_Dependencies_without_Ansible but I'd missed this because it appeared to be part of the MythWeb setup. Sorry for the false alarm.

It would nonetheless be useful if a `mysql` dependency were in the list (much as `build-essential` is).

**Comment by garybuhrmaster** [comment]
> It would nonetheless be useful if a `mysql` dependency were in the list (much as `build-essential` is).

The wiki is not always as clearly written or organized as someone may prefer.

Fortunately, you (and the entire community) can edit the wiki and make it better by editing it, so please do consider doing so (if you do not have a wiki account, you may need to create one).

**Comment by ISO8807** [comment]
Actually, the more I read of the Wiki the more I'm impressed as to the amount of useful information it presents. I hadn't realised that ordinary users could apply to edit the Wiki, so I'll bear that in mind.

**Comment by kmdewaal** [comment]
The section about the sql server has now a caption of its own so it does stand out a bit and is not as easy overlooked anymore. Thanks for reporting. Ticket is now closed.
