### ISSUE TITLE
Connection Failure to LIRC

### ISSUE THREAD

**Issue by ISO8807** [MythTV/mythtv#729]
* **Platform**: Debian 11.6 (amd64)

* **MythTV version**: 33.1

* **Package version**:

* **Component**:

### What steps will reproduce the bug?

Build and install MythTV by following the instructions at https://www.mythtv.org/wiki/Installing_MythTV_on_Debian and installing dependencies. Manually install MySQL (MariaDB) and create a database and user for MythTV. Then run mythtv-setup. Select language and country.

### How often does it reproduce? Is there a required condition?

Always.

### What is the expected behaviour?

Having selected language and country, mythtv-setup exits. I presume it should go on to do something useful (e.g. to allow a TV tuner to be set up).

### What do you see instead?

After the initial run to set up country and language, mythtv-setup does not bring up a graphical interface (which I presume is expected). The console log says:

2023-02-26 11:04:54.928923 E  LIRC: Failed to connect to Unix socket '/var/run/lirc/lircd' eno: No such file or directory (2)

### Additional information

Indeed there is no such directory and LIRC isn't running. Is this something that should have been set up  automatically? I don't see any build dependency for this.

**Comment by ISO8807** [comment]
As far as I can see,, the absence of LIRC shouldn't be critical so I'll presume this error can be ignored.

**Comment by billmeek** [comment]
Correct. Or, start the backend with the **--override-setting libCECEnabled=0** switch if LIRC isn't used.

**Comment by ISO8807** [comment]
Ah. Thank you for the clarification.
