### ISSUE TITLE
Translations: update mythfrontend_en_us.ts for v33

### ISSUE THREAD

**Issue by brfransen** [MythTV/mythtv#732]
Update mythfrontend_en_us.ts for v33 and fix display issues with help icons. Also removed the vanished items.
[mythfrontend_en_us.ts_Title_Case.patch](https://github.com/MythTV/mythtv/files/10984647/mythfrontend_en_us.ts_Title_Case.patch)

**Comment by linuxdude42** [comment]
Sorry to take so long to review. It looks like this file hasn't been translated in a long time.  Most of the changes look ok. 
A number of the items weren't translated but you removed the "unfinished" tag. Was this intentional? I believe that means the original text is used untranslated.

**Comment by brfransen** [comment]
Yes it was intentional to remove the unfinished tag. For the en_us translation many of the original texts are appropriate.

**Comment by linuxdude42** [comment]
How would you like the author listing in the commit message?

**Comment by brfransen** [comment]
Britney Fransen
