### ISSUE TITLE
Services API inconsistent results

### ISSUE THREAD

**Issue by bennettpeter** [MythTV/mythtv#740]
The API Dvr/GetUpcomingList returns different results in json output vs xml output. The field "Status" is an enum. The xml result contains the enum value name, and the json result contains the enum numeric value:

xml run
`<Status>WillRecord</Status>`

json run
` "Status": "-1",`

This is unacceptable and confusing. The problem exists with both old (port 6544) and new (port 6744) web server.

This also affects other calls that return Recording information, for example GetRecordedList, GetConflictList

I recommend changing to use the numeric values rather than the enum names. This may impact users who already use the API in xml mode. My reasoning is that there is already an API call to get the localized name for the status code (RecStatusToString) but there is no way to get a localized description from the enum name.

Please let me know what your thoughts are before I proceed.

**Comment by kmdewaal** [comment]
I recommend to always use the string representation, like "WillRecord" and not "-1", for both JSON and XML.
The numeric representation should be purely internal and even for C/C++ code the rule is that it should never depend on the numeric value.

**Comment by bennettpeter** [comment]
If I use the string representation, then I will need to change the associated APIS (e.g. RecStatusToString) to take the string value instead of or as well as the numeric value.

**Comment by paul-h** [comment]
In some other endpoints like GetRecordedList enum's are returned as both the integer and string representations like these :-

```
<ProgramFlags>4101</ProgramFlags>
<ProgramFlagNames>COMMFLAG|AUTOEXP|REPEAT</ProgramFlagNames>
<VideoProps>5</VideoProps>
<VideoPropNames>WIDESCREEN|MPEG2</VideoPropNames>
<AudioProps>1</AudioProps>
<AudioPropNames>STEREO</AudioPropNames>
```

Maybe we should try and continue to do that? We should try and be consistent with how they are represented and also naming conventions where possible/applicable.

**Comment by bennettpeter** [comment]
I can do RecStatus and RecStatusName, with both xml and json having the same values.

Current users of xml would be affected, they would get numeric values where they previously got names. They would need to change to use RecStatusName instead of RecStatus to get the same result.

Anybody have a problem with that?

**Comment by kmdewaal** [comment]
I do not have a problem with numeric values in the API but they should not be the values that the compiler generates for enums.

**Comment by bennettpeter** [comment]
In this case they are not compiler generated, they are hard-coded in recordingstatus.h, so they *SHOULD* not change.

**Comment by bennettpeter** [comment]
> On 3/28/23 11:13, Gary Buhrmaster wrote:

**Comment by bennettpeter** [comment]
This is what I will do:
- Fix the bug in the existing code. The code for xml translates env variables to their names (if they use Q_ENUM), but the code for json does not. I am adding the missing code to the json serializer so that env variables are treated the same in all cases.
- Change the Status field to be an int so that it always returns the numeric value
- Add a field StatusName that is defined as a RecStatus enum and returns the enum value name.
- Change the RecStatusToString and RecStatusToDescription methods to take either the numeric Status value or the enum value name. The parameter will be a string. For http invocation a string is passed in the same way as an int so the change to parameter type will not affect the caller.

If the caller is calling GetUpcomingList or GetRecordScheduleList and then calling RecStatusToString or RecStatusToDescription with the result, they will not be affected.

I do not see a way to continue to return different values in xml and json so as not to impact existing users, because the bug fix prevents that.
