### ISSUE TITLE
[mythvideo]: functional regression: only utf-8 subtitles supported after g9d9e2929ad

### ISSUE THREAD

**Issue by warpme** [MythTV/mythtv#756]
* **Platform**:
MiniMyth2

* **MythTV version**:
current master head (cc0db039e92330d87e2df1e08e3c577dc0afb805)

* **Package version**:

* **Component**:
player

### What steps will reproduce the bug?
play movie with non utf-8 ext.file subtitles

### How often does it reproduce? Is there a required condition?
Always

### What is the expected behaviour?
MythTV before this change allows to use non utf-8 subtitles. It looks now only utf-8 subtitles are supported.
 

### What do you see instead?
With attached windows-1250 encoded subtitles examples no subtitles are displayed.

### Additional information
Issue seems to be functional regression caused switch in 9d9e2929ad3ad6236d3caeec4710b833cd8134e6 and finally removal user setting telling to MythTV what subtitles encoding user uses. 
 

Try play any movie with 2 exemplary subtitles i'm attached here
You will not see subtitles....
Then play with master 93694840a792 - and you will see them correctly.... 

exemplary subtitles for testing:
[The Social Network.txt.zip](https://github.com/MythTV/mythtv/files/11581840/The.Social.Network.txt.zip)
[Beetlejuice.srt.zip](https://github.com/MythTV/mythtv/files/11581842/Beetlejuice.srt.zip)

I think good approach will be to just add back setting telling to MythTV what subtitles encoding user uses - and if it is set to non utf-8 - use i.e. iconv to on-the-fly conversion of user subtiles from setting declared encoding to utf-8.
Proposed approach will:

- keep nice enhancements started with 9d9e2929ad3ad6236d3caeec4710b833cd8134e6
- keep backward compatibility with MythTV functionality before 9d9e2929ad3ad6236d3caeec4710b833cd8134e6
- remove forced conversion of all non utf-8 subtitles to utf-8. (in my case this is approx 650+ movies with windows-1250 encoded subtitles)

**Comment by linuxdude42** [comment]
Are all your subtitle files windows-1250 encoded, or do you have a mix of windows-1250 and utf-8?  FFmpeg can do the conversion, but it has to be specified when the codec is opened.

**Comment by warpme** [comment]
Hi David,

Yes. Indeed - win1250 encoded subs. are not working.
After conversion to utf-8 they starting to work (with #758 issue)
Ideally will be to have encoding auto-conversion from any supported encodings to utf-8. Is it possible?

**Comment by linuxdude42** [comment]
FFmpeg can convert on the fly, if you specify the encoding conversion when the codec is first opened.

What I'm trying to figure out now is whether the subtitles code can always tell FFmpeg to use the encoding specified in the preferences (simple) or it needs to try utf-8 first and then fall back to the specified encoding (harder) like the previous code.

Auto-detection will require something like using a utf-8 codec until a failure occurs, then closing and reopening the codec with the new encoding. At that point should it skip over all of the previously read subtitles, or just flush everything and start over with the new encoding?  Alternatively, if I can find a good programmatic way to detect utf-8 text, then I could inspect the text prior to the initial opening of the codec to determine utf-8/user-encoding.

**Comment by warpme** [comment]
> What I'm trying to figure out now is whether the subtitles code can always tell FFmpeg to use the encoding specified in the preferences (simple) or it needs to try utf-8 first and then fall back to the specified encoding (harder) like the previous code.

try utf-8 first and then fall back to the specified encoding approach will make our lives much easier iirc this will mimic previous behavior (before https://github.com/MythTV/mythtv/commit/9d9e2929ad3ad6236d3caeec4710b833cd8134e6 )
 
> 
> Auto-detection will require something like using a utf-8 codec until a failure occurs, then closing and reopening the codec with the new encoding. At that point should it skip over all of the previously read subtitles, or just flush everything and start over with the new encoding? 
Alternatively, if I can find a good programmatic way to detect utf-8 text, then I could inspect the text prior to the initial opening of the codec to determine utf-8/user-encoding.

Keeping in mind that there is hell of badly encoded subtitles (some national chars have wrong encodings; part of file is with given encoding, other part of file is with another encoding) - i think worth to consider approach might be i.e. like this:

1. implement kind of subtitles encoding detector
2. run it only at playback beginning to probe subtitles file to detect encoding
3. if encoding detected - tell this to ffmpeg.
4. if encoding detection failed - look at user setting for "fallback encodings". If present - use it to ffmpeg
5. if there is no "fallback encodings" - go with utf-8

Ad1: this is exactly like you proposed regarding programmatic way to detect utf-8/user-encoding. Also - from maintainability/extensibility PoV - doing this is dedicated module will allow future detection reliability/intelligence improvements i think)

Ad2: i propose do detection _only_ at playback beginning as this will potentially give immediate feedback to user when subs are wrong. (we may even consider UI pop-up saying: "hey, i can't detect subtitles encodings. May you hint me here?"  

Ad4: this may reduce UX degradation in cases when subtitles encoding detector fails. This might be optional - but i think it is worth to consider. Value from this setting might be used as first entry in p.3 pop-up (for example)

**Comment by warpme** [comment]
Works as expected. 
Many thx!
