### ISSUE TITLE
[mythvideo] make metadatalookup configurable on a per directory basis

### ISSUE THREAD

**Issue by thomasboehm** [MythTV/mythtv#757]
When you store media in your videos storage group (home video, courses, etc.) for which there is no metadata available, then you'll be asked for possible matches again and again if you "scan for changes" in mythfrontend.

One solution could be to place a file like ".nolookup" in a directory and videos in this folder and all subfolders will be excluded fom metadata lookup

Another possible solution is to make it configurable when you add a directory to the video storagegroup.

**Comment by bennettpeter** [comment]
If I don't receive a response to the question I will close this issue.
