### ISSUE TITLE
handleKeyPress of MythMusic Visualizers is never called

### ISSUE THREAD

**Issue by twitham1** [MythTV/mythtv#766]
**Is your feature request related to a problem? Please describe.**

Yes, AlbumArt in visualize.cpp has a "handleKeyPress" intended to cycle art.  It doesn't appear to work.  WaveForm also has one so we can confirm the frontend never calls it like this:

    mythfrontend.real -v playback --runplugin mythmusic

Play music or stream, menu->fullscreen visual, menu->change->waveform

See on the terminal log that WF reported his startup.  Now go push keys like 1, 2, Enter.  See on the terminal the function never reports his LOG("WF keypress").

**Describe the solution you'd like**

It's not clear if this ever worked.  I recursive grep all .cpp and find no code calling handleKeyPress.  Should it be keyPressEvent instead like found many times throughout the code?  If so, I don't know how to get this called either.  Or should visualizers somehow get a new section in the keyboard map?

For WaveForm (#751), I'd like a simple key that can toggle text on/off, SELECT might do just fine.

For Spectrogram (#752) I'd like to toggle Y-axis from Linear to Log to Mel and pixels from mean to peak to total.

**Describe alternatives you've considered**

If visualizers respond to keyboard, they would need to be careful not to override any important keys already assigned to other things by default.

Another option would be for visualizer options to be on the menu instead.  Can the visualizer add his options to the menu?

**Comment by Jpilk** [comment]
I have noticed another keyboard-related feature when using a full-screen visualiser while 'listening to a radio stream' - specifically 'Classic FM' in the UK.

This has a continuously updated station-and-content identifier that is displayed in a popup over the visualiser output.  The only keys that are active are B, which outlines subwindows in the popup, and long-press-Esc, which goes back a few window levels.

It's not a new feature. I see it both with and before  PRs #752 and #771.

**Comment by twitham1** [comment]
> I have noticed another keyboard-related feature when using a full-screen visualiser while 'listening to a radio stream' - specifically 'Classic FM' in the UK.
> 
> This has a continuously updated station-and-content identifier that is displayed in a popup over the visualiser output. The only keys that are active are B, which outlines subwindows in the popup, and long-press-Esc, which goes back a few window levels.

This was likely fixed by #791, please let me know if any issue since then.
