### ISSUE TITLE
[video subtitles]: segfault at end of some videos with external subtitles 

### ISSUE THREAD

**Issue by warpme** [MythTV/mythtv#767]
* **Platform**:
MiniMyth2

* **MythTV version**:
current head

* **Package version**:

* **Component**:
mythplayer

### What steps will reproduce the bug?
play video till end

### How often does it reproduce? Is there a required condition?
always

### What is the expected behaviour?
correct exit to ui menu

gdb trace attached

### What do you see instead?
mythfrontend segfault (gdb output attached)

### Additional information

Segfault start to happen on very recent code.
Testing older versions i see i.e. 1601fc4c86eba926742b1bb4d4409412bc84fc7f works ok

I'm attaching gdb trace (this is from non-debug build. If needed I can rebuild myth with debug symbols)
[Madam Secretary - S02 E19 - Desperate Remedies.srt.zip](https://github.com/MythTV/mythtv/files/11928972/Madam.Secretary.-.S02.E19.-.Desperate.Remedies.srt.zip)
[trap.txt.zip](https://github.com/MythTV/mythtv/files/11928973/trap.txt.zip)
 
Also .srt from move is attached.

**Comment by warpme** [comment]
Small update: bisecting shows this 05ff55b9474dce6ffa86746c216e35b24323b403 commit causes segfaults.

**Comment by linuxdude42** [comment]
This should be fixed. Can you test and verify?

**Comment by warpme** [comment]
David,
Ah sorry for delay (prof.life gets me totally).
It now works perfectly!
Many thx!

btw: some of my users are observing some issues with .mkv build-in subtitles vs. ext. file subtitles (both are displayed and there is no simple way to turn-off this). 
This issue is _not related_ to Your's recent subtitles enhancements. 
Have you energy/time to look on this maybe?
If yes - then i can fill separate bug report.
If not - pls let me know (so i will not spent time on filling bug report which will be not addressed in reasonable time)

**Comment by linuxdude42** [comment]
Please file another bug. It might take me a little while, but I'll look into it.
