### ISSUE TITLE
[subtitles]: .mkv with internal subs + ext.file subs: both subs displyed concurrently 

### ISSUE THREAD

**Issue by warpme** [MythTV/mythtv#773]
* **Platform**:
MiniMyth2

* **MythTV version**:
current head (d3aab1567ed)

* **Package version**:

* **Component**:
video player

### What steps will reproduce the bug?
play sample:
http://warped.inet2.org/ticket.mkv
with subtitles 
http://warped.inet2.org/ticket.txt

sample .mkv has embedded subtitles - but user wants subs with language which is in ext file.
 
### How often does it reproduce? Is there a required condition?
always

### What is the expected behavior?
there should be clear way to ask playback with disabled .mkv embedded subs and enabled ext.file subs.
 

### What do you see instead?

look at picture around 0:04:13 - both subs are displayed: italian subs (from .mkv) and pl subs (from ext file)
User can't easily turn-off italian subs.

**Comment by warpme** [comment]
David,
Any chance to look on this issue?
Practically any user who testing master returns to me with messge:
-double subtitles are show-stopper for further testing of master
-having movie with non utf-8 causing fe crash at playback start

**Comment by warpme** [comment]
IS THERE ANY WAY TO FIX THIS BUG!!!!!! 
OR REVERT CODE CAUSING THIS BUG?

**Comment by warpme** [comment]
Peter,
I see exactly the same behavior....
btw: in my case - after p3 - subtitles stops to displaying after minute or so

**Comment by bennettpeter** [comment]
I committed a fix for this in b47e46482. Please test it and let me know if there are any issues remaining.
With the fixed code I could not reproduce subtitles disappearing after a minute. The test video is about 5 minutes and the subtitles  continue to work for that time. Please test with a longer video.

**Comment by warpme** [comment]
Peter,
Now works perfectly!
Many, many thx!
