### ISSUE TITLE
[python bindings]: regression: 8b59a835167d8f3cf breaks well working lossless_cut

### ISSUE THREAD

**Issue by warpme** [MythTV/mythtv#797]
* **Platform**:
ArchLinux
* **MythTV version**:
current head
* **Package version**:

* **Component**:
python bindings
### What steps will reproduce the bug?
run https://github.com/warpme/lossless_cut

I'm using lossless_cut to export recordings as .mkv
### How often does it reproduce? Is there a required condition?
always
### What is the expected behaviour?
correct operation

### What do you see instead?
starting lossless_cut results with script exception

### Additional information

revering https://github.com/MythTV/mythtv/commit/8b59a835167d8f3cfa6a6e14022082221e0bce12 brings lossless_cut working again ok

**Comment by rcrdnalor** [comment]
@warpme  Could you please check this commit ? https://github.com/MythTV/mythtv/commit/f818befd5ebe1c6234b481bba36f89a5085a2e34

**Comment by warpme** [comment]
Roland,
Works perfectly now.
many Thx!
