### ISSUE TITLE
macOS: linker error (starting in ffmpeg) with Xcode 15

### ISSUE THREAD

**Issue by jhoyt4** [MythTV/mythtv#808]
With the introduction to Xcode 15, Apple has moved to a new linker and introduced the "-ld_classic" linker flag as a work around.  Without this flag, FFMPEG fails to compile on systems with Xcode 15 (i.e. Sonoma) and possibly beyond.

I've successfully tested a fix at compile time by adding this line to the compile script (or manually in the shell)
`export LDFLAGS="$LDFLAGS -Wl,-ld_classic"`

* **Platform**: macOS 14.0 (Sonoma) with Xcode 15 (arm64 and X86_64)

* **MythTV version**: fixes/33 and master

* **Package version**:

* **Component**:ffmpeg

### What steps will reproduce the bug?

Attempt to compile MythTV either manually or with the "compileMythfrontendAnsible.zsh" script in packaging.

### How often does it reproduce? Is there a required condition?

Every time with Xcode 15

### What is the expected behaviour?

Successful compilation.

### What do you see instead?

Logs from v33 and master attached.  X86_64 shows similar errors.

### Additional information

See related [FFMPEG bug report](https://github.com/spack/spack/pull/40187) and [proposed fix](https://github.com/spack/spack/commit/bb66d15d08513e50c6d66d6c6d78854ca0348ba1) from the Spack community for proposed bandaid.

[v33 ARM.txt](https://github.com/MythTV/mythtv/files/13182735/v33.ARM.txt)
[master ARM.txt](https://github.com/MythTV/mythtv/files/13182740/master.ARM.txt)

**Comment by jhoyt4** [comment]
I'm looking for a suggestion on where to add the "-ld_classic" linker flag so that it only gets fed to FFMPEG to see if that is the only component broken with the new linker.

**Comment by linuxdude42** [comment]
Try adding "add_ldflags -ld_classic" somewhere in  mythtv/external/FFmpeg/configure before the line that reads "cat > ffbuild/config.mak <<EOF".

**Comment by linuxdude42** [comment]
Looks like I need a new mac mini. I can't upgrade past Monterey.

**Comment by jhoyt4** [comment]
Have you considered running [OpenCore](https://dortania.github.io/OpenCore-Legacy-Patcher/START.html) to patch your current system to run more recent version?

**Comment by jhoyt4** [comment]
> Try adding "add_ldflags -ld_classic" somewhere in mythtv/external/FFmpeg/configure before the line that reads "cat > ffbuild/config.mak <<EOF".

Thanks!  I added  "test ${clang_version%%.*} -ge 15 && add_ldflags -ld_classic" to line 5550 (in the darwin clang section).  It's gotten past the FFMPEG issue and successfully compiled.  Trying again with mythplugins.  If all goes well, I'll work up a PR.
