### ISSUE TITLE
Cannot Directly connect to Frontend Web Remote

### ISSUE THREAD

**Issue by davepearson1628** [MythTV/mythtv#811]
* **Platform**: Ubuntu 23:10

* **MythTV version**: 34

* **Package version**:

* **Component**: Web Frontend - Frontend Remote Control

### How often does it reproduce? Is there a required condition?
Every Time

### What is the expected behaviour?
To load up the Remote Control Web Page

### What do you see instead?
404 Not Found

**Comment by bennettpeter** [comment]
It works when clicking a link from the home page but not when invoking the url directly.

**Comment by kmdewaal** [comment]
Remote control via the mythmote Android app does not work anymore for me. Uses probably the same interface.

**Comment by bennettpeter** [comment]
> Remote control via the mythmote Android app does not work anymore for me. Uses probably the same interface.

I see that mythmote works with arrow buttons, but enter does not work so you cannot get very far. I don't know if this is related to the frontend web-app. I suggest you open a separate ticket for it.
