### ISSUE TITLE
Web thingy: running transcode jobs

### ISSUE THREAD

**Issue by white-haired-uncle** [MythTV/mythtv#813]
```
mythbackend# uname -a
Linux mythbackend 6.2.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct  6 10:23:26 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

MythTV Version : v34-Pre-531-g29e5a97b65-dirty
MythTV Branch : master
Network Protocol : 91
Library API : 34.20220913-1
QT Version : 5.15.3
Options compiled in:
 linux profile use_hidesyms using_alsa using_oss using_pulse using_pulseoutput using_backend using_bindings_perl using_bindings_python using_bindings_php using_dvb using_firewire using_frontend using_hdhomerun using_satip using_vbox using_ceton using_joystick_menu using_libcec using_libcrypto using_gnutls using_libdns_sd using_libxml2 using_lirc using_mheg using_opengl using_egl using_qtwebkit using_qtscript using_qtdbus using_taglib using_v4l2 using_v4l2prime using_x11 using_system_libbluray using_system_libudfread using_systemd_notify using_systemd_journal using_drm using_bindings_perl using_bindings_python using_bindings_php using_freetype2 using_mythtranscode using_opengl using_egl using_drm using_vaapi using_nvdec using_vdpau using_ffmpeg_threads using_mheg using_libass using_libxml2 using_libmp3lame

"dirty" because I've tweaked playbackbox.cpp to format disk usage lines
```

I selected a recording, Run Jobs, Transcode.  I expected Transcode to be a pulldown which would list my profiles.  Instead it ran one I didn't want ("Low Quality" IIRC, or maybe "Default", but not "Lossless" which is the only one that works).  And then there was no Stop Transcoding option, so my recording got trashed before I could get to the FE to stop it.  My fault for launching the job knowing it could (probably would) end badly, but even if I wanted to stop when I saw there were no profiles it would be rather easy to accidentally launch the transcode if my finger slipped off the mouse.

P.S.  While I hate to list multiple items in a single issue, since I've already done so -- shouldn't user jobs be listed here?  I don't have any, so maybe that's why they're "missing".

**Comment by bennettpeter** [comment]
User jobs are listed if you have any.

Transcode runs with the default profile. Changing that requires an extra level of menu and code to update the recording's profile before invoking the transcode. In my experience transcoding is not very useful these days. Do you find it useful? What settings do you use for recording profiles?

**Comment by white-haired-uncle** [comment]
Yeah, most transcoding has been broken for years.  It was very useful 
for long term storage, as a lot of stuff I want to keep doesn't need HD, 
so 1080i MPEG2 -> 480p h264 saves tons of space.  These days I'm using 
av1, so I probably wouldn't use mythtranscode for codec conversion.  And 
I'll bet most other people wouldn't like the 720x480 limitation.  It's 
unfortunate, I thought it was one of myth's best features when it 
worked.

I suspect if mythtranscode is ever resurrected it'll be for streaming.

I do use one profile very regularly, lossless for cutting 
commercials/credits/etc.  The lossless option disappeared from the gui 
some years back, but it still works.

**Comment by bennettpeter** [comment]
I addressed this by changing the menu item for Transcode to "Transcode with Default profile".

**Comment by white-haired-uncle** [comment]
BTW, what is the "Default profile"?  I see it's an option when transcoding, but when I look at setup there's no profile named Default, no "this profile is the default" flag, and the only thing I can find in the db is is_default on the profilegroup (which makes no sense to me, and is set to 1 for all profilegroups).

I'd like to set the Default to my Lossless profile, or set the lossless flag on the Default profile.

TIA

**Comment by bennettpeter** [comment]
It does whatever the frontend does if you select a recording, press M , Job Options -> Begin Transcoding -> Default. I am not very familiar with transcoding, so I do not know how that is set up.
