### ISSUE TITLE
Frontend web app: Collapse listing of videos

### ISSUE THREAD

**Issue by white-haired-uncle** [MythTV/mythtv#814]
```

mythbackend# uname -a
Linux mythbackend 6.2.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct  6 10:23:26 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

MythTV Version : v34-Pre-531-g29e5a97b65-dirty
MythTV Branch : master
Network Protocol : 91
Library API : 34.20220913-1
QT Version : 5.15.3
Options compiled in:
 linux profile use_hidesyms using_alsa using_oss using_pulse using_pulseoutput using_backend using_bindings_perl using_bindings_python using_bindings_php using_dvb using_firewire using_frontend using_hdhomerun using_satip using_vbox using_ceton using_joystick_menu using_libcec using_libcrypto using_gnutls using_libdns_sd using_libxml2 using_lirc using_mheg using_opengl using_egl using_qtwebkit using_qtscript using_qtdbus using_taglib using_v4l2 using_v4l2prime using_x11 using_system_libbluray using_system_libudfread using_systemd_notify using_systemd_journal using_drm using_bindings_perl using_bindings_python using_bindings_php using_freetype2 using_mythtranscode using_opengl using_egl using_drm using_vaapi using_nvdec using_vdpau using_ffmpeg_threads using_mheg using_libass using_libxml2 using_libmp3lame

"dirty" because I've tweaked playbackbox.cpp to format disk usage lines
```

I put this in as a bug, because I think it probably is.  I could certainly be wrong, in which case it's a feature request and my bad.

My videos (as opposed to recordings) are stored like this:

```
.../video/fahrenheit_451.av1                               # A movie
.../video/hell_on_wheels/hell_on_wheels_s01_e01.h264       # A TV series with many episodes
.../video/hell_on_wheels/hell_on_wheels_s01_e02.h265

```
In FE, this works reasonably well, with hell_on_wheels as a folder icon which I can open to list individual episodes.  With the new web app, when I go to Videos I get a list of every file (no hierarchy).  With 1,471 rows this is a bit unruly.  There's a checkbox Flatten Directory Lists which I suspect is supposed to collapse the list just the way I like it (if unchecked?), but it doesn't seem to do anything.

P.S.  However the videos are listed, files with the same Title should be sorted (at least by default, or have an option) by SxE like in FE, IMO.

TIA

**Comment by bennettpeter** [comment]
I do not understand what you are seeing. If you leave unchecked "Flatten directory lists" you get only the files in the current directory, and directory names displayed with a folder icon, like as in the linux file manager. Folders are listed first. Then you click on a folder name to see its contents.  Does yours not look like this?
![Screenshot_2023-11-07_21-08-13](https://github.com/MythTV/mythtv/assets/8069726/a854f34c-9795-4663-b320-bc0f4c60cef8)

**Comment by white-haired-uncle** [comment]
I don't get the folder icons.  firefox 115.4, whatever the default theme for the web app is.
![Screenshot from 2023-11-07 21-35-32](https://github.com/MythTV/mythtv/assets/135195815/dbbc9e76-ec69-4168-8c5a-006cfd14ca8b)

**Comment by white-haired-uncle** [comment]
P.S.  Notice in my URL bar there's a thing that looks like a shield(?) with a cross through it.  I had to click on that and choose turn off Enhanced Tracking Protection for this site or else the web app's main frame didn't show anything.  I suspect others will  run into this.

**Comment by white-haired-uncle** [comment]
Tried five instances.  No difference listing videos when using hostname/IP on any:

1/2) hawkeye, my desktop and the VM host.  Rocky8.7.  One firefox instance with pretty much everything locked down (noscript, adblock, privacy badger, pretty much nothing enabled, etc) but with cookies/js/etc allowed for mythbackend, and one instance running as another user which is just the default wide open.  FF 1.115.4.0esr.  Both need enhanced tracking disabled.  Uses hosts file entry (BE is a VM, needs to be forced to use specific NIC as the other shares a MAC between host/guest -- required for HDHR).

3) spartan, my laptop.  Mint 21.  114.0.1.  Needs enhanced tracking disabled.  Uses DNS.  Same extensions, etc.

4) mythbackend, a VM guest.  22.04.1-Ubuntu.  FF 119.0.1 installed from ppa:mozillateam/ppa (not snap).  No local configuration, extensions, etc.   Does not require enhanced tracking disabled.

5) wolverine, the dedicated FE.  Devuan5.  FF  115.4.0esr, no modifications.  Does not need enhanced tracking disabled.  Uses DNS.

I wonder if the issue is related to directory structure?  That's given me some grief with FE.  I'm guessing yours might be two levels deep ("TV Shows/Big Sky/episodeSxE.mpg")?  I'll try some things, starting with directory name != videometadata.title.

Note to self:  Need to test in mythbrowser.  Needs to work if I want to be able to use setup from FE (runs FE natively, no WM) unless I want to start another xsession on another pty.

Note to self:  Check settings for differences related tracking - so far only the brand new installed today instances don't need it.

**Comment by white-haired-uncle** [comment]
`mythhttpparser.cpp:20 (GetRequest) GET /Video/GetVideoList?Sort=Title&Folder=&CollapseSubDirs=true&StartIndex=0&Count=100 HTTP/1.1`

Confirmed CollapseSubDirs= changes depending on button setting.

**Comment by bennettpeter** [comment]
Please try this.
Start firefox and open `http://backend:6544`
You see Backend Status
Control-Shift-I
This opens the Inspector . Click the tab marked Network in the inspector.
Click the Videos tab in the MythTV Backend page
You should see 1 line in the inspector pane. On the right hand side click Headers to see the url. Alternatively, select the line , right click, copy value, copy URL.  It should show this url:
` http://backend:6544/Video/GetVideoList?Sort=Title&Folder=&CollapseSubDirs=true&StartIndex=0&Count=100`
The part that says `CollapseSubDirs=true` is what tells the backend you do not want to see the contents of subdirectories. If you check flatten directory lists you should see `CollapseSubDirs=false` in the url
Also please try running the url 
`http://backend:6544/Video/GetVideoList?Sort=Title&Folder=&CollapseSubDirs=true&StartIndex=0&Count=100`
in a browser. You should see xml with lots of fields and your directory names listed with DIRECTORY as the ContentType:
```
<VideoMetadataInfos>
<VideoMetadataInfo version="2.01">
<Title>DIR NAME</Title>
...
<ContentType>DIRECTORY</ContentType>
```
The results of these tests will give an indication of where things are going wrong.

**Comment by white-haired-uncle** [comment]
The Inspector pane worked as you described.

The resulting xml produces no lines containing DIRECTORY
[result.xml.gz](https://github.com/MythTV/mythtv/files/13302069/result.xml.gz)

**Comment by white-haired-uncle** [comment]
select * from videometadata
ls -lR video dir
mysqldump of videometadata

[videometadata.txt.gz](https://github.com/MythTV/mythtv/files/13302131/videometadata.txt.gz)
[ls-lR.txt.gz](https://github.com/MythTV/mythtv/files/13302132/ls-lR.txt.gz)
[videometadata.sql.gz](https://github.com/MythTV/mythtv/files/13302148/videometadata.sql.gz)

**Comment by bennettpeter** [comment]
I see what the problem is from your [result.xml.gz]. Your file names start with a slash, whereas mine never start with a slash as they are relative to the storage group directory. There is a logic error that treats a leading slash as no slash. I will fix it.
A sample from running the servuce url on my system looks like this
`<FileName>TV Shows/Drama/12 Monkeys/S01E01 Splinter.mkv</FileName>`
whereas yours look like this
`<FileName>/net/hawkeye/export/share/video/College Football/Holiday/1583_20191228010000.m4v</FileName>`
How do you create files in your videos with a leading slash in the name?

**Comment by bennettpeter** [comment]
I found out how to add files with a leading slash. I have fixed the bug, and also fixed the sort order where the episodes of a series were in random order, they will now be in season and episode order.

**Comment by white-haired-uncle** [comment]
>  How do you create files in your videos with a leading slash in the name?

I don't.

Until today, when I added one as a troubleshooting step, I didn't have a Videos storage group (was playing around in mythweb and saw it required it, so I tried it).  settings.VideoStartupDir(?)=/net/hawkeye/export/share/video for the FE (!=BE), which is where I run all my scan/metadata lookups.  I guess with no SG it must store the absolute path, not relative.

Pretty sure storage groups didn't exist many years ago, and then when they came around videos did not play back very well (as I understand it, if the FE could see the data it would stream it directly (NFS), otherwise the BE would read it and send it via some myth protocol).  Or something like that.   I remember seeing somewhere paths with the backend name in them (choppy playback), or just an NFS path (worked fine).

Thanks

P.S.  Very impressed by the new web app.  It's a lot more than I expected.

**Comment by white-haired-uncle** [comment]
Better, but a little odd.  I might be doing things a little outside the (current) ordinary by not having a Videos SG, but I think anyone who has videos going back to the days before storage groups, or perhaps just still has the direct path set in FE>Settings>General could potentially see some strangeness.

If I just click on Videos, I get basically the same giant list as before.  The only difference is now with Flatten unchecked I have a /net folder.  If I drill down into that folder to the level where my videos/directories are stored, I get a view which I assume is the intended "root menu".  I'm okay with this, but I think it might lead to some confusion for others when they first see it.

I suppose with no Videos SG to define "root", it's kind of necessary to drill all the way down from /.  I'm just not sure the other 1470 entries should be visible when you first click 'Videos'.  [I tried creating a Videos SG pointing to /net/hawkeye/export/share/video which did not help, though I didn't change the db entries to be relative to that].

![Screenshot from 2023-11-08 23-11-20](https://github.com/MythTV/mythtv/assets/135195815/62581b40-7141-41b0-91cf-151d6cf945c7)
![Screenshot from 2023-11-08 23-10-00](https://github.com/MythTV/mythtv/assets/135195815/4e7f1d3e-fd44-48d1-8afc-746b5c843011)

**Comment by bennettpeter** [comment]
How does mythfrontend show them? The list should be the same as what you see in mythfrontend.

Is it possible that you have the directory listed in two places? Perhaps in the frontend as well as in backend storage groups?

If that is not the case, please send me the output from the URL 
`http://backend:6544/Video/GetVideoList?Sort=Title&Folder=&CollapseSubDirs=true&StartIndex=0&Count=100`

The recommended approach is to remove all paths from "Directories that hold videos" in mythfrontend -> Setup -> Media Settings -> Videos Settings -> General Settings. Then add the directory or directories to backend setup -> storage groups -> Videos. You can do that with the web app setup. Then scan videos for changes.

**Comment by white-haired-uncle** [comment]
When start Watch Videos in FE, there are folders and files which match the contents of /net/hawkeye/export/share/video.  I don't actually see /net and its children (unless I also add a Videos SG, in which case I see it in addition).  Pretty much ideal (except I can't change the folder names to Title and not strictly the directory name "Hell on Wheels" instead of hell_on_wheels).

There is no SG which contains /net/hawkeye/export/share/video, only the path in settings.

```
MariaDB [mythconverg]> select groupname,dirname,hostname from storagegroup;
+-------------+---------------------------------+-------------+
| groupname   | dirname                         | hostname    |
+-------------+---------------------------------+-------------+
| Banners     | /mythdata/mythbanners/          | mythbackend |
| Coverart    | /mythdata/mythcoverart/         | mythbackend |
| DB Backups  | /mythdata/mythdbbackup/         | mythbackend |
| Default     | /mythdata/recorded1/            | mythbackend |
| Default     | /mythdata/recorded2/            | mythbackend |
| Default     | /net/hawkeye/export/video       | wolverine   |
| Default     | /net/hawkeye/export/video2      | wolverine   |
| Fanart      | /mythdata/mythfanart/           | mythbackend |
| Music       | /mythdata/mythmusic             | mythbackend |
| MusicArt    | /mythdata/mythmusicart          | mythbackend |
| MusicArt    | /net/hawkeye/export/share/music | wolverine   |
| Screenshots | /mythdata/mythscreenshots/      | mythbackend |
| Trailers    | /mythdata/mythtrailers          | mythbackend |
+-------------+---------------------------------+-------------+
13 rows in set (0.001 sec)

```

IIRC, not long ago, probably around v31, use of SGs became required for some/most things.  At the same time, I added another mount for my recordings, so I had to move at least some stuff over to them.  I tried moving Videos, but that didn't work and I had to continue using the path in settings.  IIRC, the problem was that I use autofs and the video file manager wouldn't dig down to the videos unless some other application ensured the fs was mounted first (and I didn't like having to drill down from /net).

[result2.xml.gz](https://github.com/MythTV/mythtv/files/13309644/result2.xml.gz)

**Comment by bennettpeter** [comment]
I have committed the fix. You should no longer see all of the files on the root page.

You will still have to drill down from /net.

 Thank you for following through and testing the change. Let me know if there are any other problems.

**Comment by paul-h** [comment]
I would recommend not using both the legacy directory settings and storage groups at the same time. It will only cause you more problems in the future.

We have wanted to remove the legacy settings for some time but there was resistance to it. I think it was because some wanted to still use external players which don't understand MythTV storage groups.

**Comment by white-haired-uncle** [comment]
This works as you have described.  Thanks.

**Comment by white-haired-uncle** [comment]
After applying the last two fixes (which, now that I think of it, probably included other changes, not many, but a few), I can no longer play some of my old recordings.

```
2023-11-09 22:46:35.175747 I  TV::HandleStateChange(): Attempting to change from None to WatchingPreRecorded
2023-11-09 22:46:35.184747 E  MythSocket(55c7a705f310:-1): Failed to connect to (172.30.219.103:6543) Connection refused
2023-11-09 22:46:35.184776 E  RemoteFile::openSocket(control socket): Could not connect to server hawkeye:6543
2023-11-09 22:46:35.184876 E  FileRingBuf(myth://hawkeye/2135_20221205103000.ts): RingBuffer::RingBuffer(): Failed to open remote file (myth://hawkeye/2135_20221205103000.ts)
```
hawkeye (172.30.219.103) is the old BE, before I moved it to a VM called mythbackend.  It's interesting that it starts failing now, and not when I moved the BE.  It worked last night.  Simply updating recorded.hostname to mythbackend, something I probably should have done before, allows the recordings to play.  So this is just an interesting potential side effect I thought was worth mentioning.

**Comment by bennettpeter** [comment]
I don't believe that is related to this issue.
