### ISSUE TITLE
Automatic handling of forced subtitles makes non-forced subtitles work less conveniently

### ISSUE THREAD

**Issue by Glidos** [MythTV/mythtv#820]
* **Platform**: Linux glidos 5.14.21-150500.55.36-default #1 SMP PREEMPT_DYNAMIC Tue Oct 31 08:37:43 UTC 2023 (e7a2e23) x86_64 x86_64 x86_64 GNU/Linux

* **MythTV version**: fixes-33 (all I believe)

* **Package version**: N/A

* **Component**: frontend

### What steps will reproduce the bug?
Use mythfrontend to play a .mkv video that includes a forced track amongst its subtitle tracks.

### How often does it reproduce? Is there a required condition?
Always. No condition

### What is the expected behaviour?
The forced subtitle track will display without user interaction. If the user wants also to see non-forced subtitles then they just need to toggle subtitles on with the T key.

### What do you see instead?
The forced subtitle track is displayed without user interaction, but toggling subtitles doesn't select a suitable non-forced track. The T key doesn't perform a useful function unless the user first explicitly selects a non-forced track. If the user does select a non-forced track then, although the user can toggle it on and off, automatic display of the forced track becomes inhibited.

### Additional information
I've fixed this and will post a pull request.

**Comment by bennettpeter** [comment]
It looks like you and I both added a parameter to AddAVSubtitle. I was fixing an issue with external subtitles.

**Comment by Glidos** [comment]
No problem. I can rebase and fix the conflicts

**Comment by Glidos** [comment]
Now rebased cleanly over your changes, although not tested.

**Comment by bennettpeter** [comment]
Closing this issue as we do not need an issue as well as a pull request for the same change. Continue the conversation in #821
