### ISSUE TITLE
Improve web-app Program Guide

### ISSUE THREAD

**Issue by bennettpeter** [MythTV/mythtv#822]
Some improvements to the program guide have been requested:

- Display 3 hours instead of 2 hours in the grid
- Use different background colors for different genres of program.

If anybody has other requests please add them as comments to this feature request

**Comment by kmdewaal** [comment]
In the program guide it is possible to scroll up and down, but it is NOT possible to scroll left to right. This has to be done by clicking on arrows to go the full screen width later or earlier.
It would be great if you can scroll from left to right (and back) in the same way that you can scroll up and down.

**Comment by bennettpeter** [comment]
@kmdewaal There is no easy way I could find to add horizontal scrolling. A huge amount of data would be involved if you could scroll horizontally for 14 days, so it would need a lazy load. Lazy loadfis available for vertical scroll, but I don't know about using it for  horizontal scrolll.

**Comment by bennettpeter** [comment]
closed in commit 3364fdac42b26b23963fed1f0fea0ecdf6872790

**Comment by kmdewaal** [comment]
While we are at it... it would be nice if the program guide can filter on Channel Group, similar to how the Channel Editor can filter on video source. Since channel groups are automaticaly created for each video source this makes it then possible to view only the channels for one video source. Of course, this then also makes it possible to select a manually created channel group. This is functionality that is present in mythfrontend.

**Comment by kmdewaal** [comment]
Looking at the latest version of the program guide, the background for the subtitle is colored with a dark color when it is a Series, TV Show, Movie or Sports. This gives good contrast for the subtitle text.
However, for other types of shows the background is very light grey and the subtitle text is white. This is not readable.
I suggest to make the default background also a dark color, or to change the text color to black when it is written on top of a light background.

**Comment by bennettpeter** [comment]
Default color is now fixed in 77a1ff3665
