### ISSUE TITLE
Web Server Enhancements

### ISSUE THREAD

**Issue by rottnest** [MythTV/mythtv#833]
**Is your feature request related to a problem? Please describe.**
Please describe the problem you are trying to solve.

**Describe the solution you'd like**
Please describe the desired behaviour.

1) When [Restart Backend] 'fails' it would help to say "Error in Channels" or even "No ip set for server in bla bla" I spent ages looking for 'something wrong'. I guess most people would rarely use setup. 
This could go "It may waste an hour, but you so seldom ..." or This is unusual activity, so all the help you can get.

2) Save-n-Quit rather than Save, Quit for Program Guide is a tad more user friendly
Quit
Do you really want to quit
Yes
Are you Sure
Yes
Quitting is not allowed
Aaarghhhh!

3) When entering "Record" one would usually "Record 1 showing" not usually cancel a recording. Mythfront/backend may follow mythtv but this is a minor irritation

4) mythweb manages to get a large number of categories (coloured) would be nice if mythbackend-browser could do likewise.

5) I've made comments about Qt:settings. It would be nice to accomadate users who don't want feature-xx (If you are not familiar with settings a (well-defined-path)/name.conf that says eg
[default]
colouredRows=true
guideOption=Record1
etc=blabla
)

7) Abort/Quit/Cease/Stop/Go No Further
After (1) I tried everything including reboot but mythbackend was locked in 'setup mode' and only fixing the problem solved. This is a test machine so I was about to drop the db.
If it was a real machine then I'd have looked at the DB more carefully.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

I've setup and downloaded a dev environment, but so far done no fiddling at all so all the above is based on That'd be Nice without regard to how hard it'd be to achieve.

**Comment by rottnest** [comment]
I'm a ingineer so my spelling of [accommodate] is lousy. Sorry!

**Comment by bennettpeter** [comment]
Re: Items 1 and 6, which seem to be the same problem. With the old mythtv-setup in v33. If you had a problem (e.g. no ip address set, the backend would fail to start. Now it starts in web server setup mode instead. I will change it so that a message on screen tells you why it is in setup mode.

**Comment by bennettpeter** [comment]
Re item 4, there are over 100 categories. I do not know how to categorize these into colors. Note: the category name is now displayed in the grid between title and subtitle. 

List of categories from Schedules Direct is here -> https://pastebin.com/Kzfjv3P6

If somebody can supply a list of background colors by category I will implement it. We may have to also consider text color, currently white, to make sure it contrasts with the backeground color.

Note that mythweb only supports some 30 of these categories, all others get a default color.

Probably we could group some categories together in one color, for example News and Newsmagazine may be the same color.

**Comment by rottnest** [comment]
> On Jan 2, 2024, at 09:57, Peter Bennett ***@***.***> wrote:
> 
> 
> Re item 4, there are over 100 categories. I do not know how to categorize these into colors. Note: the category name is now displayed in the grid between title and subtitle.
> List of categories from Schedules Direct is here -> https://pastebin.com/Kzfjv3P6
> If somebody can supply a list of background colors by category I will implement it. We may have to also consider text color, currently white, to make sure it contrasts with the backeground color.
> Note that mythweb only supports some 30 of these categories, all others get a default color.
> Probably we could group some categories together in one color, for example News and Newsmagazine may be the same color.

Peter you are in a bottomless pit. :-)

I think that you should use copper ones. But we always used wooden ones. …

If there was a (say) css file defining categories-colours then you as the developer may choose 1/2 dozen colours but any user who wanted to may edit the ones they want.
Specially since about 1 in 7 males are red-green colour-blind and a whole lot of colours are ‘brown’. I thought I’d get my red-green mate to choose a set of colours for my app. WOW, no, not good!!

I still have not gone exploring the src, so my opinions may be silly!

Also do you dictate what-will-be? trying to accommodate everyones ‘wouldn’t it be nice’ is fraught and that would be a good argument for ‘don’t rock the boat’.
I opine that the DB might contain a category-colour table/sub-table and totally independantly of mythtv updating that table would be a project in its own light.
Cheers
James

**Comment by paul-h** [comment]
I would think the Angular way would be to have a custom css file used by guide component. It can be hard coded into the component or added as an external css file. Ideally each theme would have it's own css file but that is a lot of work so it's probably easier just to have one css file that works for all/most themes. The css can if you desire change the background only or both the background and the text colour so they complement each other.

To give you a better idea what I'm talking about the old web frontend used a similar approach it had an included css file also which just changes the background-color for some selected categories like MythWeb :- 
https://github.com/MythTV/mythtv/blob/master/mythtv/html/tv/css/category_colors.css

The css selector is basically formed from the name of the category which would have to be added to each cell in the guide grid so it picked up the correct colours from the css file.

One question I have is the category translated or is it always in English?

**Comment by rottnest** [comment]
I like the time setting change on program guide.
but
without a date field … how would you choose NOT today
Without a tooltip the icon is not painfully obvious as *time*
James

**Comment by bennettpeter** [comment]
@rottnest 
Click the icon and get a calendar. Then click a date. Do you not see it?
![Screenshot_2024-01-03_09-02-54](https://github.com/MythTV/mythtv/assets/8069726/bb2d1b88-763e-4c69-82f3-179f50f2b1fb)

**Comment by rottnest** [comment]
> On Jan 3, 2024, at 22:07, Peter Bennett ***@***.***> wrote:
> 
> 
> @rottnest
> Click the icon and get a calendar. Then click a date. Do you not see it?
> Screenshot_2024-01-03_09-02-54.png (view on web)

I did not, but I’m a terrible tester being utterly dim :-)
but I stand by the comment that the box is not obviously the time field. Maybe a clock icon …
James

**Comment by rottnest** [comment]
Peter thankyou for colouring the categories.

A question: are the colours stored in an accessable place so that a user who wants/needs to change may get to them.
I asked for colours, and would not even contemplate plain white, but if there was a user who wanted white is that something she
could do.
 (oh boy! I was being cute and repectful saying ‘she', but it can also read as a mysoginic view that only females would consider something so daft. Sorry Ladies! no disrespect at all) 
James

**Comment by bennettpeter** [comment]
On the Program Guide page, there is a button called "Colors". Click that and see all the colors that are used. At the bottom of that page is an explanation of where to find the guidecolors.css to change the colors. In the guidecolors.css file are further instructions.

**Comment by rottnest** [comment]
Peter I modified the categories.css as documented to put the movies line last.
Some of my movie listings do not carry the appropriate decor so I went splunking:

[pagesrc]
<!DOCTYPE html><html lang="en"><head>
<meta charset="utf-8">
<title>MythTV Backend</title>
<base href="/">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="/3rdParty/primeicons-5.0.0/primeicons.css">
<link id="app-theme" rel="stylesheet" type="text/css" href="assets/themes/md-light-indigo.css">
<link rel="stylesheet" type="text/css" href="/assets/guidecolors.css">
<link rel="icon" type="image/x-icon" href="favicon.ico">
<style>html,body{height:100%}body{margin:0;height:100%;overflow-x:hidden;overflow-y:auto;background-color:var(--surface-a);font-family:var(--font-family);font-weight:400;color:var(--text-color);-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}</style><link rel="stylesheet" href="styles.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles.css"></noscript></head>
<body>
<app-root></app-root>
<script src="runtime.js" type="module"></script><script src="polyfills.js" type="module"></script><script src="main.js" type="module"></script>

</body></html>

opps not there
The category is listed as Movie, but where the sub-category is listed as Movie Name, or other then the decor is wrong

How can I troubleshoot
Thanks
James

**Comment by bennettpeter** [comment]
> Peter I modified the categories.css as documented to put the movies line last. Some of my movie listings do not carry the appropriate decor so I went splunking:

It is guidecolors.css  not categories.css

After updating the guidecolors.css you have to refresh the page.

It works for me.  I looked at my guide this morning, and channel 58 is showing Shane,  western, colored brown. I moved the .guide_type_movie line in guidecolors.css to the bottom of the file, saved guidecolors.css, refreshed the program guide page, scrolled down to channel 58 and now it is pink, the movie color.

 If  you cannot get it to work send me your updated guidecolors.css.

**Comment by rottnest** [comment]
> On Jan 19, 2024, at 22:04, Peter Bennett ***@***.***> wrote:
> 
> 
> Peter I modified the categories.css as documented to put the movies line last. Some of my movie listings do not carry the appropriate decor so I went splunking:
> It is guidecolors.css not categories.css
> After updating the guidecolors.css you have to refresh the page.
> It works for me. I looked at my guide this morning, and channel 58 is showing Shane, western, colored brown. I moved the .guide_type_movie line in guidecolors.css to the bottom of the file, saved guidecolors.css, refreshed the program guide page, scrolled down to channel 58 and now it is pink, the movie color.
> If you cannot get it to work send me your updated guidecolors.css.


Thanks. Playing with ‘colours’ :-)

This is what I choose
https://tigger.ws/downloads/eg.jpg

this is what I get
https://tigger.ws/downloads/bad.jpg


/*  Customize the guide colors here.

    Note that changes you make here may be overwritten if you subsequently install a new
    build  of MythTV. Therefore keep a copy of your changed file somewhere else and copy
    it back here if you install MythTV again or upgrade it.

    Use ".guide_type_" prefix for "Category Type" in the listings. Normally there are only 4
    types: series, tvshow, movie, sports.

    Use ".guide_cat_" prefix for "Category" in the listings. Following this is the category,
    converted to lower case, all characters other than a-z and 0-9 changed to underscore.
    For example "Science fiction" becomes .guide_cat_science_fiction and "Bus./financial" becomes
    .guide_cat_bus__financial (two underscores).

    If you edit this file with Visual C++, it will provide a color selector to  make selecting
    colors easy.
*/

/*  The default color must be first in the list. Do not remove this default. You can change it
    if needed.  If you remove it the default colors may be unreadable. */
.guide_type_default { background-color: #403060 !important; color: white !important; }

/* The type colors are next in the list. If you do not want colors for these types you
    can remove or comment these lines.
    If a show matches a type and a category, the last match will take effect, in other
    words the category will be used. If you want all movies to have the same color
    irrespective of the category, put the .guide_type_movie entry at the end of this file */
.guide_type_sports  { background-color: #005030 !important; color: white !important; }
.guide_type_series  { background-color: #87ceeb !important; color: black !important; }
.guide_type_tvshow  { background-color: rgb(117, 189, 189) !important; color: black !important; }
/*.guide_type_movie   { background-color: #ffa0a0 !important; color: black !important; }*/

/* The category colors are after the type colors. If there is a matching category its
    color will override the type color. Any time there is a multiple match, the last one
    in this file that matches will take effect.
    You can change these, remove entries or add missing entries.
    If you add a light background color, you may want to change the text color from white
    to black */
.guide_cat_action         { background-color: #906020 !important; color: white !important; }
.guide_cat_adult          { background-color: #702020 !important; color: white !important; }
.guide_cat_animals        { background-color: #609060 !important; color: white !important; }
.guide_cat_art            { background-color: #801060 !important; color: white !important; }
.guide_cat_bus__financial { background-color: #703010 !important; color: white !important; }
.guide_cat_children       { background-color: #B08080 !important; color: white !important; }
.guide_cat_animated       { background-color: #B00010 !important; color: white !important; }
.guide_cat_comedy         { background-color: #006080 !important; color: white !important; }
.guide_cat_sitcom         { background-color: #006080 !important; color: white !important; }
.guide_cat_comedy_drama   { background-color: #dda0dd !important; color: white !important; }
.guide_cat_cooking        { background-color: #208040 !important; color: white !important; }
.guide_cat_crime          { background-color: #105050 !important; color: white !important; }
.guide_cat_crime_drama    { background-color: #105050 !important; color: white !important; }
.guide_cat_documentary    { background-color: #daa520 !important; color: white !important; }
.guide_cat_docudrama      { background-color: #504020 !important; color: white !important; }
.guide_cat_drama          { background-color: #d8bfd8 !important; color: white !important; }
.guide_cat_educational    { background-color: #606060 !important; color: white !important; }
.guide_cat_fantasy        { background-color: #606090 !important; color: white !important; }
.guide_cat_game_show      { background-color: #701010 !important; color: white !important; }
.guide_cat_health         { background-color: #806060 !important; color: white !important; }
.guide_cat_history        { background-color: #807020 !important; color: white !important; }
.guide_cat_historical_drama { background-color: #807020 !important; color: white !important; }
.guide_cat_house_garden   { background-color: #A0A000 !important; color: white !important; }
.guide_cat_how_to         { background-color: #A0A000 !important; color: white !important; }
.guide_cat_horror         { background-color: #101040 !important; color: white !important; }
.guide_cat_health         { background-color: #806060 !important; color: white !important; }
.guide_cat_music          { background-color: #d8bfd8 !important; color: white !important; }
.guide_cat_mystery        { background-color: #105050 !important; color: white !important; }
.guide_cat_news           { background-color: #a2cd5a !important; color: black !important; }
.guide_cat_newsmagazine   { background-color: #9acd32 !important; color: white !important; }
.guide_cat_reality        { background-color: #304040 !important; color: white !important; }
.guide_cat_religious      { background-color: #804080 !important; color: white !important; }
.guide_cat_romance        { background-color: #A02050 !important; color: white !important; }
.guide_cat_science        { background-color: #008050 !important; color: white !important; }
.guide_cat_nature         { background-color: #008050 !important; color: white !important; }
.guide_cat_science_fiction { background-color: #606090 !important; color: white !important; }
.guide_cat_shopping       { background-color: #103010 !important; color: white !important; }
.guide_cat_soap           { background-color: #508080 !important; color: white !important; }
.guide_cat_sports_talk    { background-color: #005030 !important; color: white !important; }
.guide_cat_sports_non_event { background-color: #005030 !important; color: white !important; }
.guide_cat_talk           { background-color: #203040 !important; color: white !important; }
.guide_cat_tba            { background-color: #303030 !important; color: white !important; }
.guide_cat_travel         { background-color: #2060B0 !important; color: white !important; }
.guide_cat_war            { background-color: #B06050 !important; color: white !important; }
.guide_cat_western        { background-color: #806040 !important; color: white !important; }

.guide_type_movie   { background-color: #ffa0a0 !important; color: black !important; }

**Comment by rottnest** [comment]
> On Jan 19, 2024, at 22:04, Peter Bennett notifications at github.com ***@***.***> [bluddy spam filters]  wrote:
> 
> 
> Peter I modified the categories.css as documented to put the movies line last. Some of my movie listings do not carry the appropriate decor so I went splunking:
> It is guidecolors.css not categories.css
> After updating the guidecolors.css you have to refresh the page.
> It works for me. I looked at my guide this morning, and channel 58 is showing Shane, western, colored brown. I moved the .guide_type_movie line in guidecolors.css to the bottom of the file, saved guidecolors.css, refreshed the program guide page, scrolled down to channel 58 and now it is pink, the movie color.
> If you cannot get it to work send me your updated guidecolors.css.


Thanks. Playing with ‘colours’ :-)

This is what I choose
https [colon] [slash] [slash] tigger.ws/downloads/eg.jpg

this is what I get 
https [colon] [slash] [slash] tigger.ws/downloads/bad.jpg


/*  Customize the guide colors here.

   Note that changes you make here may be overwritten if you subsequently install a new
   build  of MythTV. Therefore keep a copy of your changed file somewhere else and copy
   it back here if you install MythTV again or upgrade it.

   Use ".guide_type_" prefix for "Category Type" in the listings. Normally there are only 4
   types: series, tvshow, movie, sports.

   Use ".guide_cat_" prefix for "Category" in the listings. Following this is the category,
   converted to lower case, all characters other than a-z and 0-9 changed to underscore.
   For example "Science fiction" becomes .guide_cat_science_fiction and "Bus./financial" becomes
   .guide_cat_bus__financial (two underscores).

   If you edit this file with Visual C++, it will provide a color selector to  make selecting
   colors easy.
*/

/*  The default color must be first in the list. Do not remove this default. You can change it
   if needed.  If you remove it the default colors may be unreadable. */
.guide_type_default { background-color: #403060 !important; color: white !important; }

/* The type colors are next in the list. If you do not want colors for these types you
   can remove or comment these lines.
   If a show matches a type and a category, the last match will take effect, in other
   words the category will be used. If you want all movies to have the same color
   irrespective of the category, put the .guide_type_movie entry at the end of this file */
.guide_type_sports  { background-color: #005030 !important; color: white !important; }
.guide_type_series  { background-color: #87ceeb !important; color: black !important; }
.guide_type_tvshow  { background-color: rgb(117, 189, 189) !important; color: black !important; }
/*.guide_type_movie   { background-color: #ffa0a0 !important; color: black !important; }*/

/* The category colors are after the type colors. If there is a matching category its
   color will override the type color. Any time there is a multiple match, the last one
   in this file that matches will take effect.
   You can change these, remove entries or add missing entries.
   If you add a light background color, you may want to change the text color from white
   to black */
.guide_cat_action         { background-color: #906020 !important; color: white !important; }
.guide_cat_adult          { background-color: #702020 !important; color: white !important; }
.guide_cat_animals        { background-color: #609060 !important; color: white !important; }
.guide_cat_art            { background-color: #801060 !important; color: white !important; }
.guide_cat_bus__financial { background-color: #703010 !important; color: white !important; }
.guide_cat_children       { background-color: #B08080 !important; color: white !important; }
.guide_cat_animated       { background-color: #B00010 !important; color: white !important; }
.guide_cat_comedy         { background-color: #006080 !important; color: white !important; }
.guide_cat_sitcom         { background-color: #006080 !important; color: white !important; }
.guide_cat_comedy_drama   { background-color: #dda0dd !important; color: white !important; }
.guide_cat_cooking        { background-color: #208040 !important; color: white !important; }
.guide_cat_crime          { background-color: #105050 !important; color: white !important; }
.guide_cat_crime_drama    { background-color: #105050 !important; color: white !important; }
.guide_cat_documentary    { background-color: #daa520 !important; color: white !important; }
.guide_cat_docudrama      { background-color: #504020 !important; color: white !important; }
.guide_cat_drama          { background-color: #d8bfd8 !important; color: white !important; }
.guide_cat_educational    { background-color: #606060 !important; color: white !important; }
.guide_cat_fantasy        { background-color: #606090 !important; color: white !important; }
.guide_cat_game_show      { background-color: #701010 !important; color: white !important; }
.guide_cat_health         { background-color: #806060 !important; color: white !important; }
.guide_cat_history        { background-color: #807020 !important; color: white !important; }
.guide_cat_historical_drama { background-color: #807020 !important; color: white !important; }
.guide_cat_house_garden   { background-color: #A0A000 !important; color: white !important; }
.guide_cat_how_to         { background-color: #A0A000 !important; color: white !important; }
.guide_cat_horror         { background-color: #101040 !important; color: white !important; }
.guide_cat_health         { background-color: #806060 !important; color: white !important; }
.guide_cat_music          { background-color: #d8bfd8 !important; color: white !important; }
.guide_cat_mystery        { background-color: #105050 !important; color: white !important; }
.guide_cat_news           { background-color: #a2cd5a !important; color: black !important; }
.guide_cat_newsmagazine   { background-color: #9acd32 !important; color: white !important; }
.guide_cat_reality        { background-color: #304040 !important; color: white !important; }
.guide_cat_religious      { background-color: #804080 !important; color: white !important; }
.guide_cat_romance        { background-color: #A02050 !important; color: white !important; }
.guide_cat_science        { background-color: #008050 !important; color: white !important; }
.guide_cat_nature         { background-color: #008050 !important; color: white !important; }
.guide_cat_science_fiction { background-color: #606090 !important; color: white !important; }
.guide_cat_shopping       { background-color: #103010 !important; color: white !important; }
.guide_cat_soap           { background-color: #508080 !important; color: white !important; }
.guide_cat_sports_talk    { background-color: #005030 !important; color: white !important; }
.guide_cat_sports_non_event { background-color: #005030 !important; color: white !important; }
.guide_cat_talk           { background-color: #203040 !important; color: white !important; }
.guide_cat_tba            { background-color: #303030 !important; color: white !important; }
.guide_cat_travel         { background-color: #2060B0 !important; color: white !important; }
.guide_cat_war            { background-color: #B06050 !important; color: white !important; }
.guide_cat_western        { background-color: #806040 !important; color: white !important; }

.guide_type_movie   { background-color: #ffa0a0 !important; color: black !important; }

**Comment by rottnest** [comment]
> On Jan 19, 2024, at 22:04, Peter Bennett ***@***.***> wrote:
> 
> 
> Peter I modified the categories.css as documented to put the movies line last. Some of my movie listings do not carry the appropriate decor so I went splunking:
> It is guidecolors.css not categories.css
> After updating the guidecolors.css you have to refresh the page.
> It works for me. I looked at my guide this morning, and channel 58 is showing Shane, western, colored brown. I moved the .guide_type_movie line in guidecolors.css to the bottom of the file, saved guidecolors.css, refreshed the program guide page, scrolled down to channel 58 and now it is pink, the movie color.
> If you cannot get it to work send me your updated guidecolors.css.

Sorrry for all the noise! My ISP is flagging the return reply as spam so I never see the reply and conclude SENT failed

**Comment by bennettpeter** [comment]
Send your replies by going to the issues page (see bottom of email, "view it on github") and type your reply there. That will avoid all the extra noise and allow you to send images.

It looks like your listings provider does things differently. "back to the future" is category Movie and type also "movie". "The Children Act" is category Movie and type "tvshow". So by using the type you get different colors.

I don't have a category of Movie, because it seems that schedules direct does not do that, they categorize the movie as whatever genre it is, Mystery, Science Fiction, Children, etc.

Solve this by adding a line to the list of categories
.guide_cat_movie { background-color: #ffa0a0 !important; color: black !important; }

**Comment by garybuhrmaster** [comment]
> I don't have a category of Movie, because it seems that schedules direct does not do that, they categorize the movie as whatever genre it is, Mystery, Science Fiction, Children, etc.

Schedules Direct (actually their upstream EPG source Gracenote) has over the past few years been trying to reorganize their entity types, categories, and genres (as I recall they removed keywords which could provide additional information).  In general the revised results would be considered more complete and accurate, but there are always exceptions.  The various XMLTV grabbers that use Schedules Direct (Gracenote) details may transform those details in slightly different ways (Gracenote EPG details do not have a one-to-one mapping to XMLTV), so one might see slightly different results from even the same upstream source.  It should also be noted that in some cases the various entity types, categories, and genres (and ratings for that matter) may be overridden for a particular showing ("this presentation edited to remove ....") and sometimes the overridden values may be less, or more, complete than the original content source.
