### ISSUE TITLE
Web Application upcoming list

### ISSUE THREAD

**Issue by rottnest** [MythTV/mythtv#840]
**Is your feature request related to a problem? Please describe.**
Please describe the problem you are trying to solve.

**Describe the solution you'd like
The "upcoming" is highlighted odd/even which makes upcoming a featureless sea of items I think that it would look much better certainly be easier to parse by eye if each date was highlighted. To be fancy you could odd/even and highlight each date

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

(say)
09/01/2024 bla bla (Light green)
09/01/2024 bla bla (Dark green)
09/01/2024 bla bla (Light green)
09/01/2024 bla bla (Dark green)
10/01/2024 bla bla (Light blue)
10/01/2024 bla bla (Dark blue)
10/01/2024 bla bla (Light blue)
11/01/2024 bla bla (Light green)

PS just a smile for you
rottnest is an island of Perth, when I signed up to github (years agi
that's the first thought that came to mind
https://www.google.com/search?channel=fs&client=ubuntu&q=rottnest+island&si=AKbGX_r2JRjvcwUFglE3kcZnQWHwIWM7hMlwYfSTP1dvrtYRO-ncxo80BdzW6mvOVzjYWX3VGXoRxTU4GOurXWuuARvXd0PypCArt64s_-f59xIz0_ogkc5DNfzNQ06P-YA_lRNCObaSi0F7ZFwziATMb-A8hM7ae6SX4L3bqMcl1jM7WVHo5E6RmtL3TpenqETanKmdbVFnD1kxzk4-XDxGe3USkGsqYi9naYg2W8_vzMr10eVfxeYdUaJn7A4LoKeXmK8hnamgX6yKp-Hm50DXtxP_BuBoklnGRmbw07HeskgoSstpd3Er9sPZMJyWaHcscvhMvEAtRMjMJqVCIRbbrX3wrZnR_APD4QLlYRu2TC_NHlzJV2qim99cgAnDsrXpSqN1quJWoeIhNAPPP-48m1JH2DGPxOnX2SBQFUz68_0MAPOH8vYyZzRqUYoGhpxJJ7tAebIzgmQOZt4UNdY8or-mMpeP6kNSAEOrXTLSlJTffigLg3wq_jOdoG4H7269iEzPQosQlCOWdPDAbLxdcqjf_U3e5OO9GdLZ2FeKub4sEXQolp7fbhlx-tt6zRkz9N9ZkyuH5B4k_SP94WmJvzrQ7wRWtnDIx4XRGMfD1YKdNCJy4KFYdlbgr9HuikpRzpBbmo-oEqLYkUoPx08qtAVqOBWUf2rx0P1E9ybngjwzTLGcigNxmq-XrQlf9ZHjxxJChiaYfeb36glWaaEprHxUjWp_W58AsW1ZLOX8BrTGwdCLlupfcXmTr62V3M6ICL72cq8kMjAFEpoviV9tfA8gNJhHhB1VNXQxyk6mXBesS-y9lVik-Rwm8JQ5XfNISN5fIQj9aDukL_9-3H3ka5xp7VBhnJ3TauUc2WeqteU2X2wA79LAMQAGzPLMYmyp6swD8hP0y6R2_jXDUSPMLxYWvEoAH06x0-4sqEcT5CxBjSEbeuLfJKKg0bf5La67GEdhBkiVon0yAbwEgX5HLKOLlAJg7AiJOX3DrfwWnsd2kK1Poafb2HMltawKWl74tAgqqEGj5z0QzH5-hgWTc1WxDSObeD3rPsnY-FS4oD4IoAa6gl7AR-qbCZS4dIipWeTrurZbq_l5lfH63WH1R4xa2Tg9WS3Eie1FQC3QH3iRZaU_Y0Tto-PpXA18NBWa4Uz_4c8vOxpPytHxQWNv2hqVZkkdaEII-81iLORwv4xT-fFKeEbmDgEC3B5dv-K92Tca5EnmI-RE0xU3YmmlEDI03KxM9Vg0THuEoT5GHUQfvDe8Ouqww2rBwFdQ93FqT2UUr2wvLlNN72qF-vngoOST_xmgQmwMTCi9k_eXbaJlqIN_-Ony8LTmmf5bGlJX6Fka0GOBolANl8I-23OZDuwZyOQ0rRBVoKzY7SFVm_CI9-uEObmT_zhgmYYWcSpZ3u5rX8NUSRY8rMkq0bCE2SefOLX5BNfA_tT1WDDX24QNsWs8iTQFNbGyXmfDnh0RqDbF_WiKqcpa78hnaMsrxrN4lCngZBN4xJAUhQymxHCx1F--1hDCo_Gb8GnJdMz7bWmuX6Y9eusrmxZgsd_R4Ky1QBnPG4OCjrosz1teDVhuMgs6tSG6rgEfYdLNEFE5L4w_TBOJ-ONIzHdrbCbq4pTZwcoJc0baylQzANJSFCsf7tT-OaBa3NP5umfoaJhDCIKlp8HE46lRuLolIvkP2MGsqpi-5TnH84BcFDOUn3adI66p6ZF7mrHDHrBLUr0pgGtddrQw&ictx=1&ved=2ahUKEwj7s_CqhtCDAxVkRWcHHWkEAvQQ_coHegQITBAB

**Comment by bennettpeter** [comment]
The suggested change is difficult. The alternate line highlight is handled by the Prime NG package. The row colors are handled by the selected theme.

I agree that not having them split by date and not having the day of the week is a problem.

So I have changed it this way:

- Add day of the week to the start date.
- If more than one row has the same start date, only show the start date on the first row.
- remove the alternate line highlighting and add gridlines instead.

See commit d3ce31cbcb

**Comment by bennettpeter** [comment]
Yes - master. Only bug fixes are going into fixes/34.

**Comment by rottnest** [comment]
> On May 8, 2024, at 20:34, Peter Bennett ***@***.***> wrote:
> 
> 
> Yes - master. Only bug fixes are going into fixes/34.
> 

OK that’s nice - thankyou

James
