### ISSUE TITLE
SetuptoolsDeprecationWarning: setup.py install is deprecated.

### ISSUE THREAD

**Issue by kmdewaal** [MythTV/mythtv#848]
* **Platform**: Fedora 39 and Ubuntu 23.10

* **MythTV version**: master

* **Package version**: build from source

* **Component**: "make install"

### What steps will reproduce the bug?

On a "make install" I do get the following error message:
```
make[1]: Entering directory '/home/klaas/mma-eit/mythtv/mythtv/bindings/python'
python3 setup.py install --skip-build --root="/" --prefix="/home/klaas/mma-eit/usr"
running install
/usr/lib/python3.12/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer, pypa/build or
        other standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!

```
As the message says, it looks that something must be fixed in the install process.

### How often does it reproduce? Is there a required condition?
Always.

### What is the expected behaviour?
Install without error messages.

### What do you see instead?
Error message as shown above.

**Comment by rcrdnalor** [comment]
| As the message says, it looks that something must be fixed in the install process.

The implementation is already done, see announcement in
https://lists.archive.carbon60.com/mythtv/dev/643997

What is missing is the enforcement to only use python pip
to install the MythTVs Python Bindings in case of python 3.12

Could you please test the following patch?`
```
diff --git a/mythtv/configure b/mythtv/configure
index 5db0eac1e7..80732cf9a2 100755
--- a/mythtv/configure
+++ b/mythtv/configure
@@ -6564,6 +6564,7 @@ if enabled bindings_python; then
     check_py_lib lxml          || disable_bindings_python "lxml"
     check_py_lib requests      || disable_bindings_python "requests"
     check_python "(3,11,1)" && check_py_lib wheel && check_py_lib_version pip "(23,0,1)" && USE_PYTHON_PIP="yes"
+    test x"$USE_PYTHON_PIP" = x"" && check_python "(3,12,0)" && disable_bindings_python "pip, wheel"
 fi
 
 # Check for perl dependencies
```

BTW, if you are using ansible to get the dependencies,
could you please comment on that PR as well?
https://github.com/MythTV/ansible/pull/36

**Comment by kmdewaal** [comment]
Before installing the patch the configure starts without warnings:

```
klaas@kasus:~/mma-eit/mythtv/mythtv$ ./configure --previous
Options:     --prefix=/home/klaas/mma-eit/usr --compile-type=debug 
sed 's#@@PREFIX@@#/home/klaas/mma-eit/mythtv/mythtv/external/nv-codec-headers/install#' ffnvcodec.pc.in > ffnvcodec.pc
```

After installing the patch the configure starts with a warning:

```
klaas@kasus:~/mma-eit/mythtv/mythtv$ ./configure --previous
Options:     --prefix=/home/klaas/mma-eit/usr --compile-type=debug 
WARNING: disabling Python bindings; missing pip, wheel
sed 's#@@PREFIX@@#/home/klaas/mma-eit/mythtv/mythtv/external/nv-codec-headers/install#' ffnvcodec.pc.in > ffnvcodec.pc
```

Once upon a time I have installed the dependencies with ansible.
I did now update ansible and tested configure as above; no change.
I also updated ansible with patch 36 and tested configure as above; no changes.

Comment on the ansible patch 36 in that PR.

**Comment by rcrdnalor** [comment]
Thank you for testing above patch.
Your observations show the correctness of this patch.
On Ubuntu, you need only install the `python3-pip` package.
On Fedora 39, you need to install the `python3-wheel` package as well.
