### ISSUE TITLE
Web app drop box issue

### ISSUE THREAD

**Issue by jfabernathy** [MythTV/mythtv#850]
* **Platform**:
backend is Kubuntu 22.04
* **MythTV version**:
V34 via ppa:mythbuntu/34
* **Package version**:

* **Component**:
Web App
In the Videos tab, if I select a video with no release date and try to manually update, The drop box on date does not allow scrolling within the box. The first pop up is a current calendar but I need to change the year. If I select the 10 year range so I can get to 2012, it doesn't always show the complete set of those 10 years. If I can some how manage to get to 2012, I can only see the first 3 months and then I can't scroll without the popup disappearing. I can't just type in the correct date

**Comment by bennettpeter** [comment]
It works for me. Here is a set of images showing where I selected 2012-08-14
https://imgur.com/a/MCaP5Fw
I suspect your calendar may have been partly off the page for some reason. Try making the page bigger.
Alternatively you can just type the date into the box as 2012-08-14

**Comment by jfabernathy** [comment]
I'm using Firefox and I had to use the ctrl-mouse wheel to really make the text small.  Then on the Update Metadata I had to do the same.  I kept making it smaller until the last week of the month would show up.  Luckily this is something I will not have to do often.

**Comment by bennettpeter** [comment]
You can also type in the date instead of using the calendar.

There is not much I can do to improve this.
