### ISSUE TITLE
static.py.in (and static.py) are missing

### ISSUE THREAD

**Issue by marillat** [MythTV/mythtv#867]
Debian unstable amd64 (also all arches)
mythtv 0.34

As reported here https://forum.mythtv.org/viewtopic.php?f=36&t=5611

```static.py``` is missing and the code to generate ```static.py``` from ```static.py.in``` is also missing

From ```configure``` I see 

```#``` See bindings/python/MythTV/static.py.in
MYTHTV_PYTHON_OWN_VERSION="(34,0,-1,0)"

**Comment by rcrdnalor** [comment]
The file `static.py`  exists and  the file not needed anymore  - `static.py.in` does not exist when checkout of mythtv uses the `v34.0` tag.
See
```
$ git show v34.0 mythtv/bindings/python/MythTV/static.py
tag v34.0
Tagger: David Hampton <mythtv@love2code.net>
Date:   Fri Feb 9 14:09:45 2024 -0500
```

I guess that the sources to build mythtv v34 are taken from a wrong git tag.

**Comment by marillat** [comment]
The source doesn't come from a git tag but from here 
https://github.com/MythTV/mythtv/archive/refs/tags/v34.0.tar.gz

And yes static.py is in this tarball.
I don't know why this file is gone in my machine
