### ISSUE TITLE
Channel editor option might be missing from frontend webapp

### ISSUE THREAD

**Issue by white-haired-uncle** [MythTV/mythtv#884]
* **Platform**:` Linux mythbackend 6.5.0-18-generic #18~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb  7 11:40:03 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`  HDHR Connect Duo (OTA, USA)

* **MythTV version**: Originally v34-Pre-544-g4908066fc4-dirty, now v34.0-18-g5590d0d5eb

* **Package version**:

* **Component**: web 

### What steps will reproduce the bug?

http://mythbackend:6544/setupwizard/channel-editor
 
There is no option, that I can find, to use channel scan.  Also, I was unable to set Multiplex until I added the channel via mythtv-setup->channel scan.

[Additionally, after adding channel 45_8, no matter how I tried to sort, it showed in with the 3_* channels.  I should open separate issue for this after upgrade]

### Additional information

I know I need to upgrade to v34 proper, and I will do so when possible.  For now, I wanted to get this down before I forgot any of the details.

There are three other options (like Edit Transports) at the bottom of the mythtv-setup channel editor main view that I don't see in webapp either.

**Comment by bennettpeter** [comment]
Channel scan is at http://backend:6544/setupwizard/input-connections . Select your device and click the button labeled "Scan for Channels".

Editing of transports is in the channel editor. Click the pencil icon for a channel. In the dialog box scroll to the bottom and click "Advanced Settings"

**Comment by white-haired-uncle** [comment]
Okay, I see the channel scan.  Not where I was expecting it, but I suppose it makes sense.  Thanks.

After upgrading to fixes/34 [v34.0-18-g5590d0d5eb] I'm still unable to find the Edit Transports  (Advanced Settings has only Multiplex and Service ID), Restore Data, or Import Icons.  FWIW, I don't think I've ever used any of these three.

**Comment by bennettpeter** [comment]
I believe that edit transports was found to be unnecessary. Users do not normally have a reason to edit those manually. Is there a need for that? The channel scan should fill in all of the needed values for you.

**Comment by white-haired-uncle** [comment]
I've never needed it, just noticed that it was gone.  Same for  Restore Data and Import Icons.  If these were removed intentionally then I think all is well and this should be closed.

My only real concern was the channel scan, and that's a non-issue.

Thanks

**Comment by bennettpeter** [comment]
I don't know if Import Icons is needed. Icons are now supplied with the setup of schedules direct. Maybe import ions is still needed by some people.

Where is Restore Data? I don't know what that is or where it is in the old setup.

**Comment by white-haired-uncle** [comment]
mythtv-setup > channel editor

![Screenshot_2024-03-20_10-08-16](https://github.com/MythTV/mythtv/assets/135195815/fe066f19-aef9-4623-a297-90098222ddfb)

**Comment by bennettpeter** [comment]
I use the Steppes theme.  It seems that theme is missing the Restore Data button. I will look into it.

![Screenshot_2024-03-20_11-50-04](https://github.com/MythTV/mythtv/assets/8069726/afbce1b9-0fa7-4ea2-900f-26904d92088c)

**Comment by bennettpeter** [comment]
I do not understand what Restore Data is supposed to do. What deleted channel does it copy from and to where? I cannot get it to do anything.
![Screenshot_2024-03-20_12-03-51](https://github.com/MythTV/mythtv/assets/8069726/d18af9f6-f3d9-4411-942c-4100c58f3f6b)

**Comment by kmdewaal** [comment]
https://www.mythtv.org/wiki/Channel_Scanning#Restore_Data

**Comment by Steve-Goodey** [comment]
On Wednesday, 20 March 2024 13:58:41 GMT Peter Bennett wrote:
> I don't know if Import Icons is needed. Icons are now supplied with the
> setup of schedules direct. Maybe import ions is still needed by some
> people.
> 

If using EIT exclusively?

-- 
Regards, Steve Goodey
Colchester, England
***@***.***

Hello to Jason Isaacs

**Comment by bennettpeter** [comment]
My task now is to add "Restore Data" and "Import Icons"  to the web app. This will be for the next version, they did not make it into V34.

**Comment by bennettpeter** [comment]
I have added Restore Data to the web app in these commits
2e4657804a
9dc9ae7977
db8c584ad3

**Comment by bennettpeter** [comment]
I have added Download all and Download missing icons to the web app in these commits:
2ed651c840
24aa45eeb2
db8bc84a6c
Still to be done is search and download an icon for a single channel.

**Comment by bennettpeter** [comment]
I have added Icon Search and Download for a single channel. The button is inside the channel details update dialog. Also added a feature to assign to a channel any icon in the channels directory. 
18a9050fdd
a514d6c51a
be785b239c
