### ISSUE TITLE
Webapp upcoming recordings sorted by title

### ISSUE THREAD

**Issue by phippodoplis** [MythTV/mythtv#885]
**Is your feature request related to a problem? Please describe.**
There are several series I record that have episodes repeated and no metadata to indicate which episode they are. I have to go through the upcoming recordings list and set "Don't record" on the duplicates. It's much easier if the list is sorted by title first, then airdate

**Describe the solution you'd like**
Have a clicky thing on the columns headers to enable sorting, like the "recordings" page in the webapp.

**Describe alternatives you've considered**
MythWeb has this feature and is what I use, but I know it may go away soon

**Comment by bennettpeter** [comment]
Mythweb allows sort by date, title, channel or record length. Record length seems the least useful.
This will need a sort parameter to be passed to the API.

**Comment by bennettpeter** [comment]
Support for sorting by sort by date, title or channel has been implemented in the master branch.

**Comment by phippodoplis** [comment]
Thanks for doing this, very useful
