### ISSUE TITLE
Include program title/sub-title in the filename when downloading from the webapp

### ISSUE THREAD

**Issue by phippodoplis** [MythTV/mythtv#886]
**Is your feature request related to a problem? Please describe.**
If I download a program on my phone from the webapp I get a file with just the airdate in the filename, which makes it difficult to identify programs later.

**Describe the solution you'd like**
The file name should include the title (and sub-title or series and episode numbers) in the file name.

**Describe alternatives you've considered**
MythWeb just uses the title, which is fine for movies, not so good for series.

**Comment by bennettpeter** [comment]
Requires a change to the content api to not set a filename or to set a specified filename.Currently it sets the file name of the recording file.
If it does not set the file name we can use the download attribute to set a name.

**Comment by bennettpeter** [comment]
This has been implemented in master.

**Comment by phippodoplis** [comment]
Thanks Peter, last thing stopping me leaving mythweb
