### ISSUE TITLE
Convenience button in webapp upcoming recordings

### ISSUE THREAD

**Issue by phippodoplis** [MythTV/mythtv#887]
**Is your feature request related to a problem? Please describe.**
Trying to use the new web app instead of MythWeb, there are some buttons on the MythWeb upcoming recordings list that would be nice in the webapp. These are:

 * "Don't Record" for a show that is scheduled to record
 * "Activate" for a show that has had a "Don't Record" rule added to remove the "Don't Record"

There are others in MythWeb, but I don't use them

**Describe the solution you'd like**
A button or something to add/remove a do-not-record override rule for a particular scheduled recording

**Describe alternatives you've considered**
Carry on using Mythweb

**Comment by bennettpeter** [comment]
> "Don't Record" for a show that is scheduled to record

Click the paperclip icon. Select "do not record" in schedule type.

> "Activate" for a show that has had a "Don't Record" rule added to remove the "Don't Record"

If a show is not to record it will not be in the upcoming list. Go to the Recording Rules tab, look for the rule with type "Do Not Record" and click the trash can icon next to it.

**Comment by phippodoplis** [comment]
On 2024-03-21 15:48, Peter Bennett wrote:

>> "Don't Record" for a show that is scheduled to record
> 
> Click the paperclip icon. Select "do not record" in schedule type.
> 
>> "Activate" for a show that has had a "Don't Record" rule added to 
>> remove the "Don't Record"
> 
> If a show is not to record it will not be in the upcoming list. Go to 
> the Recording Rules tab, look for the rule with type "Do Not Record" 
> and click the trash can icon next to it.

Hi Peter,

That's all a bit clicky, Mythweb does both of those in one click. But 
thinking about it, it's not a big deal, so mark this as won't fix, or 
just leave it. At the current rate, there won't be anything worth 
recording on Freeview by the time Mythweb finally dies :-|

Cheers and thanks for all your hard work,

Tim.
