### ISSUE TITLE
Webapp URL for editing a recording rule for a program

### ISSUE THREAD

**Issue by phippodoplis** [MythTV/mythtv#888]
**Is your feature request related to a problem? Please describe.**
I have a daily cron job that runs after mythfilldatabase and emails me a list of new program titles together with the description and a clickable link to a MythWeb page to set up a recording rule for that progam. It looks a bit like this, but with the italics shown as a hyperlink

> _Big Trouble in Little China (5ACTION Action film 1986 70%)_
      Kurt Russell, Kim Cattrall, Dennis Dun, James Hong, Victor Wong
   Jack Burto agrees to pick up a friend's girlfriend from the airport,
   but when Miao Yin is kidnapped in front of him, Burton finds she's been...

The first line is a link to https://mythweb.my-domain.net/mythweb/tv/detail/10033/1711915200 where 10033 is the chanid and the other number is unix_timestamp(starttime)

**Describe the solution you'd like**
A link to http://mythbackend.net.home:6544/<something> that will have the recording rule for the program. The recording rule editor that pops up from a progam guide or search is fine, but it is a pop up, and I am too lazy to cut the title and paste into a search box, especially when I have the chanid and starttime available.

**Describe alternatives you've considered**
Mythweb still works for now.

**Comment by bennettpeter** [comment]
I have implemented this. The available parameters are documented in the wiki at https://www.mythtv.org/wiki/Web_Application:Program_Guide . There is also a help (question mark) icon on the Program Guide that links to that wiki page.
