### ISSUE TITLE
modernize mythbrowser plugin (1)

### ISSUE THREAD

**Issue by hoh61** [MythTV/mythtv#890]
**Is your feature request related to a problem? Please describe.**
In germany (and in some other countries maybe too) each internet site has to inform the user on the usage and acceptance of cookies. This is in most cases handled by a pop-up window. The Browser plugin is not able to handle popup-windows, therefore it is not usable for most of the german websites.

**Describe the solution you'd like**
The webbrowser plugin shall be capable of handling of popup windows for the handling of cookie-acceptance. The selected acceptance shall be remembered for the next visit.

**Describe alternatives you've considered**
No alternative solution idea yet.

**Comment by bennettpeter** [comment]
i believe we should deprecate some of the plugins, including mythbrowser, as they have not  been supported for a long time.

**Comment by garybuhrmaster** [comment]
On Sat, Apr 20, 2024 at 1:35 AM Peter Bennett ***@***.***>
wrote:

> i believe we should deprecate some of the plugins, including mythbrowser,
> as they have not been supported for a long time.
>

Related to #327

**Comment by hoh61** [comment]
Having a short look on the given references I see a lot of work if the mythbrowser should survive. I can follow the arguments that it would be easier to use a actual browser. Nevertheless, the idea to go through a mediathek only by using the remote control has still some charme. This is because I'm using a dedicated PC as HTPC without mouse and keyboard.
