### ISSUE TITLE
modernize mythbrowser plugin (2)

### ISSUE THREAD

**Issue by hoh61** [MythTV/mythtv#891]
**Is your feature request related to a problem? Please describe.**
I tried to use the mythbrowser plugin as a tool for accessing different mediatheques. Even if the cookie issue is not generally blocking the access, I noticed, that by tab-ing through the I can enter child windows, however, I wasn't able neither to select a video nor to start and view it. From the description of this plugin I got the impression, that this plugin is capable to play flash movies, which are mostly outdated by today. If this is the only accepted format, this plugin is hardly usable for me.

**Describe the solution you'd like**
Mediatheque videos shall be selectable by tabbed selection (through a remote control and by keybord). Newer and modern encodings shall be playable.

**Describe alternatives you've considered**
As an alternative a mediatheque plugin could be on interest. However, I noticed, that the structure of the mediatheques are changing quite often, the adaptation of a specialized mediatheque module would be hard. Furthermore different mediatheques have different structures, which will make this module more complicated in the realization. I checked  solutions on other media tools and found the most interesting ones not or hardly usable. Therefore for my personal experience this cannot be a real alternative.

**Comment by bennettpeter** [comment]
i believe we should deprecate some of the plugins, including mythbrowser, as they have not  been supported for a long time.
