### ISSUE TITLE
Internet access through proxy server imperfect

### ISSUE THREAD

**Issue by hoh61** [MythTV/mythtv#892]
* **Platform**:
Linux, Linux xxx 5.15.0-101-generic #111-Ubuntu SMP Tue Mar 5 20:16:58 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

* **MythTV version**:
v35-Pre-5e2af89441e and older

* **Package version**:
GIT download

* **Component**:
frontend/backend

### What steps will reproduce the bug?
Starting of mythtv will reproduce the bug. Internet access is blocked through an active proxy server for frontend and backend requests.

Under Linux the system settings for the usage of the proxy server are not recognized and not applied. Only internal servers can be accessed.
The setting of the shell environment variable for the proxy server address is recognized and used. This is valid for the environment variable "http_proxy". However, by this selection any internal server is ignored and I can only access external sources. The environmental variable "noproxy" is not recognized and ignored.
The current standard for all browser to allow an exception list for defined addresses which shall not requested without proxy interface is missing.

### How often does it reproduce? Is there a required condition?
Everytime the proxy environment variable is set/unset

### What is the expected behaviour?
To operate according to the proxy setting rules defined in the system settings, at least a proper implementation of the "noproxy" variable

### What do you see instead?
Simple switch proxy/no proxy for all(!) server requests.

**Comment by bennettpeter** [comment]
What specific actions in MythTV are you using that are affected? What action needs Internet access that does not work and what action needs internal access  that does not work?

**Comment by hoh61** [comment]
Mythweb is an extension that uses internet protocol to respond to external clients in the local network. 
Mythwebbrowser is an extension that should access external web sites. In the same way a few setup tools are accessing some internet resources.
Since I sat up a proxy server years ago to bundle external internet access through this proxy, I couldn't access any of the external setup helpers. In the last month an idea came up to use the mythwebbrowser for accessing mediathek's. Unfortunately the currently implemented proxy support allows only one setting: with or without proxy: mythweb or mythwebbrowser. A selective proxy support, as it is mostly standard nowadays, is missing.

**Comment by bennettpeter** [comment]
There is no i nterest in expanding proxy support for mythwebbrowser. mythweb is deprecated in favor of webapp (backend:6544)
