### ISSUE TITLE
Add support for "Never Record" and "Forget Old" upcoming recordings to Web App

### ISSUE THREAD

**Issue by mymatenige** [MythTV/mythtv#899]
With MythWeb the Upcoming Recordings page showed two options for entries due to be recorded;

1. Don't Record - which would cancel that specific recording for that date/time
2. Never Record - which would cancel that episode recording now and indefinitely

With the newer Web App the Upcoming page shows two icons for entries due to be recorded;

1. Pencil - used for editing the recording rule that relates to the recording
2. Paperclip - used for editing the options for that specific recording

Under the paperclip I can change the Schedule Type to cancel that recording for that date/time (the same as MythWeb's "Don't Record", however there is no equivalent of MythWeb's "Never Record".  I want to keep the recording rule, but ensure that all instances of only that specific episode are removed from upcoming recordings.  It seems that with the Web App I can stop it recording a single instance of the episode, which then causes the backend to schedule recording of the next match of the episode, or I can delete the entire rule, but not stop it recording all instances of a single episode.

Can the equivalent "Never Record" please be added?  I find it very useful for stopping the backend from recording episodes that I have already seen via a different method.  This also implies that the option to reverse this "Forget Old" is also required.

If if helps, these are the code snippets that MythWeb uses can be found in these locations:

https://github.com/MythTV/mythweb/blob/92f0f9bc6d15f6d6534e5d5e40bdddbb6f431254/modules/tv/classes/Program.php#L636

https://github.com/MythTV/mythweb/blob/92f0f9bc6d15f6d6534e5d5e40bdddbb6f431254/modules/tv/classes/Program.php#L604

I'm not suggesting that the Web App should do it in the same way, especially as I have doubts that "Forget Old" actually works.  Instead RecordingInfo::ApplyNeverRecord() and RecordingInfo::ForgetHistory() seem to be more suitable.

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Ideally an option on the row presented on the Upcoming tab for "Never Record", similar to that present in MythWeb.  With the additional option to "Forget Old" if an entry is set to "Never Record".

**Describe alternatives you've considered**
I'm not aware that this can be resolved via any other route with the Web App.

**Comment by bennettpeter** [comment]
Fixed in b1203fe77e and f593133c74
