### ISSUE TITLE
webapp always sets db ping option 

### ISSUE THREAD

**Issue by white-haired-uncle** [MythTV/mythtv#918]
* **Platform**:
`Linux mythbackend 6.5.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue May  7 09:00:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

* **MythTV version**:
```
MythTV Version : v34.0-18-g5590d0d5eb
MythTV Branch : fixes/34
Network Protocol : 91
Library API : 34.20220913-1
QT Version : 5.15.3
Options compiled in:
 linux profile use_hidesyms using_alsa using_oss using_pulse using_pulseoutput using_backend using_bindings_perl using_bindings_python using_bindings_php using_dvb using_firewire using_frontend using_hdhomerun using_satip using_vbox using_ceton using_joystick_menu using_libcec using_libcrypto using_gnutls using_libdns_sd using_libxml2 using_lirc using_mheg using_opengl using_egl using_qtwebkit using_qtscript using_qtdbus using_taglib using_v4l2 using_v4l2prime using_x11 using_system_libbluray using_system_libudfread using_systemd_notify using_systemd_journal using_drm using_bindings_perl using_bindings_python using_bindings_php using_freetype2 using_mythtranscode using_opengl using_egl using_drm using_vaapi using_nvdec using_vdpau using_ffmpeg_threads using_mheg using_libass using_libxml2 using_libmp3lame

```

* **Package version**:

* **Component**:
webapp

### What steps will reproduce the bug?

1. Start with the option to ping the db host disabled in ~mythtv/.mythtv/config.xml.
2. Make any valid change in http://mythbackend:6544/setupwizard/dbsetup and save
3. Note that `<PingHost>` is now set to true.

### How often does it reproduce? Is there a required condition?

Always for me.

### What is the expected behaviour?

The option to enable/disable ping of the db host should be available in webapp, and saved correctly in config.xml.

### Additional information

While not common in the kind of environments mythtv is going to be installed in, a host not responding to ping is (or was last time I looked) a perfectly valid condition.

**Comment by bennettpeter** [comment]
The ping option is no longer used. Since 2017 the code uses a port check rather than a ping, and always does the check, regardless of the setting. The ping check should really be removed from the mythfrontend setup and from the config.xml file. I don't know why the web app is always setting it true.

**Comment by bennettpeter** [comment]
The web app sets it true because the default for that field is true. The web app does not get or set the field with the API. Saving the changes creates a new database setting structure and overwrites what is there. The new setting has the ping as true.

**Comment by bennettpeter** [comment]
I have removed the database ping setting from mythfrontend and defaulted it to false in config.xml.
