### ISSUE TITLE
Search Lists for Programs in Web Interface :6544

### ISSUE THREAD

**Issue by krisbee** [MythTV/mythtv#920]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The web interface, to replace mythweb functionality, would be nice to have to the ability to use search lists (new titles, in particular), so you can search for programs to record generally without knowing specific names or titles.  Premieres are particularly useful - right now you have to go into a proper frontend to accomplish this.  Mythweb used to do this, but the New Titles/Premieres start to not work right over the years.

**Describe alternatives you've considered**
At the moment, I have to use a proper mythfrontend, but we only use Leanfront here, so I have to log onto the backend computer just to search for new titles.

**Comment by bennettpeter** [comment]
See #898 for updates
