### ISSUE TITLE
Record rule; recording Schedule options doesn't work

### ISSUE THREAD

**Issue by mtraxiot** [MythTV/mythtv#925]
* **Platform**:
Ubuntu
* **MythTV version**:
V34
* **Package version**:
34.0+fixes.202406302352.061af3b0aa~ubuntu22.04.1
* **Component**:
Mythfrontend
### What steps will reproduce the bug?
Recording Rules -> Select program -> Schedule options 

### How often does it reproduce? Is there a required condition?
all the time
### What is the expected behaviour?
select specific schedule options eg Prime time

### What do you see instead?
button does nothing

**Comment by bennettpeter** [comment]
It works fine on master version with default theme. What theme are you using?

**Comment by mtraxiot** [comment]
I was using Functionality , but I switched to Mythbuntu and that works.
it looks like an issue with that specific theme.

thanks for the info
