### ISSUE TITLE
Web App uses incorrect filename to stream

### ISSUE THREAD

**Issue by SingingDwarf** [MythTV/mythtv#937]
* **Platform**: Linux ford 5.15.0-118-generic #128-Ubuntu SMP Fri Jul 5 09:28:59 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

* **MythTV version**: fixes/32 [v32.0+fixes.20220325.f69ce764b7-0ubuntu1]

* **Package version**:

* **Component**: Web App

### What steps will reproduce the bug?

Attempt to stream a recording

### How often does it reproduce? Is there a required condition?

Always.

### What is the expected behaviour?

Stream plays

### What do you see instead?

No error, stream does not play.
Browser DevTools gives 404 error.

### Additional information

DevTools show file to stream is called http://ford.local:6544/StorageGroup/Streaming/2005_20220712020500.mpg.640x360_600kV_64kA.m3u8 but file created in the Streaming Storage Group is 2005_20220712020500.mpg.640x368_600kV_64kA.m3u8

Note the difference between 640x368 and 640x360

**Comment by bennettpeter** [comment]
The web app in V32 is incomplete, was never completed, and will not be fixed. It has been completely rewritten in MythTV V34.
