### ISSUE TITLE
Mythtv web backend - add Encoder device to status page

### ISSUE THREAD

**Issue by dheian** [MythTV/mythtv#945]
On the web backend status page, the Encoder Status shows:

"Encoder 1 is on host bhmf..."

On Leanfront's backend status it shows:

"Encoder 1 [DEVICEID] is local on host bhmf"

It's a simple difference but if you have multiple devices and doing some hardware debugging it's easier than trying to remember which encoders are which device. :) 

Any chance the device ID could be added to the web backend status page?

**Comment by bennettpeter** [comment]
As a workaround - you can see the status page as it is displayed on leanfront by using this URL
`http://<backend>:6544/Status/GetStatusHTML`
