### ISSUE TITLE
webapp: sort order for upcoming recordings

### ISSUE THREAD

**Issue by white-haired-uncle** [MythTV/mythtv#953]
* **Platform**:
`Linux mythbackend 6.5.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue May  7 09:00:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

* **MythTV version**:
v35-Pre-331-g41b921c949-dirty
* **Package version**:

* **Component**:

### What steps will reproduce the bug?

http://mythbackend:6544/dashboard/upcoming

1) The sort for Date will sort by date, but only in ascending order
2) The sort for Title will sort by Title, but only in ascending order
3) The sort for Channel, well I'm not sure what that is doing.  It doesn't sort by channel, but if you've altered the order by using Title sort, it will either sort by ascending date or just reset the list with no sort order (which are the same thing - now that I think of it, I'm not sure that Date sort works either as it could just be resetting/removing the sort).

P.S.  Would be nice to be able to sort by Status when All Status Values is checked, particularly to look for recording conflicts (even better to be able to filter, say replace the All Status Values with a dropdown list with a checkbox for each possible/current status value).

**Comment by bennettpeter** [comment]
I fixed the error in the descending order sort.

I do not see the problem with channel sort. It sorts by channel number if it is an actual number. For example on my test system I see a mixture of "31 TBS", "1434 TBSHD", "14 WSBK", "1038 WSBKDT" and others in the channel column. Sorting by channel sorts them by the number not the call sign. Sorting in reverse now also works, using the numbers. Do you have numeric channel numbers? If not the sort will likely do nothing useful.

With regard to sorting by status, the default view if you do not select "All Status Values" gives 4 status values: 
Pending
WillRecord
Offline
Conflict
So to see conflicts you do not need to select "All Status Values". Does this help?

**Comment by bennettpeter** [comment]
I will set some channel numbers the way you say and retest the channel number sort. 

Ctrl-f may not work because upcoming uses a lazy load, items not yet visible are not populated until you scroll down to them.

I will look into the status sort or select.

**Comment by bennettpeter** [comment]
Status sort is problematic, as the status values are translated to English or other languages after the sort is done.

**Comment by bennettpeter** [comment]
Channel number sort is fixed.

**Comment by bennettpeter** [comment]
I added a dropdown to filter on status.
