### ISSUE TITLE
Max Recordings = 1, 'Schedule as Group' combo causes conflicts

### ISSUE THREAD

**Issue by SteveErl** [MythTV/mythtv#964]
* **Platform**: Linux Mint 21.3, 5.15.0-124-generic 134-Ubuntu SMP Fri Sep 27 20:20:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

* **MythTV version**: fixes/34

* **Package version**:

* **Component**:

### What steps will reproduce the bug?

I have Manual Record rules to record two shows which air at the same time. One is "**Tracker**" on channel 189, and the other is "**Ridley**" on channel 191. Even though there are many available tuners, the **Scheduler** picked the same tuner, **Prim0**, to record both shows. 
![BeforeFixSmall](https://github.com/user-attachments/assets/8d4819f1-4ff4-4def-ab1c-0d675568f6ff)
This is an HdHomerun Prime, using a cablecard, so multiplex recording is not possible. There are 3 tuners, and the cablecard can decrypt one channel per tuner. I have configured 3 **Capture Cards** for the HdHomerun Prime, **Prim0**, **Prim1**, **Prim2**. Here is the relevant portion of the **Input Connections** configuration for **Prim0**.
![Sched1](https://github.com/user-attachments/assets/caa836e6-3c03-4a9f-946d-5d2a9a33ad96)
Note that I had the **Schedule as Group** option enabled. I'm not sure why. I didn't think it would matter with **Max Recordings** set to 1. In the text under **Max Recordings**, we're told that MythTV will only do multiplex recordings for values other than 1.

Each Sunday night, the supposed recording of "Tracker" would hold the contents of the "Ridley" show. There was one week when "Tracker" started early at 6:30pm. The recording had the correct show for half an hour, and then switched to "Ridley" in the middle of it.

I suspected that the **Scheduler** was improperly trying to do multiplex recordings, so I checked the database.

```
mysql> select channum, mplexid, callsign, sourceID from channel where mplexid=428;
+---------+---------+-----------------+----------+
| channum | mplexid | callsign        | sourceID |
+---------+---------+-----------------+----------+
| 368     |     428 | WTTW Vme        |        4 |
| 369     |     428 | WTTW Create     |        4 |
| 191     |     428 | WTTW - PBS - HD |        4 |
| 189     |     428 | WBBM HD         |        4 |
+---------+---------+-----------------+----------+
4 rows in set (0.00 sec)
```
The two channels, 189 and 191, do share the same multiplex ID.
```
mysql> SELECT cardid, displayname, parentid, schedgroup, reclimit FROM capturecard WHERE sourceid > 0 ORDER BY cardid;
+--------+-------------+----------+------------+----------+
| cardid | displayname | parentid | schedgroup | reclimit |
+--------+-------------+----------+------------+----------+
|     96 | Prim0       |        0 |          1 |        1 |
|     97 | Prim1       |        0 |          0 |        1 |
|     98 | Prim2       |        0 |          0 |        1 |
|     99 | Prim3       |        0 |          0 |        1 |
|    100 | Prim4       |        0 |          0 |        1 |
|    101 | Prim5       |        0 |          0 |        1 |
|    108 | Prim6       |        0 |          0 |        1 |
|    109 | Prim7       |        0 |          0 |        1 |
|    110 | Prim8       |        0 |          0 |        1 |
+--------+-------------+----------+------------+----------+
9 rows in set (0.00 sec)
```
Experimentation revealed that the **Scheduler** does not make this error when **Schedule as Group** is disabled.
![Sched2](https://github.com/user-attachments/assets/72c886a8-ee28-42b8-bb3a-b2a47354343d)
![AfterFixSmall](https://github.com/user-attachments/assets/132b6cbe-5294-450b-be53-7de319c1a506)

### How often does it reproduce? Is there a required condition?
Always. Max Recordings = 1, 'Schedule as Group' = true, and two or more shows, sharing the same multiplex, set to record at the same time.

### What is the expected behaviour?
The Scheduler should factor in the value of Max Recordings when deciding whether multiplex recording is allowed. If Max Recordings = 1, multiplex recording should not be allowed.
![Sched1](https://github.com/user-attachments/assets/caa836e6-3c03-4a9f-946d-5d2a9a33ad96)
![AfterFixSmall](https://github.com/user-attachments/assets/132b6cbe-5294-450b-be53-7de319c1a506)

### What do you see instead?
"Tracker" and "Ridley" are scheduled to record at the same time on the same tuner.
![BeforeFixSmall](https://github.com/user-attachments/assets/8d4819f1-4ff4-4def-ab1c-0d675568f6ff)

**Comment by gigem** [comment]
Are you using your HDHR Prime(s) for clear QAM channels, ie. without a cablecard?  That's the only case where you channels should have non-zero/null mplexids.  If you are using a cablecard, your channels are definitely messed up.  How did you populate the channels table?

To see why the scheduler does what it does, please run "mythbackend --testsched --verbose schedule --loglevel debug" and provide that output here.

Finally, your input table looks like you have 3 HDHR Primes.  Is that correct?  I'm just checking to make sure something else isn't wrong.

**Comment by SteveErl** [comment]
Long ago, I was the one who submitted the code to allow use of HdHomerun Prime clear QAM channels (without a cablecard). But soon after that, my cable company started encrypting every channel, so I got a cablecard. And I have added two more Primes with cablecards.

I populated the channels tables long ago, using a much older release of MythTv. I think, back then, the scanner didn't work with cablecard decryption, so I wrote my own code to get it to work. That's probably why my database has non-zero multiplexids.

I have a fix for this issue, but if it only exists due to my weird database, maybe it's not worth merging in.

I'll try doing a fresh scan using another computer, and see if it works after using the official scanning code.

**Comment by gigem** [comment]
That makes sense for how your channel table got to where it is.  Fixing that will probably fix yor issue.

Also, I suggest you consider using Gary Buhrmaster's very fine, mythhdhrrecorder instead of the internal HDHR recorder.  EVen after I fixed the internal recorder to properly share inputs long ago, I switched to using mythhdhrrecorder myself.

**Comment by SteveErl** [comment]
I installed the fixes/34 release. I deleted all the existing channel and dtv_multiplex rows. I tried running a Full Scan, which found no channels at all. Then I tried HDHomeRun Channel Import, which is really fast. This created a channel row for 397 channels known by the HdHomerun Prime.

```
mysql> select * from channel where channum='171';
+--------+---------+--------+----------+----------+-------+------+----------+--------------+---------+-------------+----------+------------+--------+-------+----------+---------+---------------+---------------+---------+-----------+--------------+----------+-----------------+-----------------+---------------------+-------------------+------------+--------+---------+
| chanid | channum | freqid | sourceid | callsign | name  | icon | finetune | videofilters | xmltvid | recpriority | contrast | brightness | colour | hue   | tvformat | visible | outputfilters | useonairguide | mplexid | serviceid | service_type | tmoffset | atsc_major_chan | atsc_minor_chan | last_record         | default_authority | commmethod | iptvid | deleted |
+--------+---------+--------+----------+----------+-------+------+----------+--------------+---------+-------------+----------+------------+--------+-------+----------+---------+---------------+---------------+---------+-----------+--------------+----------+-----------------+-----------------+---------------------+-------------------+------------+--------+---------+
| 120171 | 171     | NULL   |       12 | AMCHD    | AMCHD |      |     NULL |              |         |           0 |    32768 |      32768 |  32768 | 32768 | Default  |       1 |               |             1 |     147 |         1 |            0 |        0 |               0 |               0 | 0000-00-00 00:00:00 |                   |         -1 |   NULL | NULL    |
+--------+---------+--------+----------+----------+-------+------+----------+--------------+---------+-------------+----------+------------+--------+-------+----------+---------+---------------+---------------+---------+-----------+--------------+----------+-----------------+-----------------+---------------------+-------------------+------------+--------+---------+
1 row in set (0.00 sec)
```

 It created one dtv_multiplex:

```
mysql> select * from dtv_multiplex;
+---------+----------+-------------+-----------+-----------+-----------+------------+------+----------+------------+-----------+--------------+-------------------+----------------+---------+---------------+-----------+--------------+-----------+---------+------------+----------------+---------------------+-------------------+
| mplexid | sourceid | transportid | networkid | frequency | inversion | symbolrate | fec  | polarity | modulation | bandwidth | lp_code_rate | transmission_mode | guard_interval | visible | constellation | hierarchy | hp_code_rate | mod_sys   | rolloff | sistandard | serviceversion | updatetimestamp     | default_authority |
+---------+----------+-------------+-----------+-----------+-----------+------------+------+----------+------------+-----------+--------------+-------------------+----------------+---------+---------------+-----------+--------------+-----------+---------+------------+----------------+---------------------+-------------------+
|     147 |       12 |           0 |         0 | 267000000 | a         |          0 | auto | v        | auto       | a         | auto         | a                 | auto           |       0 | auto          | a         | auto         | UNDEFINED | 0.35    | dvb        |             33 | 2024-11-06 19:49:18 |                   |
+---------+----------+-------------+-----------+-----------+-----------+------------+------+----------+------------+-----------+--------------+-------------------+----------------+---------+---------------+-----------+--------------+-----------+---------+------------+----------------+---------------------+-------------------+
1 row in set (0.00 sec)
```
Every one of the 397 channels has a mplexid set to match that single dtv_multiplex entry, 147.

That disproves your assertion that every channel should have a mplexid of zero.

The channel scan using fixes/34 doesn't really work though. None of the channels can be tuned in. I'll have to add my own code to set the channel using the 
`hdhomerun_config <ID> set /tuner<n>/vchannel <vchannel>
`syntax. The official code doesn't do that, so I don't understand how it's supposed to work without a bunch of extra effort. Is the HDHomeRun Channel Import just a partial implementation?

As it stands. If I were able to tune in the discovered channels, each one would have the same mplexid, and the failure I described in this Issue would happen if **Schedule as Group** were set to true.

**Comment by gigem** [comment]
> Every one of the 397 channels has a mplexid set to match that single dtv_multiplex entry, 147. That entry is a lie for a huge majority of them.
> 
> ```
> $ hdhomerun_config 13122384 set /tuner0/channel qam:267000000
> $ hdhomerun_config 13122384 get /tuner0/streaminfo
> 2: 10 GVACC2 (encrypted)
> 3: 17 PUACC (encrypted)
> 4: 18 PAARL1 (encrypted)
> 8: 99 EDACCC (encrypted)
> 911: 0
> tsid=0x8389
> ```
> 
> So there are only 4 out of 397 channels where the proper frequency is specified.
> 
> That disproves your assertion that every channel must have a mplexid of zero or NULL. The standard process for discovering channels on a HdHomerun Prime gives us a non-zero/non-NULL value for mplexid.

No, it proves there is something wrong with importing channels.  When using virtual channel numbers with HDHRs, duplicate, non-zero mplexids will absolutely cause problems.

**Comment by SteveErl** [comment]
Here's where the Multiplex is created and then used in creating Channel entries.

libs/libmythtv/channelscan/hdhrchannelfetcher.cpp
```
306 void HDHRChannelFetcher::run(void)
307 {
...
424             // A new dtv_multiplex entry will be created if necessary, otherwise an existing one is returned
425             uint mplexID = ChannelUtil::CreateMultiplex(m_sourceId, sistandard, frequency, modulation,
426                                                         transportID, networkID, symbolrate, bandwidth,
427                                                         'v', 'a', 'a', QString(), QString(), 'a', QString(),
428                                                         QString(), QString(), modsys.toString(), "0.35");
429             if (mplexID == 0)
430             {
431                 LOG(VB_GENERAL, LOG_ERR, QString("No multiplex for %1 sid:%2 freq:%3 url:%4")
432                     .arg(msg).arg(serviceID, -5, 10, QChar(' ')).arg(frequency).arg((*it).m_tuning.GetDataURL().toString()));
433                 continue;
434             }
435 
436             if (adding_channel)
437             {
438                 ChannelUtil::CreateChannel(mplexID, m_sourceId, chanid, name, name,
439                                         channum, serviceID, atsc_major_channel, atsc_minor_channel,
440                                         use_on_air_guide, kChannelVisible, QString(),
441                                         QString(), "Default", QString());
442 
443                 ChannelUtil::CreateIPTVTuningData(chanid, (*it).m_tuning);
444             }
```

**Comment by SteveErl** [comment]
I'm not sure what types of HdHomerun devices the above code applies to. Maybe it shouldn't create a Multiplex for a Prime using a cablecard? Is it supposed to work for other HdHomeruns? The HDHomeRun Channel Import fails on my Dual. I just get "Scan Error Downloading Channel List Failed". Do other models like the Flex ones allow downloading a channel list?

If other types of HdHomerun might work with this scanning option, then we could condition the creation of a Multiplex and use of the corresponding ID in Channel creation for tuner types not equal to kTunerTypeOCUR.

**Comment by bennettpeter** [comment]
Populating the channel list when using a hd homerun with cable card should be done from the listing service. Multiplexes do not apply in that case, there are virtual channel numbers assigned to the decrypted channels. When more than 1 channel exists on one frequency, it is presented as a separate channel when decrypted. Performing a scan is not useful. Tuning the channel is done using only the virtual channel number.

**Comment by SteveErl** [comment]
There is no requirement that users _have_ to use a listing service.

Some HdHomerun models, including the **Prime**, allow us to retrieve a channel list in XML format directly from the device. That's what the  **HDHomeRun Channel Import** type of "scan" does. It's extremely fast, and provides a complete list of all the virtual channel numbers and channel names available. It would work great if it weren't improperly setting the **mplexid** value in created **channel** rows in the database.

I have 3 **Prime** and a **Dual**. I run an EIT scan on the Dual to collect the OTA listing information. I added a little bit of code into eithelper.cpp which copies the EIT data for the OTA channels over to the corresponding cable channels on my Prime. This gives me free listing data for all such channels. It works great.

Performing a scan **_is_** useful for users who are not using a listing service. Yes, tuning the channels is done using the virtual channel number.

**Comment by garybuhrmaster** [comment]
> There is no requirement that users _have_ to use a listing service.

No, but in practice, in the US, you need guide data for any useful functionality, and the guide service provides the channel information.

One of the core developers, a while ago, suggested they were considering improvements in loading the channel information, but they were not highly motivated to prioritize that work because they had other itches to scratch, and were using an unsupported 3rd party solution that was sufficient for their immediate needs.

In practice, this is also a time limited issue, as most cable operators are in various phases of eliminating CableCARD support (two have already done so, all others have stated they have stopped offering new CableCARDs, and two operators have announced specific future changes that eliminate them in the (still not precisely defined, but upcoming) future, so while I don't schedule scratching for others, I suspect there is likely even less motivation than before.  Cable linear QAM was an improvement over analogue, but it, too, is reaching its end.  One can choose to ride the CableCARD train until it reaches the end of the line (I may do so for another few years until D4.0 FDX), but I would never suggest that linear QAM and CableCARD has more than a few years of viability ("He's dead, Jim").

**Comment by SteveErl** [comment]
I don't use a listing service, but my system is still highly useful. I just write a large number of Manual Record rules. 

The **Max Recordings** setting is weird. The description underneath it in _SetupWizard_ is misleading. It gets completely ignored by the scheduler. It's only the **Schedule as Group** setting which enables or disables multiple recordings on a shared multiplex.

I've got a fix for **HDHomeRun Channel Import** which will make it fully functional for HdHomerun Primes. With this update, it's possible to scan for channels and then tune them in or record on them. I'll commit that fix soon.

My cable company stopped providing new cablecards a couple of weeks ago, but they say we can keep using the ones we have. Not sure how long that will last. :-1: 

**Miracle Max**: “There’s a big difference between mostly dead and all dead. Mostly dead is slightly alive. With all dead, well, with all dead there’s usually only one thing you can do.”

**Comment by gigem** [comment]
> The **Max Recordings** setting is weird. The description underneath it in _SetupWizard_ is misleading. It gets completely ignored by the scheduler. It's only the **Schedule as Group** setting which enables or disables multiple recordings on a shared multiplex.

That's not totally true.  When **Schedule as Group** is false, **Max Recordings** works exactly as described.  When **Schedule as Group** is true, however, it will automatically increase the limit as needed.  That's an oversight in the help text.

> I've got a fix for **HDHomeRun Channel Import** which will make it fully functional for HdHomerun Primes. With this update, it's possible to scan for channels and then tune them in or record on them. I'll commit that fix soon.

Please attach it to this ticket and I'll review it.

**Comment by kmdewaal** [comment]
> > The Max Recordings setting is weird. The description underneath it in SetupWizard is misleading. It gets completely ignored by the scheduler. It's only the Schedule as Group setting which enables or disables multiple recordings on a shared multiplex.
> 
> 
> That's not totally true. When Schedule as Group is false, Max Recordings works exactly as described. When Schedule as Group is true, however, it will automatically increase the limit as needed. That's an oversight in the help text.
> 

Both settings are documented in the Channel Scanning Wiki page starting at paragraph https://www.mythtv.org/wiki/Channel_Scanning#Max_Recordings

The Schedule as Group setting does control two features: automatically creating additional virtual tuners and the Schedule as Group. I think it would be better if there were separate settings, one for each feature; this has been discussed in the past but, as I understood it from gigem, the code is not easy to split so it must be one setting.

Of the two features I personally think that creating additional virtual tuners is for the users the most important one. If the setting would be renamed to e.g. "Create virtual tuners on demand" it would probably create less confusion.

**Comment by kmdewaal** [comment]
> I'm not sure what types of HdHomerun devices the above code applies to. Maybe it shouldn't create a Multiplex for a Prime using a cablecard? Is it supposed to work for other HdHomeruns? The HDHomeRun Channel Import fails on my Dual. I just get "Scan Error Downloading Channel List Failed". Do other models like the Flex ones allow downloading a channel list?
> 
> If other types of HdHomerun might work with this scanning option, then we could condition the creation of a Multiplex and use of the corresponding ID in Channel creation for tuner types not equal to kTunerTypeOCUR.

The HDHomeRun Channel Import code has been written for and tested mainly with European DVB, both DVB-C and DVB-T2. It has also been tested against an XML file from an American HDHomeRun but that was one with unencrypted channel, so not a CableCard.
Thanks for your fix to support also the CableCard flavour, the fix looks good and I tested it with DVB-C succesfully.

**Comment by SteveErl** [comment]
@kmdewaal - The change to scheduler.cpp was just to back out a change I had previously pushed, commit 4b31dd1. I had added access to **reclimit** and checked those values when determining **mplexid_ok**. Based on the subsequent comments, I learned that was not needed. Perhaps I should also back out the code which provided new access to **reclimit**?  I didn't want to back out everything from that commit because in scheduler.cpp, I significantly improved a log message around line 1098, and fixed a typo in a log message around line 1148. 

Should I do another push to remove the now unused access to **reclimit**? Will a Pull request take the results of all 3 pushes combined? If I changed scheduler.h in the first and remove that change in the last, will the resulting Pull request avoid touching that file?

**Comment by kmdewaal** [comment]
@SteveErl it would be easiest for me and gigem if you create two separate pull requests to  master, one for the hdhomerunchannelfetcher and one for the scheduler.

**Comment by SteveErl** [comment]
I've backed out all the changes to scheduler. The scheduler log message improvements will be handled by Issue #967. After all the commits in this branch, the only changes are to hdhomerunchannelfetcher.cpp.

**Comment by SteveErl** [comment]
Pull Request #968 has been made.

**Comment by gigem** [comment]
Only Tuesday and it's already been a very hectic week.  I'm just no looking at the proposed changes here.

  I'm mostly ambivalent regarding the HDHR channel import changes.  As previously stated, I think mythhdhrrecorder is the better choice over the builtin recorder in most cases these days.  One suggestion I have for the importer is to have an option to import virtual channel numbers (a la with cablecard) or import frequency/protocol/etc.

Regarding the reclimit changes, I don't like them.  It looks they were backed out and weren't committed.  Good.  After giving this some thought, my preference is to disable the reclimit setting when schedule as group is enabled.

**Comment by gigem** [comment]
I was referring to the non-prime HDHomeRuns and primes without cablecards.  They can tune by virtual channel number or  by frequency/protocol/etc.  Your change correctly handles the with cablecard case which must use virtual channel numbers.  All of the other cases should let the user choose which way to import.  In addition, the default should probably be virtual channel numbers as that's what Silicon Dust recommends.
