### ISSUE TITLE
v35 master web-app input connection full scan or hdhr channel import formatting issue.

### ISSUE THREAD

**Issue by jfabernathy** [MythTV/mythtv#992]
* **Platform**:Intel NUC with HDHomerun tuner

* **MythTV version**:master v35

* **Package version**:web-app

* **Component**:input connection setup full scan or hdhr channel import

### What steps will reproduce the bug?
just do the scan
This is a formatting problem only for me.

### Additional information

![Screenshot from 2024-12-08 08-49-14](https://github.com/user-attachments/assets/cd978fff-b247-4706-950b-770814fedf47)

**Comment by kmdewaal** [comment]
Same output formatting issue (probably missing newline at end of string) also present for DVB satellite tuning.
